### ISSUE TITLE
Fehlende Literaturverzeichniseinträge

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#100]
Aus den Entstehungszeugnissen:

* faust://bibliography/WA_Ergaenzung
* faust://bibliography/390376

**Comment by gerritbruening** [comment]
`faust://bibliography/WA_Ergaenzung` ist ein Verscheibebahnhof mit noch nicht sauberem XML. @sandrakrause kann näheres sagen. Aus Beta 3 rauslassen?

**Comment by dietmarpravida** [comment]
Wo kommt faust://bibliography/390376 denn vor?

**Comment by thvitt** [comment]
faust://bibliography/390376 Entstehungszeugnisse: Pniower Nr. 765

**Comment by dietmarpravida** [comment]
Okay, das sind die Verweise auf Faust-Handschriften bei Pniower (dazu gibt es auch ein anderes Issue, glaube ich). In sollchen Fällen sind ein Teil unserer Handschriften zugleich datierungsrelevante Zeugnisse, z.B. wegen einer angebrachten Datierung o.ä. @thvitt Hast du darüber schon mal mit Gerrit gerpochen?

**Comment by dietmarpravida** [comment]
Dieser Issue wohl zum Issue Fehlende Literaturverzeichniseinträge #100?

**Comment by thvitt** [comment]
390376 ist _keine_ Handschrift der Edition (dieser Fall würde über die Spalte mit den Siglen abgehandelt). Der Eintrag [kommt von hier](https://faustedition.uni-wuerzburg.de/xml/testimony/manuscript/), das ist wohl aussortiert, denn man findet es noch [im attic-Ordner](https://faustedition.uni-wuerzburg.de/xml/attic/documents/gsa/gsa_390376.xml), aber nicht bei den Hs. der Edition.

**Comment by sandrakrause** [comment]
Ja, WA_Ergaenzung (und auch -WA_Ergaenzung_II) sollte auf jeden Fall aus dem Release rausgelassen werden.
Es sind im Prinzip nur Sammelbecken für fehlende Zeugnisse.
Die sauberen Zeugnisse sortiere ich in die jeweiligen bestehenden WA-xmls ein.
Zurück bleiben dann nur noch die unsauberen xmls, die in der Form nicht veröffentlicht werden sollten.

**Comment by thvitt** [comment]
Der ex. Filter filtert alles, was mit `-` beginnt bereits aus, also hieße WA_Ergaenzung.xml am besten `-WA_Ergaenzung.xml`

**Comment by sandrakrause** [comment]
Okay, das ist prima, dann benenne ich die Datei am Donnerstag enstsprechend um.

**Comment by dietmarpravida** [comment]
390376 (Handschrift einer Tagebuchaufzeichnung Eckermanns) hat keinen Anspruch auf einen Eintrag in der Bibiographie (gehört zu Pniower 765 bzw. WA I 15.2, S. 9), mag das technisch gelöst werden wie es will

**Comment by dietmarpravida** [comment]
@thvitt Ich habe hier wirklich keine Ahnung, was ich hier (für Beta3) tun kann.

**Comment by thvitt** [comment]
nix. Überlegt euch halt irgendwann, wie ihr damit umgehen wollt.

**Comment by dietmarpravida** [comment]
cf #622
