### ISSUE TITLE
selbstreferenzielle Milestones

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#103]
In den folgenden Instanzen zeigt das `spanTo`-Attribut des `<milestone unit="testimony">` auf den Startmilestone selbst, sodass der Inhalt des Entstehungszeugnisses entsprechend leer ist. Bitte so korrigieren, dass es auf den entsprechenden end-`<anchor/>` zeigt.

```xml
INFO : testimony.xpl:52:35:ERROR: graef_1277 spans to itself in wa_III_10!
INFO : testimony.xpl:52:35:ERROR: graef_863a spans to itself in wa_IV_7!
INFO : testimony.xpl:52:35:ERROR: pniower_105 spans to itself in jonas1892-1897_5!
INFO : testimony.xpl:52:35:ERROR: quz_III-44A spans to itself in quz_3!
```

Vgl. faustedition/faust-gen-html#133

**Comment by sandrakrause** [comment]
Ist jetzt korrigiert.

**Comment by thvitt** [comment]
INFO : testimony.xpl:61:35:ERROR: quz_I-277 spans to itself in wa_I_32!

**Comment by sandrakrause** [comment]
Ist korrigiert.
