### ISSUE TITLE
Gräf 1531 / 1521

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#106]
in wa_IV_43.xml:

```xml
                  <milestone unit="testimony" spanTo="#graef_1531_end" xml:id="graef_1531"
                     next="#graef_1521"/>/&gt;Lassen Sie mich nun zuerst das Vergnügen ausdrücken,
                  welches Sie durch den Antheil an <rs>Helena</rs> mir gewährt haben. Bey der hohen
```

1. `/&gt;` ist wohl zuviel?
2. next="#graef_1521" ist überraschend. Ist Gräf 1521 tatsächlich die Fortsetzung von Gräf 1531? Es gibt auch keinen Tabelleneintrag für [Gräf 1521](http://dev.faustedition.net/testimony/graef_1521). Nebenwirkung faustedition/faust-gen-html#139

**Comment by dietmarpravida** [comment]
Hm, schwierig. 1521 ist tatsächlich eine Beilage zu 1531. "/&gt;" ist sachlich richtig (es ist von Goethe mit TInte geschrieben), dürfte aber hier ein Irrläufer sein, ich kenne die Codierung der Zeugnisse aber nicht.
 
@gerritbruening Da Gräf 1521 zwei Faustverse enthält (9623f.), müsste das zeugnis auch unter den Handschriften enthalten sein? Ich finde es dort nicht.

**Comment by thvitt** [comment]
ah, gut, es sah so nach Irrläufer aus für mein ungeschultes Auge :)

**Comment by sandrakrause** [comment]
&gt; entfernt

**Comment by gerritbruening** [comment]
Das Zitat der Verse
> Denn wie leuchtet's ihm zu Haupten? Was erglänzt ist schwer zu sagen,
Ist es Goldschmuck, ist es Flamme übermächtiger Geisteskraft.

haben wir bislang nicht als Überlieferung angesehen. Sollten wir das?

**Comment by dietmarpravida** [comment]
Nein, ich erinnere mich, dass wir das vor schon sehr langer Zeit einmal ausdrücklich ausgeschossen haben,

**Comment by gerritbruening** [comment]
Umso besser!

Ist damit die obige Frage
> müsste das Zeugnis auch unter den Handschriften enthalten sein?

(https://github.com/faustedition/xml/issues/106#issuecomment-324928813) erledigt?

**Comment by dietmarpravida** [comment]
man müsste erstmal prüfen, wie Gräf 1531 / 1521 jetzt in den testimonies aussehen, ich habe daher noch gezögert, den Issue zu schließen

**Comment by sandrakrause** [comment]
Die beiden Zeugnisse sehen beim Aufrufen aus der Tabelle eigentlich normal aus.
Gräf 1521 steht in derselben Datei wie 1531 und ist dort unter der Überschrift Beilage [Concept] unten drunter angefügt.
s. http://dev.faustedition.net/testimony/graef_1531#graef_1531
Da Gräf 1521 nicht in der Tabelle verzeichet ist, ist es nicht möglich, dieses Zeugnis direkt aufzurufen, man kommt nur dorthin, wenn man 1531 aufruft.
1521 ist auch im Text nicht als 1521 erkennbar, dort steht nur "Gräf Nr. 1531 (weiter)".
Insofern wird 1521 im Prinzip als Teil von 1531 behandelt und nicht als eigenständiges Zeugnis.

**Comment by gerritbruening** [comment]
> Da Gräf 1521 nicht in der Tabelle verzeichet ist, ist es nicht möglich, dieses Zeugnis direkt aufzurufen

(@sandrakrause)
Das scheint mir ein wichtiger Punkt zu sein.
Als erstes habe ich nämlich `strg` `f` `1521` probiert -- ohne Erfolg. Kann man nicht dafür sorgen, dass `1521` in der Tabelle auftaucht?

**Comment by thvitt** [comment]
* Im Text taucht Gräf 1521 wegen `<milestone xml:id="graef_1531" next="#graef_1521"/>` nicht auf. Für die Beschriftung der Anker / Fortsetzungsmilestones hangelt sich das Transformationsskript rückwärts an der durch `next`/`target` gebildeten Kette entlang und findet so das erste Milestone-Element, dass zur Identifikation herangezogen wird.
* Um in der Tabelle aufzuscheinen, gibt es m.E. zwei Möglichkeiten:

   1. eine eigene Tabellenzeile für Gräf 1521 würde dazu führen, dass das Zeugnis eine eigene verlinkte Seite mit eigenen Metadaten (aber dem Label Gräf 1531 im Text …) bekommen würde.
   2. Ein Eintrag `1531; 1521` in der Spalte _Gräf_ würde funktionieren wie z.B. bei [Pniower 596](http://dev.faustedition.net/archive_testimonies#pniower_596). Man müsste vllt. mal die Sortierung (`numericplus`) anpassen, dass (wie bei der ID-Berechnung auch) nur der Teil vor dem `;` berücksichtigt wird; so werden alle `;`-Zeilen an den Anfang sortiert (neues Issue in faust-web)

**Comment by gerritbruening** [comment]
Das leuchtet mir sehr ein. Variante ii würde aus meiner Sicht völlig ausreichen. Strg f ist zumutbar, wenn jemand das Zeugnis wirklich finden will. Das erwähnte neue Issue, soll das angelegt werden?

**Comment by sandrakrause** [comment]
Ich habe den Eintrag in der Gräf-Spalte in "`1531; 1521`" geändert.

**Comment by thvitt** [comment]
Dann ist das offiziell erledigt, was?
