### ISSUE TITLE
change name of entry "Geiger 1890" in bibliography

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#108]
Die Bibliographien im alten GJb sollten nicht in toto unter dem Namen Geiger verzeichnet werden! Entsprechend wären auch Metadateneinträge mit "Geiger 1890" zu ändern

**Comment by dietmarpravida** [comment]
@thvitt kann ich bitte alle xml-Einträge mit faust://bibliography/geiger1890 bekommen?

**Comment by dietmarpravida** [comment]
siehe faustedition/xml/issues/116

**Comment by thvitt** [comment]
Gibt keine.

Gibt eine Datei `testimony/geiger1890.xml`, steht ein Absatz von S. 267/268 drin, aber kein Entstehungszeugnis-`<milestone>`. 

Gibt entsprechend auch keinen Eintrag in der Bibliographie: http://dev.faustedition.net/bibliography#geiger1890

**Comment by dietmarpravida** [comment]
ah, okay, der Eintrag verweist auf einen Eintrag der Bibliographie. Dann lassen wir die Angabe einfach so, wie sie ist. Nur wenn auf die Berichte der WA-Editoren innerhallb des bibliographischen Teils verwiesen würde, dann sollten diese auch als eigenständige Beiträge erscheinen.
