### ISSUE TITLE
Stapfer 1928 oder 1828?

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#110]
In der Bibliographie steht `faust://bibliography/stapfer1828`, die Datei mit dem Entstehungszeugnis heißt jedoch `stapfer1928.xml` – ist eins davon flacsh?

**Comment by dietmarpravida** [comment]
1828 ist das richtige

**Comment by thvitt** [comment]
dann einmal umbenennen bitte …

**Comment by dietmarpravida** [comment]
kann ich leider nicht machen, kein Zugang

**Comment by thvitt** [comment]
erl.
