### ISSUE TITLE
Bibliographie: Gräf fehlt

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#111]
… Gräf 1904 wird in den Infotexten erwähnt, hat aber keinen Bibliographieeintrag

**Comment by dietmarpravida** [comment]
Der Verweis sollte auf "den" Gräf gehen (also Gräf II 2 wie hier verzeichnet: https://faustedition.uni-wuerzburg.de/wiki/index.php/Bibliographische_Verweise#Gr.C3.A4f). 1904 ist hier nur eine Information zum Erscheinungsjahr.

**Comment by thvitt** [comment]
Alles was unter der Überschrift Gräf steht auf der Seite ist falsch formatiert. Korrekt wäre:

```
* faust://bibliography/…
** Kurzzitation
*** Langzitation
```

so wie's oben ist.

Korrigier das doch und schreib die korrekte URI hier hinein, damit ich nix verwechsel, dann ergänze ich den Verweis im Text entsprechend.

**Comment by dietmarpravida** [comment]
Morgen Thorsten, 

kannst du mir sagen, was genau die url für "Gräf III 2.1" und "Gräf III 2.2." ist? Punkt bei 2.1 und 2.2? Bindestrich 2-1 und 2-2? 

Grüße 

Dietmar 



Von: "Thorsten Vitt" <notifications@github.com> 
An: "faustedition/xml" <xml@noreply.github.com> 
CC: "dietmarpravida" <dpravida@goethehaus-frankfurt.de>, "Assign" <assign@noreply.github.com> 
Gesendet: Montag, 28. August 2017 08:09:33 
Betreff: Re: [faustedition/xml] Bibliographie: Gräf fehlt (#111) 



Alles was unter der Überschrift Gräf steht auf der Seite ist falsch formatiert. Korrekt wäre: 
* faust://bibliography/…
** Kurzzitation
*** Langzitation 


so wie's oben ist. 

Korrigier das doch und schreib die korrekte URI hier hinein, damit ich nix verwechsel, dann ergänze ich den Verweis im Text entsprechend.

**Comment by dietmarpravida** [comment]
die korrekte uri für die Info (vormals "Gräf 1904") ist faust://bibliography/graef1901-1914_II_2
