### ISSUE TITLE
required changes in bibliography and in bibliographical references/metadata

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#116]
muss geklärt werden

**Comment by thvitt** [comment]
Es gibt in diesen Fällen zwei Einträge mit derselben URI auf der Bibliographische-Verweise-Seite: Im Falle _Pniower 1891_ einen unter __L-R__ und einen weiter unten unter __P__

**Comment by thvitt** [comment]
Hier ist eine Liste der doppelten / fehlenden Literaturverzeichniseinträge lt. letztem Lauf des Skripts:

```
INFO : target/xproc/bibliography.xpl:33:13:WARNING: 0 bibliography entries for faust://bibliography/390376, ignoring all but the first
INFO : target/xproc/bibliography.xpl:33:13:WARNING: 0 bibliography entries for faust://bibliography/gjb_50, ignoring all but the first
INFO : target/xproc/bibliography.xpl:33:13:WARNING: 0 bibliography entries for faust://bibliography/graef1904, ignoring all but the first
INFO : target/xproc/bibliography.xpl:33:13:WARNING: 2 bibliography entries for faust://bibliography/duentzer1882, ignoring all but the first
INFO : target/xproc/bibliography.xpl:33:13:WARNING: 2 bibliography entries for faust://bibliography/loeper1881, ignoring all but the first
INFO : target/xproc/bibliography.xpl:33:13:WARNING: 2 bibliography entries for faust://bibliography/manning1896, ignoring all but the first
INFO : target/xproc/bibliography.xpl:33:13:WARNING: 2 bibliography entries for faust://bibliography/pniower1891, ignoring all but the first
INFO : target/xproc/bibliography.xpl:33:13:WARNING: 3 bibliography entries for faust://bibliography/loeper1879, ignoring all but the first
INFO : target/xproc/metadata-html.xpl:128:15:WARNING: 3 bibliography entries for faust://bibliography/loeper1879, ignoring all but the first
INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 0 bibliography entries for faust://bibliography/gjb_59, ignoring all but the first
INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 0 bibliography entries for faust://bibliography/graef1901-1914_II_2, ignoring all but the first
INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 0 bibliography entries for faust://bibliography/jahrbuch_der_auktionspreise1996, ignoring all but the first
INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 0 bibliography entries for faust://bibliography/stargardt1996, ignoring all but the first
INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 0 bibliography entries for faust://print/hagen/C1_4 , ignoring all but the first
INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 0 bibliography entries for faust://print/q_1_2, ignoring all but the first
INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 2 bibliography entries for faust://bibliography/duentzer1882, ignoring all but the first
INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 2 bibliography entries for faust://bibliography/loeper1881, ignoring all but the first
INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 2 bibliography entries for faust://bibliography/manning1896, ignoring all but the first
INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 3 bibliography entries for faust://bibliography/loeper1879, ignoring all but the first
INFO : target/xproc/testimony.xpl:81:13:WARNING: 0 bibliography entries for faust://bibliography/390376, ignoring all but the first
INFO : target/xproc/testimony.xpl:81:13:WARNING: 0 bibliography entries for faust://bibliography/gjb_50, ignoring all but the first
INFO : target/xproc/testimony.xpl:81:13:WARNING: 2 bibliography entries for faust://bibliography/pniower1891, ignoring all but the first
…
```

**Comment by dietmarpravida** [comment]
[ ] 390376: Sonderproblem
[ ] gjb_50 und gjb_59: muss vermutlich in Autor/Jahr-Angabe geändert werden > Eingriffe in xml-Dateien erforderlich
[ ] graef1901-1914_II_2: sollte gelöst sein
[ ] graef1904: muss an aktuele uri angepasst werden: graef1901-1914_II_2
[ ] jahrbuch_der_auktionspreise1996, stargardt1996: muss geklärt werden
[ ] print/hagen/C1_4, print/q_1_2: Metadaten der Drucke?
[ ] manning1896 und pniower1899: Bibliographie bereinigen
[ ] übrige:  Eingriffe in xml-Dateien erforderlich

**Comment by dietmarpravida** [comment]
Kann ich die Doppeleinträge in der Bibliographie einfach löschen? Es sollte ja egal sein, wo ein Eintrag auf der Seite steht, ob unter "Allgemeine Literatur" oder "Entstehungszeugnisse", oder?

**Comment by thvitt** [comment]
wenn sie gleich sind, ja. Mein Skript interessiert sich überhaupt nur für Zeilen, die der Form `* / ** / ***` entsprechen, die überschriften sind ihm wurst.

**Comment by thvitt** [comment]
die `print`-Dinger muss ich mal suchen, kann spontan nicht sagen ob das mein oder euer problem ist.

**Comment by dietmarpravida** [comment]
- "faust://bibliography/jahrbuch_der_auktionspreise1996" muss in xml geändert werden zu "faust://bibliography/jap_47"
- "faust://bibliography/stargardt1996" muss in xml geändert werden zu "faust://bibliography/stargardt_663"

**Comment by dietmarpravida** [comment]
@thvitt ermittle doch bitte bei Gelegeneheit, welche Seiten aus gjb_50 und gjb_59 zitiert werden

**Comment by thvitt** [comment]
```
xml/document/archival/bb_cologny/G-30_15.xml
52:            <reference type="essay" uri="faust://bibliography/gjb_59">S. 112</reference>
```

gjb_50 finde ich grad selbst nicht, merkwürdig

**Comment by thvitt** [comment]
Zu den Drucken:

```
10:07:38 INFO : Rendering metadata of H P4 (file:/mnt/data/jenkins/workspace/faust-gen/data/xml/document/paralipomena/gsa_391357.xml) to HTML ...
10:07:38 INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 0 bibliography entries for faust://print/q_1_2, ignoring all but the first

10:07:38 INFO : Rendering metadata of H P50 (file:/mnt/data/jenkins/workspace/faust-gen/data/xml/document/paralipomena/gsa_391375.xml) to HTML ...
10:07:38 INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 0 bibliography entries for faust://print/q_1_2, ignoring all but the first

10:07:39 INFO : Rendering metadata of H P20 (file:/mnt/data/jenkins/workspace/faust-gen/data/xml/document/paralipomena/gsa_390887.xml) to HTML ...
10:07:39 INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 0 bibliography entries for faust://print/q_1_2, ignoring all but the first

10:07:41 INFO : Rendering metadata of T 3 H.3 (file:/mnt/data/jenkins/workspace/faust-gen/data/xml/document/archival/gsa/GSA_25-W_13-5.xml) to HTML ...
10:07:41 INFO : target/xproc/metadata-html.xpl:54:36:WARNING: 0 bibliography entries for faust://print/hagen/C1_4 , ignoring all but the first

10:07:42 INFO : Rendering metadata of J.3-1 (file:/mnt/data/jenkins/workspace/faust-gen/data/xml/document/archival/gsa/GSA_30-447-1.xml) to HTML ...
10:07:42 INFO : target/xproc/metadata-html.xpl:54:36:WARNING: Unresolved URI reference in text: faust://print/kua_VI_1
10
```

Die Bildung der URIs scheint mir hier eher freihändig zu sein … [hier eine Liste der möglichen URIs für die eingebundenen Drucke](https://github.com/faustedition/xml/files/1256500/print-uris.txt)

**Comment by dietmarpravida** [comment]
wo stehen denn die bibliographischen Angaben für die Drucke? wenn in einer xml-Datei, dann müssen Frau Krause oder Gerrit das machen

**Comment by thvitt** [comment]
ja, in den xml/document/**/*.xml-Dateien, die im o.g. Kommentar jeweils in der ersten Zeile jedes Zweierblocks angegeben sind. Das Präfix file:/mnt/data/jenkins/workspace/faust-gen/data/ entsprechend ignorieren.

**Comment by thvitt** [comment]
gjb_50 ist in der Bibliographie selbst referenziert:

```
2232:        <f:reference>Gleichen-Rußwurm, Alexander von: Das Schema im 'Faust'. In: faust://bibliography/gjb_50, S. 209–223.</f:reference>
```

**Comment by dietmarpravida** [comment]
gjb_50 ist abgehakt

**Comment by dietmarpravida** [comment]
@thvitt Kannst du bitte die Liste der doppelten / fehlenden Literaturverzeichniseinträge (wie oben gegeben) aktualisieren?

**Comment by thvitt** [comment]
Hier die Bibliographiewarnungen [aus dem letzten Buildlog](http://dev.digital-humanities.de/ci/view/Faust/job/faust-gen-fast/lastBuild/consoleFull):

```
2 bibliography entries for faust://bibliography/loeper1879, ignoring all but the first
2 bibliography entries for faust://bibliography/loeper1881, ignoring all but the first
Citation faust://bibliography/390376 missing in testimony pniower_765
Citation faust://bibliography/wa_II_5 missing in testimony graef_1222
Citation faust://bibliography/wa_IV_3 missing in testimony graef_860
Citation not found: faust://bibliography/390376 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/testimony-split/pniower_765.xml)
Citation not found: faust://bibliography/390376 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/xproc/bibliography.xpl)
Citation not found: faust://bibliography/jahrbuch_der_auktionspreise1996 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/data/xml/document/faust/2.5/gsa_391503.xml)
Citation not found: faust://bibliography/schroeer1881 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/data/xml/document/archival/bl_london/Add_20723.xml)
Citation not found: faust://bibliography/schroeer1881 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/data/xml/document/archival/sb_berlin/SBB-IIIA_Ms_germ_qu_527.xml)
Citation not found: faust://bibliography/schroeer1881 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/data/xml/document/archival/sb_berlin/SBB-Ms_germ_qu_475.xml)
Citation not found: faust://bibliography/schroeer1881 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/xproc/bibliography.xpl)
Citation not found: faust://bibliography/stargardt1996 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/data/xml/document/faust/2.5/gsa_391503.xml)
Citation not found: faust://bibliography/wa_II_5 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/testimony-split/graef_1222.xml)
Citation not found: faust://bibliography/wa_II_5 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/xproc/bibliography.xpl)
Citation not found: faust://bibliography/wa_IV_3 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/testimony-split/graef_860.xml)
Citation not found: faust://bibliography/wa_IV_3 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/xproc/bibliography.xpl)
```

**Comment by dietmarpravida** [comment]
- [ ] 2 bibliography entries for faust://bibliography/loeper1879, ignoring all but the first
- [ ] 2 bibliography entries for faust://bibliography/loeper1881, ignoring all but the first
- [ ] Citation faust://bibliography/390376 missing in testimony pniower_765
- [ ] Citation faust://bibliography/wa_II_5 missing in testimony graef_1222
- [ ] Citation faust://bibliography/wa_IV_3 missing in testimony graef_860
- [ ] Citation not found: faust://bibliography/390376 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/testimony-split/pniower_765.xml)
- [ ] Citation not found: faust://bibliography/390376 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/xproc/bibliography.xpl)
- [ ] Citation not found: faust://bibliography/jahrbuch_der_auktionspreise1996 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/data/xml/document/faust/2.5/gsa_391503.xml)
- [ ] Citation not found: faust://bibliography/schroeer1881 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/data/xml/document/archival/bl_london/Add_20723.xml)
- [ ] Citation not found: faust://bibliography/schroeer1881 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/data/xml/document/archival/sb_berlin/SBB-IIIA_Ms_germ_qu_527.xml)
- [ ] Citation not found: faust://bibliography/schroeer1881 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/data/xml/document/archival/sb_berlin/SBB-Ms_germ_qu_475.xml)
- [ ] Citation not found: faust://bibliography/schroeer1881 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/xproc/bibliography.xpl)
- [ ] Citation not found: faust://bibliography/stargardt1996 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/data/xml/document/faust/2.5/gsa_391503.xml)
- [ ] Citation not found: faust://bibliography/wa_II_5 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/testimony-split/graef_1222.xml)
- [ ] Citation not found: faust://bibliography/wa_II_5 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/xproc/bibliography.xpl)
- [ ] Citation not found: faust://bibliography/wa_IV_3 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/testimony-split/graef_860.xml)
- [ ] Citation not found: faust://bibliography/wa_IV_3 (in file:/mnt/data/jenkins/workspace/faust-gen-fast/target/xproc/bibliography.xpl)

**Comment by dietmarpravida** [comment]
hier erledigt, der Rest bei anderen issues
