### ISSUE TITLE
inconistencies in meta/B(a)9 and in archive_prints

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#121]
"Sigle Hagen B.a 9"

wohingegen

"Sigle Hagen B" (etc.)

D.h. die Bandangabe wird anscheinend nur bei B.a gemacht. Dagegen wird bei den Siglen auf archive_prints überall die Bandzahl angegeben (also z.B. "A 8"), nur nicht bei B.a.

**Comment by gerritbruening** [comment]
Geändert
