### ISSUE TITLE
Aufbewahrungsort missing in meta/seckendorff1782

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#122]
Weiteres herangezogenes Exemplar

    Aufbewahrungsort [missing]
    Signatur
        4 Mus.pr. 37674-1/3

**Comment by dietmarpravida** [comment]
@gerritbruening Wo wird das aufbewahrt?

**Comment by gerritbruening** [comment]
Das ist komisch.
In der Datei steht klar und deutlich
```xml
            <furtherCopy>
                <repository>bsb_muenchen</repository>
                <idno type="bsb_muenchen">4 Mus.pr. 37674-1/3</idno>
```
Das erscheint auf S. http://dev.faustedition.net/document?sigil=J.1&page=1&view=structure aber nicht.

**Comment by gerritbruening** [comment]
@thvitt, ich finde gerade nicht, wo das festgelegt wird. Finde nur MUE, aber wo stehen die vollen Namen der Archive?

**Comment by thvitt** [comment]
im XML-Ordner in der Datei `archives.xml`

**Comment by gerritbruening** [comment]
Morgen sicherheitshalber nochmal schauen.

**Comment by thvitt** [comment]
Weiteres herangezogenes Exemplar

    Aufbewahrungsort
        Bayerische Staatsbibliothek
    Signatur
        4 Mus.pr. 37674-1/3
