### ISSUE TITLE
Gräf 1333 / QuZ II-814

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#123]
Das Entstehungszeugnis Gräf 1333, das lt. Tabelle auch die nachrangige Nr. QuZ II-814 trägt, enthält `<milestone>`-Elemente _nur_ für die nachrangige ID `quz_II-814` und nicht für `graef_1333`.

Die Konsequenz – für die man durchaus auch die Transformation verantwortlich machen kann, die dieses Szenario jenseits der Vorgaben verwirrt – ist, dass für das als _Gräf Nr. 1333_ bezeichnete Zeugnis die Datei <http://dev.faustedition.net/testimony/quz_II-814> geschrieben wird, der [Link in der Tabelle](http://dev.faustedition.net/archive_testimonies#graef_1333) indes verweist auf die nicht ex. Datei `graef_1333`.

**Comment by sandrakrause** [comment]
In graef_1333 geändert.
Als die Datei markiert wurde, war noch nicht aufgefallen, dass die Einträge identisch sind. (Vgl. #104)
