### ISSUE TITLE
Auszüge verschiedener Zeugnisse in einer Tabellenzeile

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#124]
Fällt besonders auf bei Gräf 1024. Dort stehen alle Auszüge aus WA III, 3 in der Tabellenspalte,
obwohl in diesem Zeugnis nur einmal "Faust" als rs-Tag markiert ist.
Dasselbe tritt bei Gräf 1087 auf (ebenfalls aus WA III, 3).
Die Anzeige der anderen Zeugnisse in WA III, 3 scheint normal zu sein.
Woran kann das liegen?

**Comment by thvitt** [comment]
Hier:

```xml
                    <date when="1801-02-23"/>23. <milestone unit="testimony" spanTo="graef_1024_end" xml:id="graef_1024"
                        /><rs>Faust</rs>.<anchor xml:id="graef_1024_end"/> Ritter von Jena. Hr. G. R. Voigt.
                    Graf Stadion und Hr. v. Haller.</p>
```

`spanTo='#graef_1024_end'`, ohne den `#` ists ein Link auf eine Datei 'graef_1024_end'.

Ich lass mal 'ne Warnung ausgeben für diese Fälle …

**Comment by sandrakrause** [comment]
Prima, danke! Ich habe das in dem Fall jetzt verbessert.
Kann man da auch eine Liste ausgeben von Fällen, bei denen das noch falsch ist?

**Comment by thvitt** [comment]
Büddeschön:

```
ERROR: graef_1024 spans to graef_1024_end, which doesn't exist (#?). 
ERROR: graef_1068 spans to graef_1068_end, which doesn't exist (#?). 
ERROR: graef_1087 spans to #graef_101087_end, which doesn't exist (#?). 
ERROR: graef_1127 spans to #graef_1127_end, which doesn't exist (#?). 
ERROR: graef_862 spans to #graef_860a_end, which doesn't exist (#?). 
ERROR: pniower_765 spans to , which doesn't exist (#?). 
```

Weitere Meldungen aus dem Bereich der Entstehungszeugnisse:

```
ERROR: 0 metadata records match bie3_3461 (in riemer1841_1)
ERROR: 0 metadata records match bie3_6013 (in schoch1832_1)
ERROR: 0 metadata records match bie3_6490 (in houben1925-1928_1)
ERROR: 0 metadata records match bie3_6689 (in kletke1873)
ERROR: 0 metadata records match graef_1521 (in wa_IV_43)
ERROR: 0 metadata records match quz_III-483 (in quz_3)
ERROR: 0 metadata records match quz_IV-1797 (in wa_IV_40)
WARNING: No testimony divs found in 390376_0002
WARNING: No testimony divs found in burkhardt1870
WARNING: No testimony divs found in geiger1890
WARNING: No testimony divs found in gm_duesseldorf_KK1838
WARNING: No testimony divs found in gm_duesseldorf_KK1838
WARNING: No testimony divs found in wa_IV_51
WARNING: Using inferior testimony id lfd-nr-neuneu_331 (in harding1920_2)
WARNING: Using inferior testimony id quz_II-1211 (in wa_IV_43)
WARNING: Citation faust://bibliography/390376 missing in testimony pniower_765
WARNING: Citation faust://bibliography/wa_I_40 missing in testimony graef_865c
WARNING: Citation faust://bibliography/wa_I_49_1 missing in testimony graef_1957
WARNING: Citation not found: faust://bibliography/390376 (in file:/var/www/faust-gen/target/testimony-split/pniower_765.xml)
WARNING: Citation not found: faust://bibliography/wa_I_40 (in file:/var/www/faust-gen/target/testimony-split/graef_865c.xml)
WARNING: Citation not found: faust://bibliography/wa_I_49_1 (in file:/var/www/faust-gen/target/testimony-split/graef_1957.xml)
```

**Comment by sandrakrause** [comment]
Vielen Dank!
Habe die Liste, soweit ich konnte, abgearbeitet.
Die übrigen Punkte sind hauptsächlich Dinge, die bereits in anderen Issues behandelt werden.

Was (für mich) noch als unklar übrig bleibt, ist folgendes:

Anscheinend gibt es Probleme mit den "metadata records", wenn für ein Zeugnis sowohl die übergeordnete ID (z.B. Gräf-Nr.) als auch die untergeordnete ID (z.B. Biedermann) benutzt werden.
Mehrere der hier angezeigten Fehlermeldungen entstanden bei solchen Fällen.
Z.B.: 

> ERROR: 0 metadata records match bie3_6013 (in schoch1832_1)

Es gibt es bei bie3_6013 und dem übergeordneten pniower_544 Überschneidungen. Da das bie3-Zeugnis aber noch weitere Abschnitte umfasst, die das pniower-Zeugnis nicht beinhaltet, wurden beide markiert.

Ich kann jetzt nicht beurteilen, was man da machen kann, bzw. ob man da was unternehmen muss oder ob man mit der Fehlermeldung leben kann und was/ob das Auswirkungen für den Nutzer oder uns hat, wenn da ein Fehler angezeigt wird.

**Comment by thvitt** [comment]
Ich sehe im Augenblick nur eine kleine Unschönheit, die bei den Endnutzern anschaut: Wenn man in der [Pniower-544-Seite](http://dev.faustedition.net/testimony/pniower_544#bie3_6013) tatsächlich auf _Biedermann-Herrwig Nr. 6013:_ klickt, landet man am Anfang der Entstehungszeugnistabelle statt am entsprechenden Eintrag. Aber gut, ggf. lässt sich das durch Vergabe von IDs an die Tabellenzellen mit den untergeordneten Nummern lösen.

Eine weitere Nebenwirkung ist, dass wegen des bie3_6013-Milestone auch hierfür [eine eigene Entstehungszeugnisdatei erzeugt wird](http://dev.faustedition.net/testimony/bie3_6013), die dann entsprechend keine Metadaten etc. trägt (daher kommt die o.g. Meldung). Diese Seite wird aber nirgends verlinkt, Benutzer sollten sie also nie zu Gesicht bekommen.

**Comment by sandrakrause** [comment]
Wenn sich das ändern ließe, wäre das vielleicht nicht verkehrt, auch wenn die Auswirkungen ja weniger dramatisch sind.

Wenn die Nutzer die Seiten ohne Metadaten nicht zu Gesicht bekommen, sollte das ja vertretbar sein, würde ich meinen.
Allerdings habe ich da keine Entscheidungsgewalt ;)

**Comment by thvitt** [comment]
Bitte [im Wiki](https://faustedition.uni-wuerzburg.de/wiki/index.php/Dokumente_zur_Entstehungsgeschichte#Vergabe_der_IDs) kurz die Fälle dokumentieren, in denen `<milestone unit="testimony">` mit "sekundären" IDs vorkommen können & dann dieses Issue hier schließen.

**Comment by sandrakrause** [comment]
Habe ich eingetragen.
Sollte eine ausführlichere/andersartige Dokumentation erforderlich sein, einfach Bescheid sagen.
