### ISSUE TITLE
prints, after 2269

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#131]
Liegt hier in der Zeile:
 "MEPHIſTOPHELES. (bohrt, einer hat indeſſen die Wachspfropfen gemacht und verſtopft.)" 
nicht ein Kodierungsfehler vor? Sonst erscheint die Bühennanweisung immer in eigener Zeile (wie auch in den Drucken), hier aber in der Zeile der Sprecherangabe.

![nach 2269](https://user-images.githubusercontent.com/26788529/31889088-d94126ce-b7fe-11e7-95aa-89676c924da0.JPG)

**Comment by gerritbruening** [comment]
> Mephistopheles 

ist nicht `speaker`, sondern Teil einer `stage` (und in `hi`, deswegen Kapitälchen).
