### ISSUE TITLE
artificial variants in before_2429_c

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#132]
Worin besteht hier der Unterschied zwischen A, D1 und H.1, B, C.1, C.3, D.2 S? 

![vor 2429](https://user-images.githubusercontent.com/26788529/31895769-576faa08-b812-11e7-8ef4-526b4636774c.JPG)

**Comment by thvitt** [comment]
```xml
   <stage n="before_2429_c"
          rend="centered small"
          f:sigil="A 8">welcher dieſe Zeit
                                    über vor einem Spiegel geſtanden, ſich ihm bald ge­<lb break="no"/>nähert, bald ſich von ihm entfernt hat.</stage>
   <stage n="before_2429_c"
          rend="centered small"
          f:sigil="1 H.1">welcher dieſe Zeit
                                    über vor einem Spiegel geſtanden, ſich ihm bald <lb/>genähert,
                                    bald ſich von ihm entfernt hat.</stage>
```

**Comment by gerritbruening** [comment]
Was ist also die Ursache, der `<lb/>` oder der soft hyphen im XML?

**Comment by thvitt** [comment]
der soft hyphen. Es läuft durch [f:normalize-space()](https://github.com/faustedition/faust-gen-html/blob/4fc04847657ace7c2f00132ae90fba8381c63c78/xslt/utils.xsl#L337), da entfällt das <lb>, aber der shy bleibt stehen. Was tun? Soft hyphens grundsätzlich rauswerfen beim space normalisieren?

**Comment by gerritbruening** [comment]
Ja, shy kann entfallen!
