### ISSUE TITLE
Pniower Nr. 27 - Text ersetzen?

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#14]
Digitalisiert liegt vor: Pniower 1891.
In Pniower 1891 fehlt ein Stück des relevanten Zitats.
Als Quelle könnte besser Karl Wagner herangezogen werden:

Karl Wagner (Hrsg.): Briefe aus dem Freundeskreise von Goethe, Herder, Höpfner und Merck. Eine selbständige Folge der beiden in den Jahren 1835 und 1838 erschienenen Merckischen Briefsammlungen. Leipzig: Ernst Fleischer 1847. S. 131-135.
Dieses Zeugnis enthält den vollständigen Brief.

Online verfügbar unter: https://books.google.de/books?id=vitOAAAAcAAJ&dq=Karl%20Wagner%20Goethe%20Herder&hl=de&pg=PP5#v=onepage&q&f=false

Als PDF: [Briefe_aus_dem_Freundeskreise_von_Goethe.pdf](https://github.com/faustedition/xml/files/780548/Briefe_aus_dem_Freundeskreise_von_Goethe.pdf)

**Comment by gerritbruening** [comment]
Diese und verwandte Issues werden in folgender Tabelle verwaltet:

https://docs.google.com/spreadsheets/d/11Z043ZghUsXGrOiWsEJsopcub-SdeYX92rPYkfcpfiE/edit?usp=sharing

**Comment by gerritbruening** [comment]
Relevante Seiten der PDF-DAtei in `P:\digitalisate\Entstehungszeugnisse\nachdigitalisierung\` ablegen.

**Comment by sandrakrause** [comment]
Entsprechende Seiten sind im angegebenen Ordner abgelegt und die Google-Tabelle ist ergänzt.

**Comment by gerritbruening** [comment]
Danke!
