### ISSUE TITLE
Auszeichnung mit <rs> vervollständigen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#15]
* xml/testimony/biedermann1889-1896/
* xml/testimony/wa_I/
* xml/testimony/wa_III/
* xml/testimony/wa_IV/

**Comment by gerritbruening** [comment]
Abfrage:
https://faustedition.uni-wuerzburg.de/new/xml-query/?folder=testimony&xpath=%2F%2Ftei%3Adiv[not(%2F%2Ftei%3Ars)]&mode=files

**Comment by thvitt** [comment]
Man sollte das auch [in der Tabelle](http://dev.faustedition.net/archive_testimonies) sehen wenn man nach Auszug sortiert, vor `rs` sollte `…` stehen, vor Incipit nicht.

[Gräf 1497](http://dev.faustedition.net/testimony/graef_1497) übrigens hat das `<rs>` _außerhalb_ des durch `<milestone>` abgedeckten bereichs, da taucht das `<rs>` natürlich nicht in der Tabelle auf (sonst hätten wir bei divs mit mehreren Testimonies zuviel).

**Comment by gerritbruening** [comment]
Danke für den Hinweis auf den komischen rs, kümmern wir uns drum.

**Comment by sandrakrause** [comment]
Bei der Gelegenheit: Mir ist aufgefallen, dass bei einem Zeugnis in der Tabelle [Gräf 1574](http://dev.faustedition.net/testimony/graef_1574) vor dem `rs` zweimal `...` steht.
Mir ist nicht klar, wie das zustande kommt. Habe ich da was falsch gemacht? Ich konnte bisher den Fehler nicht finden.

**Comment by thvitt** [comment]
Ellipsen werden für Text vor Milestone / nach Anker erzeugt, aber auch vor/nach `<rs/>`. Es gibt eine Logik, um … … zu vermeiden, aber vermutlich funktioniert die in diesem Fall nicht
