### ISSUE TITLE
Zeugnisse gjb_2 bis gjb_24 in Autor-Jahr-System ändern

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#16]
1. Abschnitt auf der Wiki-Seite überarbeiten: https://faustedition.uni-wuerzburg.de/wiki/index.php/Bibliographische_Verweise#GJb.
2. Dateien in `testimony/xml` umbenennen nach Autor-Jahr-System (identisch mit dem letzten Teil `autorjahr` in `faust://bibliography/autorjahr`).

**Comment by gerritbruening** [comment]
Teil von https://github.com/faustedition/xml/issues/19

**Comment by sandrakrause** [comment]
Den Abschnitt auf der Wiki-Seite habe ich überarbeitet.
Die einzelnen Einträge habe ich alphabetisch auf der Wiki-Seite einsortiert.
Sicherheitshalber habe ich den GJB-Abschnitt vorerst noch (durchgestrichen) dort gelassen.
Die xml-Dateien tragen nun auch den richtigen Namen.

**Comment by gerritbruening** [comment]
OK, sehr gut! Jetzt würde ich Sie noch bitten, [hier](https://faustedition.uni-wuerzburg.de/wiki/index.php/Bibliographische_Verweise#Goethe-Jahrbuch) die folgenden Nachweise zu vervollständigen:
* faust://bibliography/gjb_5
* faust://bibliography/gjb_10
* faust://bibliography/gjb_18
* faust://bibliography/gjb_21
* faust://bibliography/gjb_24
Denn diese URIs werden in den von Ihnen angelegten Einträgen ja verwendet.

**Comment by gerritbruening** [comment]
Die <s>abgearbeiteten Einträge</s> habe ich hierhin verschoben: https://faustedition.uni-wuerzburg.de/wiki/index.php/Diskussion:Bibliographische_Verweise#GJb.

**Comment by sandrakrause** [comment]
Danke für den Hinweis, die Nachweise sind nun vervollständigt.

**Comment by gerritbruening** [comment]
Danke!
