### ISSUE TITLE
Fehlermeldungen abarbeiten

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#17]
Siehe https://faustedition.uni-wuerzburg.de/wiki/index.php/Dokumente_zur_Entstehungsgeschichte#Fehlerliste

**Comment by sandrakrause** [comment]
@gerritbruening Die Liste ist nun abgearbeitet.
Bevor das issue geschlossen wird: könnte der Test evtl. noch einmal durchgeführt werden, falls sich seit der letzten Überprüfung noch weitere Fehler eingeschlichen haben? Dann können diese auch direkt noch abgearbeitet werden.

**Comment by gerritbruening** [comment]
Statt der Liste gibt es jetzt 
> keine/komische ID: »«.

in der Tabelle ersetzt.
