### ISSUE TITLE
Complete Bibliographische Verweise

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#19]
> müssen halt noch eine ganze Reihe Literaturverzeichniseinträge ergänzt werden (vgl. http://dev.faustedition.net/archive_testimonies )

Liste zum Abarbeiten: https://docs.google.com/spreadsheets/d/1aTQDjncQRvb3_JZSWT2y_ocrGvNckXG-1bT1yAaUOHQ/edit?usp=sharing

**Comment by sandrakrause** [comment]
Zwischenstand:
Die Liste habe ich abgearbeitet.
Ich bin die Tabelle noch einmal durchgegangen und dabei noch auf weitere fehlende Einträge gestoßen, die ich in der Liste ergänzt und weitgehend schon abgearbeitet habe.
Bei den KuA-Einträgen ist noch nicht ganz klar, wie diese aufgebaut werden sollen. DP sagte, man müsse noch einmal überlegen/diskutieren, wie diese zu behandeln sind.

**Comment by gerritbruening** [comment]
Auch KuA erledigt.
