### ISSUE TITLE
Komische Stellen in Faust I Lesetext

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#211]
1948

     <p><font name="Times" size="12">Nachher<p><fn-c><color fgc="000000">,</color></fn-c> <color fgc="000000">vor allen andern Sachen</color></p>

1950

        <p><font name="Times" size="12"><color fgc="000000">Da</color> #.seht<p><fn-c><color fgc="000000">,

1952

            <p><font name="Times" size="12">Für<p><fn-c><color fgc="000000">,

2080

                <p><font name="Times" size="12"><color fgc="000000">Ihr</color> wollt<p><fn-c><color fgc="000000">#[2019]

Es sieht aus, als wären Kommas und Apostroph hochgestellt. Steckt da was zu beachtendes dahinter?

**Comment by dietmarpravida** [comment]
Hm, das sind wohl alles versehentliche Hochstellungen in der Worddatei (hat mit nachfolgenden Fußnotenziffern oder ehemals dort befindlichen Fußnotenziffern zu tun); sachlich ohne Belang.

**Comment by gerritbruening** [comment]
Danke!
