### ISSUE TITLE
A8 before_3776_b head oder stage

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#238]

**Comment by dietmarpravida** [comment]
in hac causa mihi acqua haeret

**Comment by dietmarpravida** [comment]
Steht in den Drucken vor der Linie, also eher Head, typographisch in den Drucken aber weniger gesperrt als "Dom". Urfaust gibt ja wenig direkten Anhalt.

**Comment by dietmarpravida** [comment]
immer noch ratlos, aber da  AA ebenso wie wir jetzt verfährt, lassen wirs so

ist das damit erledigt, oder muss in den Dateien noch was geändert werden?

**Comment by gerritbruening** [comment]
Ja, wegen der Linie würde ich bei `head` bleiben. Wenn im Satz alles in Ordnung ist, schließen.
