### ISSUE TITLE
GJb 11, 266--268

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#24]
gjb_11_0266-0267-0268 

Kommentar JK:
> xml-Datei entspricht nicht dem Entstehungsdokument in der Excel-Tabelle/ unterschiedliches Datum, unterschiedliche bie3_

aus https://docs.google.com/spreadsheets/d/1xcWc71MqO5Dkdt2ksTHDfXVBLNqqg70ocFka-2UnXbM/edit#gid=174171133

DP gefragt

**Comment by dietmarpravida** [comment]
Zitat aus Brief von Zimmermann an Reich, 25.01.1776, GJb 11, S. 267 aus: Catalog des antiquarischen Lagers von Albert Cohn, No CXCIV (nach Zitat in GJb (es wurde die falsche Stelle des GJb mit Zitat nach Catalog CXCVI digitalisiert)
