### ISSUE TITLE
Nr. für GJb 2, 392--395

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#25]
gjb_2_0392-0393, gjb_2_0394-0395

Kommentar JK:

> keine entsprechende Identifikationsnummer vorhanden

**Comment by dietmarpravida** [comment]
Küttner an Bertuch, 11.05.1777, erhält die Gräf-Nr. 859A_e ("A" für Anmerkung, "e" für Stelle des Zeugnisses = fünftes Zeugnis in der Anmerkung)
