### ISSUE TITLE
Satzförmige BAs kennzeichnen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#253]
Liste der satzförmigen oder der nicht satzförmigen `stage` Elemente wird von @dietmarpravida erstellt.

@thvitt, wäre es dann möglich, die mit `@n`-Wert adressierten `stage`s im Rahmen der XSLT-Pipeline mit einem bestimmten Attribut auszustatten, z.B. `type="sentence"`?

Hintergrund ist, dass jetzt doch nur die `stage type="sentence"` einen Punkt am Ende erhalten sollen.

**Comment by thvitt** [comment]
ja, das kann man dann schon machen.

**Comment by gerritbruening** [comment]
Super, da bin ich erleichtert!

**Comment by gerritbruening** [comment]
@thvitt, wäre es möglich, dass du alle `stage/@n`-Werte in jeweils einer Zeile als txt ausgibst (oder erklärst mir, wie das geht), und @dietmarpravida löscht dann diejenigen raus, die einen oder keinen Punkt erhalten sollen?

**Comment by gerritbruening** [comment]
[Satzwertige BAs-2.docx](https://github.com/faustedition/xml/files/1905879/Satzwertige.BAs-2.docx)

| Zeilenpräfix | Bedeutung                                                                             | `@type`  | Punkt am Ende? |
|--------------|------------------------------------------------------------------|---------|----------------|
| $ | vollständiger Satz (auch, wenn er mit Kleinbuchstabe beginnt)            | sentence | ja             |
| $_G | kein vollständiger Satz, aber wegen größerem Anfangsbuchstaben Punkt erwarten lassend | capitalized| ? |
| $_L  | kein vollständiger Satz, aber wegen Länge Punkt erwarten lassend | long | ??             |
| $? | unvollständiger Satz, aber finites Verb                                               | finite-verb | nein           |

**Comment by dietmarpravida** [comment]
hm, könntest du mal eine Meinung zu 2 und 3 ventilieren, @gerritbruening ?

**Comment by thvitt** [comment]
nein, docx war nicht teil der abmachung

**Comment by gerritbruening** [comment]
* txt?
* Präfix ersetzen durch Präfix + tab?

**Comment by gerritbruening** [comment]
+ nach faust-gen-html pushen und dort pflegen?

**Comment by dietmarpravida** [comment]
Es kommt ohnehin eine neue Version, da ich gerade nochmal darübergehe. Reicht es, wenn ich es unter .txt abspeichere? Wenn Tabs und andere Schikanen erwünscht sind, bitte ich um Anweisungen.

**Comment by thvitt** [comment]
txt und keine zusätzlichen Zeilenumbrüche gegenüber der Ausgangsversion (ich schnappe mir das erste Wort jeder Zeile, schnipple das Präfix ab und ignorier den rest). Sonst wurscht.

**Comment by dietmarpravida** [comment]
[Satzwertige.BAs-3.txt](https://github.com/faustedition/xml/files/1907828/Satzwertige.BAs-3.txt)

**Comment by thvitt** [comment]
habe mir jetzt erlaubt, die entsprechende Datei nach XML zu konvertieren – (a) aus Gründen der Selbstbeschreibungsfähigkeit und (b) zum leichteren Verarbeiten – und ins Github zu packen. Die Attribute stehen jetzt dran.

**Comment by gerritbruening** [comment]
Danke!
Dies müsste jetzt sachlich noch von @dietmarpravida geprüft werden, denke ich.

**Comment by gerritbruening** [comment]
@thvitt, was eignet sich am besten für die Prüfung?
https://github.com/faustedition/faust-gen-html/blob/master/text/stage-sentences.xml?

**Comment by thvitt** [comment]
was soll denn da geprüft werden? 

[stage-sentences.xml](https://github.com/faustedition/faust-gen-html/blob/master/text/stage-sentences.xml) ist ja einfach die Datei von Dietmar, die mit ein wenig Suchen und Ersetzen nach XML gewandelt wurde, da bringt eine Prüfung jetzt nicht soviel.

Vielleicht einfach faust.xml im Oxygen öffnen und `//stage` durchgucken? Sind 722 Treffer. Oder `//stage[@type]` (270)?

**Comment by gerritbruening** [comment]
> Vielleicht einfach faust.xml im Oxygen öffnen und `//stage` durchgucken? Sind 722 Treffer. Oder `//stage[@type]` (270)?

@dietmarpravida, hol dir dochmal die aktuelle Oxygen-Version mit Testlizenz und probiere das.

> `//stage` durchgucken? Sind 722 Treffer. Oder `//stage[@type]` (270)

Wie, es haben nicht alle ein `@type`?

**Comment by gerritbruening** [comment]
<stage n="before_2073_b">Zeche
                                lustiger Gesellen.</stage>

hat kein `@type`, aber einen Punkt am Ende. Wie kommt das?

**Comment by thvitt** [comment]
also: Im Rahmen dieses Issues kennzeichne ich diejenigen stages, die von Dietmar in eine der in https://github.com/faustedition/xml/issues/253#issuecomment-381028207 beschriebenen Kategorien einsortiert worden sind, mit dem entsprechenden Type. Alle, die nicht einsortiert worden sind, bekommen auch kein Type.

Ich sehe gerade kein Issue, das nun von diesem type abhängig punkte setzt oder nicht. Das ist ja, wie man der Tabelle oben entnehmen kann, noch nichtmal vollständig spezifiziert geschweige denn implementiert.

Also @gerritbruening @dietmarpravida Spezifikation vervollständigen und passendes Issue entweder raussuchen und mir und dem Milestone zuweisen oder erzeugen, damit ich die Punkte- und Klammernsetz- und Entfernorgie noch an die types angleichen kann.

**Comment by gerritbruening** [comment]
OK, vielleicht war es unklug, das zu vermischen, siehe jetzt #349.

**Comment by dietmarpravida** [comment]
Komisch, ich bin mir vollkommen sicher, dass ich die Spezifikation schon vor langem vervollständigt habe

**Comment by thvitt** [comment]
Meines Erachtens ist jetzt sowohl die Typeintragung als auch das Punktsetzen durch (#349). Wenn du das noch durchsehen magst, mach das, sonst kannst du m.E. dieses Issue ebenso wie #349 schließen.
