### ISSUE TITLE
ID-Nr. für Zeugnis Harding 1920, 2, 108ff. vergeben

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#26]
Ritter an Örsted, 16. und 17. August 1805:

> Ich habe sie aber, wie Göthe seinen Faust, in einen Sack gebunden, den ich mich fürchte aufzumachen.

(http://dev.faustedition.net/testimony/harding1920_2)

XML-Datei vorhanden (`harding1920_2.xml`), aber kein entsprechender Eintrag in der Excel-Datei. Um was für ein Zeugnis handelt es sich?

DP gefragt.

**Comment by dietmarpravida** [comment]
Eintrag in excel-Datei ergänzt; das Zeugnis muss nach einer lfd. Nr. zitiert werden, da es sonst keine ID-Nr. gibt

**Comment by dietmarpravida** [comment]
Das Zeugnis muss noch eine ID-Nr erhaten (die letzte lfd. Nr.)

**Comment by sandrakrause** [comment]
Der Text ist relativ lang. Soll er komplett als Zeugnis markiert werden oder nur ein bestimmter Abschnitt?

Wie soll die ID in der xml-Datei dann aussehen? lfd_nr_331 oder Lfd_Nr_(neuneu)_331 oder ganz anders?

**Comment by thvitt** [comment]
Die ID jedenfalls in Kleinbuchstaben und mit `-` als einzigem Sonderzeichen im Teil vor der Nummer (`_` dient als trenner zwischen den Bestandteilen (nummerierungssystem_nummer_sonstiger-kram; und der erste Milestone wird z.Z. daran erkannt, dass er genau ein `_` enthält).

Also:
* entweder jetzt `lfd-nr-neuneu_331` (sieht aber ein wenig albern aus) 
* oder `lfd-nr_331`, dann müsst ihr aber jedesmal alles nachcodieren, wenn Ihr eine neue laufende Nummerierung einführt
* oder erst codieren, wenn Ihr nie wieder eine neue laufende Nummerierung einführt (d.i. kurz vor der Entdeckung eines neuen Zeugnisses 😜)

**Comment by sandrakrause** [comment]
Nachcodieren halte ich persönlich nicht für eine gute Lösung.
Mir würde alternativ nur einfallen, eine neue Spalte einzufügen. Wobei hier die Frage wäre, ob sich das lohnt, da es, glaube ich, nicht allzuviele Fälle ohne sonstige Identifikationsnummer gibt.
Oder könnte man eventuell auch z.B. die Spalte Lfd. Nr. (alt) in etwas "hübscheres" umbenennen und diese dann als ID nutzen (denn dort ändern sich die alten Zahlen ja nicht mehr)?

**Comment by dietmarpravida** [comment]
markiert werden soll der Abschnitt, wo Ritter Goethes "Walpurgissack" erwähnt.

**Comment by sandrakrause** [comment]
ist so markiert
