### ISSUE TITLE
8217f. eigene Replik

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#267]
Zu http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=194&view=print#l8217

@dietmarpravida, ich habe mit 8217 eine eigene Replik angefangen, da nicht mehr die Sirenen allein singen, sondern sie und die Nereiden und Tritonen ("Allgesang"). Ist das richtig so?

**Comment by dietmarpravida** [comment]
scheint mir keine separate Replik zu sein

**Comment by gerritbruening** [comment]
Ist zu einer Replik zusammengefasst, 8217f. als eigene Versgruppe.
