### ISSUE TITLE
Klischnig 1794, S. 210f

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#27]
In der Excel-Tabelle, `lfd Nr. allerneuestens` 81 werden Pniower-Nr. 64 und Biedermann-Herwig-Nr. 844 als Referenz angegeben.  Die dort angeführten Texte stimmen jedoch nicht mit dem Text in der xml-Datei des Zeugnisses überein (klischnig1794.xml).

**Comment by dietmarpravida** [comment]
Bei Pniower wird das zeugnis zumindest erwähnt (bleibt also); Biedermann-Herwig in Tabelle gestrichen
