### ISSUE TITLE
"Chor" und dgl. Teil der Sprecherbezeichnung?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#278]
oder BA in derselben Zeile?

In H (`before_11604_b` ff., Lemuren) sind diese Zusätze als Teil der Sprecherbezeichnung aufgefasst. Dafür spricht das Fehlen von Klammern.
Wie wird das im Faust I gehandhabt, und muss da einheitlich verfahren werden?

**Comment by dietmarpravida** [comment]
In H sind die Angaben nicht unterstrichen, die Lemuren aber schon; würde ich behandeln wie "Hexen im Chor" vor 3956

**Comment by gerritbruening** [comment]
Bleibt jeweils.
