### ISSUE TITLE
Typ 1c --> Typ 8?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#281]
> Verzeichnung typographischer Inkonsistenzen im Ausgangstext, die infolge der systematischen typographischen Regelung für die vorliegende Ausgabe aufgehoben wird (Eingriff erübrigt sich; auch für analoge Phänomene in Handschriften)

Dies scheint mir auf einige Stellen zuzutreffen, die jetzt unter 1c gelistet sind.
Sollten wir mal gemeinsam durchgehen.

**Comment by dietmarpravida** [comment]
glaube nicht, dass es da viele Inkonsistenzen gibt. Aber durchgehen dürfte sinnvoll sein.

**Comment by dietmarpravida** [comment]
habe die Typen geändert, nehme aber an, dass es jetzt einen Haufen neue Fehler geben wird, da ich zugeich die Beiersdorf-Punkte entfernt habe

**Comment by gerritbruening** [comment]
Die Fehler können wir uns dann ja ansehen.
