### ISSUE TITLE
Apparateintrag zu 3787–3788 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#287]
<s>In der online-Darstellung (http://dev.faustedition.net/print/faust.23#app.3787.only-app) scheinen Siglen zu fehlen (mindestens S und A).</s>
<s>Beim ersten Lesen war mir nicht sofort klar, dass es um das "die" geht. Wäre es nicht genauer und variantenfriedhöflicher, die Variante zu verkürzen und dann auch ein Lemma anzugeben?</s>

**Comment by dietmarpravida** [comment]
Da es kein Lemma gibt, wo sollen da die Siglen stehen? Ich wäre hier eher für negativen Apparat.

**Comment by gerritbruening** [comment]
Evtl. den Eintrag ganz weglassen.

**Comment by dietmarpravida** [comment]
ich bin noch unentschieden

**Comment by dietmarpravida** [comment]
Kommt in den Anhang, hier erledigt

**Comment by dietmarpravida** [comment]
Gibt es Konventionen für das Anhangkodieren?

**Comment by dietmarpravida** [comment]
@gerritbruening Die Beantwortung dieser Frage scheint mir dringend.

**Comment by gerritbruening** [comment]
Könnte man nicht sagen, alle Typ 8er kommen in den Anhang? Im übrigen sollten die Einträge so aussehen wie die anderen.

**Comment by gerritbruening** [comment]
Könnte man nicht sagen, alle Typ 8er kommen in den Anhang? Im übrigen sollten die Einträge so aussehen wie die anderen.

**Comment by dietmarpravida** [comment]
ist das Problem von 3787-3788 noch aktuell und wenn ja oder nein, was war die Lösung?

**Comment by gerritbruening** [comment]
Die Lösung war direkte XML-Kodierung.
Sieht für mich jetzt OK aus.
