### ISSUE TITLE
2348 Dich

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#288]
sollte doch in erster Linie zu 2a gehören, oder? H.2 braucht man hier ja eigentlich nicht.
Sonst wäre auch eine doppelte Typzuweisung möglich, wie ich sie manchmal beim Faust II habe.

**Comment by dietmarpravida** [comment]
Dann wäre ich für doppelte Zuweisung. Wie drückst du das aus? "[Typ 2a] oder [Typ 2c]", "[Typ 2a oder 2c]"?

**Comment by gerritbruening** [comment]
Aus der Pipeline direkt ins XML verlegt: https://github.com/faustedition/faust-gen-html/commit/1f8c2448b8fd5fd35e529e28735fbe08fe3e9204.
@dietmarpravida, bitte Ergebnis prüfen: http://dev.faustedition.net/print/faust.9#app.2348.dich.

**Comment by dietmarpravida** [comment]
scheint mir geklärt
