### ISSUE TITLE
2d*, 3*

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#289]
@dietmarpravida, unsere Typenliste hat an diesen Stellen noch keinen Asterisk. Ich habe bislang 2d und 3 ohne Asterisk angegeben. Ich kann das ändern, aber dann sollten wir das gleich auch in der Typenliste tun, oder?

**Comment by dietmarpravida** [comment]
Ich bin aus systematischen Gründen schon immer für mit Asterisk, also: ja.

**Comment by gerritbruening** [comment]
Gefixt durch https://github.com/faustedition/faust-gen-html/commit/c513b598ac646b8cf2b502023ed19fe9225f212b.
