### ISSUE TITLE
Lfd allerneust 549 / Pniower 325

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#29]
Wie kommt Zeugnis allerneueste 549 hier hinein?

Zahme X II, 430ff., WA I 3, 258:
> Was dem einen widerfährt ...

Ich finde in Pniower 325 keinen Hinweis darauf.

Text laut JK nicht in entsprechern KuA-XML-Datei (http://dev.faustedition.net/testimony/kua_2-3#pniower_325).

Aus https://docs.google.com/spreadsheets/d/1xcWc71MqO5Dkdt2ksTHDfXVBLNqqg70ocFka-2UnXbM/edit#gid=174171133.

**Comment by dietmarpravida** [comment]
lfd. Nr. (allerneuestens) 549 entfällt
