### ISSUE TITLE
S B B.2 gegen A? 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#292]
Anlass: app zu 1987
Muss es hier nicht
> _1987_ ists] _A_ ist's _S_ ist's _B B.a_

heißen?
Die Übereinstimmung von S und B-B.a dürfte ja keine genealogische sein.
Vgl. zu 2100.

Weitere Fälle:
* 2322

**Comment by dietmarpravida** [comment]
Danke!
