### ISSUE TITLE
quz_3_0057f. in attic

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#30]
SK in https://docs.google.com/spreadsheets/d/1xcWc71MqO5Dkdt2ksTHDfXVBLNqqg70ocFka-2UnXbM/edit#gid=174171133:

> entfällt, kein Zeugnis

ausschneiden und in xml/attic speichern.

**Comment by sandrakrause** [comment]
QuZ III-42 habe ich aus der Datei quz_3.xml entfernt und als quz_3_0057f.xml in xml/attic/testimony abgespeichert.

**Comment by gerritbruening** [comment]
Danke!
