### ISSUE TITLE
Bie3 3461 = Gräf 1762

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#31]
Anderer Druckort?

Ist das nicht dasselbe Zeugnis und auszuscheiden?

**Comment by dietmarpravida** [comment]
Es ist dasselbe Zeugnis, das sich aber einmal auf Plutarchlektüre im Jahr 1811, einmal auf die Erinnerung daran 1829 bezieht

**Comment by dietmarpravida** [comment]
lfd. Nr (allerneueste) 450 entfällt, in lfd. Nr. (allerneueste) 1241 wurde Bie3-Nr. ergänzt; der Eintrag hat jetzt zwei Ereignisdaten (1811 und 1829)
