### ISSUE TITLE
check app on 1899 -- 1900

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#318]
> 1899–1900 gern, … iſt,] S A Ba gern^ … iſt^ B 

suggeriert, dass alles übrige identisch ist.

Analoger Fall:
http://dev.faustedition.net/print/faust.30#app.before_5987_c.anst%C3%A4ndignichtauffallendnachsittegekleidetbeydeknieen
Angabe für H ist etwas verlängert, damit die beiden fehlenden Kommas verzeichnet sind.

**Comment by dietmarpravida** [comment]
1899|1900[gern, was auf der Erden|Und in dem Himmel ist,] {=}1899–1900 gern, … dem Himmel iſt,] A Ba gern, … den Himmel iſt, S    gern^ … dem Himmel iiſt^ B [Typ 4c]

**Comment by gerritbruening** [comment]
Fixed by https://github.com/faustedition/faust-gen-html/commit/2bc4b7197b31354ec60742f38866997509877b6b#diff-86da7489d035aef254aa3eb175b90d8fR100.
