### ISSUE TITLE
Bie3 6013 = Pniower 544?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#32]
und daher auszuscheiden?

**Comment by dietmarpravida** [comment]
lfd. Nr (allerneueste) 450 entfällt, in lfd. Nr. (allerneueste) 1241 wurde Bie3-Nr. ergänzt; der Eintrag hat jetzt zwei Ereignisdaten (1811 und 1829)

**Comment by dietmarpravida** [comment]
lfd. Nr (allerneueste) 934 entfällt (gehört zu lfd. Nr. (allerneueste) 921)
