### ISSUE TITLE
Förster-Zeugnisse (Kletke 1873)

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#33]
Sie das Tabellenblatt „Friedrich Förster“ in der Excel.
Alle dortigen Zeugnisse sollen nach Kletke 1873 wiedergegeben werden (Biedermann 1 wird ersetzt).
Vorhandener Textbestand: http://dev.faustedition.net/testimony/kletke1873.

* [x] DP: Passagen mit Leuchtstift im Ausdruck
* [x] SK: Lücken in XML identifizieren
* [x] SK: unbearbeitete Abbildungen dazu suchen
* [x] SK an Bildstelle delegieren: neue Abbildungen anfertigen
* [x] SK: in einem Fall nach Biedermann 2, Bd. 4, S. 381-383, diese Seiten digitalisieren (an Bildstelle delegieren)
* [x] entsprechende Seiten neu digitalisieren
* [x] DP: Zeilen im Blatt „Gesamt“ korrigieren

**Comment by gerritbruening** [comment]
S. 211--215 (1. Absatz gehört zu Gräf 1226) wird vollständig im Text belassen.

**Comment by dietmarpravida** [comment]
in excel-Datei korrigiert
