### ISSUE TITLE
1 H.5 GSA-Signatur

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#331]
Als (neue) GSA-Signatur von [1 H.5](http://dev.faustedition.net/document?sigil=1_H.5&page=1&view=structure) ist GSA 25/W 3081 verzeichnet, was aber ein anderes Dokument [(alte Signatur: 25/XXXVIII,2,1)](http://ora-web.swkk.de/archiv_online/gsa.entry?source=gsa.vollanzeige&p_id=5850) ist.

**Comment by gerritbruening** [comment]
Hm, schaue ich bei Gelegenheit.

**Comment by dietmarpravida** [comment]
die korrekte aktuelle (so lange es hält...) Signatur für 1 H.5 lautet: GSA 25/W 2890

**Comment by dietmarpravida** [comment]
cf #463
