### ISSUE TITLE
Zeugnisse aus WA IV 41

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#34]
in Zeno-xml nicht vorhanden, aber in xml/testimony-sources/zeno

* daraus kopieren
* markup korrigieren
* milestones setzen

**Comment by sandrakrause** [comment]
Die Datei wa_IV_41.xml ist nun vollständig und markiert mit korrigiertem Markup in xml/testimonies vorhanden.

**Comment by gerritbruening** [comment]
Prima, danke!
