### ISSUE TITLE
App on before_2465_a

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#346]
http://dev.faustedition.net/print/faust.9#app.before_2465_a.diehexe

Zeichenformat überlegen.

**Comment by dietmarpravida** [comment]
Ich würde es im edierten Text als Auftritt markieren (welches Format wäre das?), d.h. als Eingriff. Und in den Lesarten als emph? Oder ist das anders festgelegt?

**Comment by gerritbruening** [comment]
Der Auftritt würde so hineinkommen:
https://github.com/faustedition/faust-gen-html/commit/6b81fd7ec392432d98fa7d38de31b2f445cfe013#diff-62d902c026cea28dac4c69d62caf0daaR26
richtig, @thvitt?
Der andere Eintrag kann so bleiben, wie er ist, nur dass das `*` wegfallen müsste, oder?

**Comment by thvitt** [comment]
vor n="before_2465_a" soll ein `<move>` eingefügt werden?
```xml
    <app>   
        <f:ins n="before_2465_a" place="before"><move type="entrance"/></f:ins>
        <!-- TODO ref, lem, rdg -->
    </app>
```
`f:replace` hat niemals nie Spezialbedeutung, diese [^]-Sonderfälle sind alle in `f:ins/@place` gelandet.

**Comment by gerritbruening** [comment]
Ah, da hatte ich den txt-Input mit dem XML verwechselt. Sorry!
>         

Für die eigentlichen Eintragsinformationen (mit Lemma etc.) wird in diesem Fall woanders gesorgt:
https://github.com/faustedition/faust-gen-html/blob/master/text/app1norm.txt#L175
Ich weiß nicht, wie das anders gehen soll.

**Comment by thvitt** [comment]
Es können ja mehrere f:ins in einem app stehen, passiert ja sonst auch öfters. Warum nicht das hier mit bei der Hexe mit unterbringen? Wegen dem Textformat?

**Comment by gerritbruening** [comment]
(das mit den mehreren f:ins war mir entfallen)

**Comment by gerritbruening** [comment]
@thvitt, es tut mir leid, ich muss dich noch einmal bemühen.
So wie ich das gemacht habe, geht das nicht.
Das zweite `f:ins` wird moniert, und vor allem wird an beiden Stellen `move` eingefügt, "Die Hexe" fehlt dann im Text.

**Comment by thvitt** [comment]
Es gibt unterschiedliche Arten von Operationen, die im Apparat codiert werden können:

* Auf `<f:replace>` muss unmittelbar ein `<f:ins>` _ohne_ place-Attribut folgen, dieses Elementpaar steht für eine Ersetzung/Markierung des Teilstrings, der im `<f:replace>`-Element steht, durch den Inhalt des unmittelbar darauffolgenden `<f:ins>`. 
* `<f:ins place="…"/>` steht für alle anderen Operationen, bei denen abhängig vom Wert von place irgendwo was eingefügt wird, z.B. `<f:ins place="before" n="before_2465_a"><move type="entrance"/></f:ins>` fügt das `<move>` vor Element `n="before_2465_a"` ein.

Dir ist das `<f:ins place="before">` zwischen das `<f:replace>` und das dazu gehörende `<f:ins>` gerutscht, deshalb gabs Mecker vom Schema und falsches Verhalten vom Einfügeskript. Jetzt sollte m.E. alles ok sein?

**Comment by gerritbruening** [comment]
Alles klar, danke!
@dietmarpravida, jetzt lese ich
> (I c*)
d.h., es werde nicht eingegriffen. Es wird doch aber eingegriffen, oder?

**Comment by dietmarpravida** [comment]
ups, danke, müsste mit nächster Sendung erledigt sein

**Comment by dietmarpravida** [comment]
Siehe #381, abgesehen davon hier erledigt
