### ISSUE TITLE
Bestimmte BAs mit einem Punkt am Ende versehen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#349]
Betrifft nur den Lesetext.
Vorlauf: #253

**Comment by gerritbruening** [comment]
Regeln für die Punktevergabe:

| Zeilenpräfix | Bedeutung                                                                             | `@type`  | Punkt am Ende? |
|--------------|------------------------------------------------------------------|---------|----------------|
| $ | vollständiger Satz (auch, wenn er mit Kleinbuchstabe beginnt)            | sentence | ja             |
| $_G | kein vollständiger Satz, aber wegen großem Anfangsbuchstaben Punkt erwarten lassend | capitalized| ? |
| $_L  | kein vollständiger Satz, aber wegen Länge Punkt erwarten lassend | long | ??             |
| $? | unvollständiger Satz, aber finites Verb                                               | finite-verb | nein           |

(https://github.com/faustedition/xml/issues/253#issuecomment-381028207)

**Comment by gerritbruening** [comment]
Meine Meinung:
* `capitalized` würde ich eher ohne Punkt lassen. Ich verstehe das Bedürfnis nach Symmetrie, aber ich würde mir von der Großschreibung (in H recht inkonsequent) nicht den Punkt diktieren lassen.
* `long`: verstehe ich die Zuteilung manchmal nicht. Kann die Kombination von Sprecher und BA nicht eine `sentence`-`stage` rechtfertigen?

**Comment by dietmarpravida** [comment]
Ich neige ja inzwischen eher zu sowenig Punkten wie möglich, sonst schafft man sich nur allerhand Zweifelsfälle.

>  Kann die Kombination von Sprecher und BA nicht eine sentence-stage rechtfertigen?

So was wie ALLE _singen_ meinst du? Ist mir gestern auch aufgestoßen, aber noch obigem Vorschlag, vielleicht lieber kein Punkt, sieht sonst aufs ganze gesehen uneinheitlich aus.

**Comment by dietmarpravida** [comment]
In meiner Datei steht auch 

`before_3978[Halbes]{halbes} vor 3978 HEXENMEIſTER halbes Chor. none] H14  HEXENMEIſTER. Halbes Chor.  A B H1 C1 C3 	HEXENMEIſTER. (Halbes Chor.) Ba [Typ 8]`

Der Punkt ist hier ein Fehler, oder?

**Comment by gerritbruening** [comment]
> Der Punkt im Lemma ist hier ein Fehler, oder?

Ja, scheint mir so.

**Comment by gerritbruening** [comment]
> So was wie ALLE _singen_ (before_2293_c) meinst du?

Ja. Ich will jetzt aber keine Unruhe verbreiten.

**Comment by thvitt** [comment]
vgl. https://github.com/faustedition/faust-gen-html/issues/216 (überholt)

**Comment by dietmarpravida** [comment]
Ebenso (aber mit Doppelpunkt) `$_Lbefore_9446	Zu den Heerführern, die sich von den Colonnen absondern und herantreten:`

**Comment by dietmarpravida** [comment]
Ein besonderer Fall ist `$before_10849_a	Kaiser, mit Vier Fürsten treten auf Die Trabanten entfernen sich.`

Schöne hat hier nach "auf" einen Punkt ergänzt. Machen wir nicht. Aber man sieht das Problem.  "Die Trabanten entfernen sich." steht aber doch in eigener Zeile, oder?

**Comment by thvitt** [comment]
Ich hatte die Liste als abgeschlossen angesehen? Sie lebt jetzt in XML-Form [hier](https://github.com/faustedition/faust-gen-html/blob/master/text/stage-sentences.xml)

**Comment by dietmarpravida** [comment]
Ich sehe das Ganze gerade nochmal durch, auch wegen Gerrits Fragen. Wäre es möglich, die Liste einfach neu zu generieren? Es einfach im XML einzutragen, wäre recht fehleranfällig.

**Comment by dietmarpravida** [comment]
| [Zeilenpräfix] | [Bedeutung]                                                                             | `@type`  | Punkt am Ende? |
|--------------|------------------------------------------------------------------|---------|----------------|
| $ | vollständiger Satz (auch, wenn er mit Kleinbuchstabe beginnt)            | sentence | ja             |
| $_G | kein vollständiger Satz, aber wegen großem Anfangsbuchstaben Punkt erwarten lassend | capitalized| nein |
| $_L  | kein vollständiger Satz, aber wegen Länge Punkt erwarten lassend | long | nein             |
| $? | unvollständiger Satz, aber finites Verb                                               | finite-verb | nein           |

**Comment by dietmarpravida** [comment]
[Satzwertige.BAs-4.txt](https://github.com/faustedition/xml/files/2009938/Satzwertige.BAs-4.txt)

**Comment by dietmarpravida** [comment]
Bitte erst obige Fragen zu 2884a und 9446 klären, bevor weiteres geschieht.

**Comment by thvitt** [comment]
AAAAAAAAAA jetzt wird doch an der Textdatei weitergearbeitet, damit waren wir doch durch!

**Comment by gerritbruening** [comment]
Die Frage zu `before_2284_a` müsste @thvitt beantworten, über `before_9446` sinniere ich Ende Mai.

**Comment by thvitt** [comment]
So, das ist jetzt auch drin. @dietmarpravida, wenn du das sachlich kontrollieren willst, dann entweder im Endprodukt (Webedition) oder vielleicht in der without-app.xml, denn da sind die Apparat-Notes noch nicht drin, aber die Punktersetzungen vorgenommen.

Ich sehe gerade, dass ein zwei Stellen meine Ersetzung nicht geklappt hat da die txt-Datei mehrere Versnummern enthielt:

```
before_7495_a before_7495_b	Am obern Peneios wie zuvor.
$_Lbefore_8275_a before_8275_b	Telchinen von Rhodus auf Hippokampen und Meerdrachen, Neptunens Dreyzack handhabend.
```

bitte [direkt im XML nachkodieren](https://github.com/faustedition/faust-gen-html/blob/master/text/stage-sentences.xml), ich verstehe nicht, wie diese Einträge gemeint sind.

**Comment by gerritbruening** [comment]
> Die Textvalidierung vermeldet, dass dementsprechend drei Apparateinträge überarbeitet werden müssen, alle in Faust II

Danke für den Hinweis, habe ich gemacht (https://github.com/faustedition/faust-gen-html/commit/6f7b5019876f5aee96445e466f8c4640045a3785).

**Comment by gerritbruening** [comment]
> ich verstehe nicht, wie diese Einträge gemeint sind

die zweimalige `@n`-Wert-Angabe hat hierin ihren Grund:
`<stage n="before_7495_a before_7495_b" xml:id="before_7495_a" rend="inline">Am obern Peneios wie zuvor</stage>`
`<stage n="before_8275_a before_8275_b"><hi>Telchinen von ...`

**Comment by thvitt** [comment]
achso, diesen Fall hatte ich nicht bedacht. ich hab's jetzt manuell im stage-types.xml nachgetragen, siehe den o.g. commit. Beim Eintragen der type-Attribute erfolgt der Vergleich der n-Attribute buchstäblich, sollte also klappen.

**Comment by gerritbruening** [comment]
Danke!

**Comment by dietmarpravida** [comment]
@gerritbruening wenn du das für abgeschlossen hältst, bitte zumachen
