### ISSUE TITLE
Nummern im Text (Greife, Choretiden)

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#351]
https://github.com/faustedition/faust-gen-html/issues/460#issuecomment-389219766

**Comment by markusciupke** [comment]
Hier kommen mal für die beiden Stellen, die es betrifft PDF-Dateien zum Vergleich. Wobei es natürlich mal wieder komplizierter ist als erwartet. Und zwar insofern als in H hinter »1.« ein doppelt unterstrichenes kleines r steht. Das »1.r« ist ansonsten nicht unterstrichen, wie es der Sprecher »Greif« ist.
Bei der »2« wiederum (bei der der Punkt fehlt) ist das r ebenfalls doppelt unterstrichen und hochgestellt. Und hier ist die Unterstreichung von »Greif länger geraten, so dass auch das hochgestellte »r« von der Sprecherunterstreichung (versehentlich?) miterfasst ist.
Daraus ergeben sich zwei Fragen:
1. Wie reagieren wir darauf im Konstituierten Text. 
2. Wie reagieren wir darauf in der Transkription? 
In dieser sind die r’s weder hochgestellt noch doppelt unterstrichen. Dafür ist hier das »r« hinter 1. von der Sprecherunterstreichung miterfasst, dafür aber das »r« hinter der 2 nicht. Ich werde Dieter eine entsprechende Korrektur senden und dich Cc setzten.
[Medievalziffer 311.pdf](https://github.com/faustedition/xml/files/2009219/Medievalziffer.311.pdf)
[Medievalziffer 368.pdf](https://github.com/faustedition/xml/files/2009220/Medievalziffer.368.pdf)
[Medievalziffer mit Hochstellung 311.pdf](https://github.com/faustedition/xml/files/2009221/Medievalziffer.mit.Hochstellung.311.pdf)
[Versalziffer 311.pdf](https://github.com/faustedition/xml/files/2009222/Versalziffer.311.pdf)
[Versalziffer 368.pdf](https://github.com/faustedition/xml/files/2009223/Versalziffer.368.pdf)
[Versalziffer mit Hochstellung 311.pdf](https://github.com/faustedition/xml/files/2009224/Versalziffer.mit.Hochstellung.311.pdf)

**Comment by markusciupke** [comment]
Entschuldige. Die doppelte Unterstreichung bei den beiden PDF-Dateien mit Hochstellung war vermutlich unsinnig. Die soll ja, wenn ich das richtig verstehe, nur die Hochstellung verdeutlichen. So würde es also reichen, die Hochstellung vorzunehmen und die doppelte Unterstreichung kann weggelassen werden. Zwei entsprechende PDF-Dateien mit Medieval- bzw. Versalziffern siehst du hier:
[Medievalziffer ohne Unterstreichung.pdf](https://github.com/faustedition/xml/files/2009592/Medievalziffer.ohne.Unterstreichung.pdf)
[Versalziffer ohne Unterstreichung.pdf](https://github.com/faustedition/xml/files/2009593/Versalziffer.ohne.Unterstreichung.pdf)

**Comment by dietmarpravida** [comment]
ist jetzt immer noch mediäval, oder?

**Comment by markusciupke** [comment]
Nein, bei den Greifen sind Zahlwörter und bei den Choretiden sind Versalziffern.

Zu den Greifen: Wieso darf man aus den Ziffern einfach Wörter machen? Und wieso wird das nicht im Apparat vermerkt?

**Comment by gerritbruening** [comment]
> Wieso darf man aus den Ziffern einfach Wörter machen? Und wieso wird das nicht im Apparat vermerkt?

#484 

> ist jetzt immer noch mediäval, oder?
> > Nein, bei den Greifen sind Zahlwörter und bei den Choretiden sind Versalziffern.

![grafik](https://user-images.githubusercontent.com/10358005/44079843-82c3e752-9faa-11e8-8855-01bb058ef8f3.png)

@dietmarpravida|s Eindruck rührt vielleicht daher, dass die Ziffern weniger hoch sind als die vorhergehenden Versalien. Lässt sich das evtl. ausgleichen?

**Comment by markusciupke** [comment]
so besser?

[Faust II 359.pdf](https://github.com/faustedition/xml/files/2286325/Faust.II.359.pdf)

**Comment by dietmarpravida** [comment]
ich meinte gar nicht, dass es vorher schlecht ausgesehen hätte (war tatsächlich nur eine Sachfrage); bin mir auch bei der ästhetischen Einschätzung gar nicht sicher

**Comment by markusciupke** [comment]
Gefällt mir jetzt besser so. Ist 0,5 pt größer.

**Comment by gerritbruening** [comment]
Finde ich OK so, danke!
