### ISSUE TITLE
app after_4611

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#356]
muss after_4611f heißen:

```xml
                            <stage type="finite-verb" n="after_4611f">verschwindet mit
                                Faust</stage>
```

**Comment by dietmarpravida** [comment]
okay, die Feherquelle war immerhin das hier:

![after_4611](https://user-images.githubusercontent.com/26788529/40179632-1e15bfe8-59e5-11e8-866c-58a125b369fc.JPG)
