### ISSUE TITLE
Gräf Sternchen * entfernen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#36]

**Comment by sandrakrause** [comment]
Sternchen* bei Gräf 1148 in Absprache mit DP entfernt:
Gräf 1148* entfällt, da der Brief, auf den verwiesen wird, kein Zeugnis ist (QuZ I-1100).
Das eigentliche Zeugnis ist die Beilage zu diesem Brief (QuZ I-1100a), welche mit Gräf 1148** (Lfd. Nr. 470) vertreten ist und als Gräf 1148 erhalten bleibt.  Der Brief wurde als Bemerkung bei 1148 aufgenommen.

**Comment by sandrakrause** [comment]
Sternchen* bei Gräf-Nr. 1067 in Absprache mit DP entfernt:
1067* entfällt (der Brief ist bereits bei Gräf-Nr. 1068 enthalten), 1067** wird zu 1067.

**Comment by dietmarpravida** [comment]
Zeilen in excel-Datei gelöscht
