### ISSUE TITLE
app zu 3184:

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#361]
http://dev.faustedition.net/print/faust.15#app.3184.only-app –

> 3184[]{} <i>3184</i>] <i>In 1_H.5 S A B B.a handelt es sich um zwei Verse, sie wurden erst von faust://bibliography/duentzer1882a#Düntzer und dann von faust://bibliography/wa_I_14#faust://bibliography/wa_I_14 zu einem antilabischen Vers zusammengefasst. [type=3*]</i>

die zweite Zitation sollte nach dem `#` wohl Erich_Schmidt enthalten statt einer wiederholung der URI?

**Comment by dietmarpravida** [comment]
bei mir steht:

`3184[]{} 3184] In H5 S A B Ba handelt es sich um zwei Verse, sie wurden erst von faust://bibliography/duentzer1882a#Düntzer und dann von faust://bibliography/wa_I_14#Erich Schmidt zu einem antilabischen Vers zusammengefasst. [Typ 3*]`

**Comment by dietmarpravida** [comment]
Der Fehler findet sich erst in app1norm.txt

**Comment by gerritbruening** [comment]
Fixed in https://github.com/faustedition/faust-gen-html/commit/39f257db9fb634d7ad4e45adf6f9cb5a83a19c74.

**Comment by thvitt** [comment]
Es muss bitte `#Erich_Schmidt` heißen, da an Leerzeichen tokenisiert wird; sonst ist der Link nur der Erich.

**Comment by dietmarpravida** [comment]
Müsste beim nächsten Pushing erledigt sein
