### ISSUE TITLE
check bibliography entries and metadata for 1 H.12

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#367]
![1h12](https://user-images.githubusercontent.com/26788529/40741290-7de74c28-644b-11e8-9c58-ece3236b94f3.JPG)

Fehlt eigentlich die Valentin-Szene bei Bohnenkamp? Cras credam.

**Comment by gerritbruening** [comment]
S. 98f. gibt es zwei kurze Erwähnungen:
> die Ende 1800/Anfang 1801 entstandene Handschrift zur ‘Walpurgisnacht’

> das überlieferte eigenhändige
Manuskript großer Teile der ‘Walpurgisnacht’ sowie die ebenfalls erhaltene Niederschrift
der Valentinsszene

**Comment by dietmarpravida** [comment]
schroeer1881 > schroeer1881_1 geändert
loeper1879 noch nicht geändert

**Comment by dietmarpravida** [comment]
cf #622
