### ISSUE TITLE
Merkwürdig aufgeteilte Überschriften

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#37]
Siehe https://faustedition.uni-wuerzburg.de/wiki/index.php/Diskussion:Dokumente_zur_Entstehungsgeschichte#umgebrochene_.C3.9Cberschriften

**Comment by gerritbruening** [comment]
Wahrscheinlich nur Biedermann betroffen.

**Comment by sandrakrause** [comment]
Die Überschriften sind jetzt alle korrigiert.
