### ISSUE TITLE
text view missing in 2 II H.69

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#376]
http://dev.faustedition.net/document?sigil=2_II_H.69&page=1&view=facsimile_text

![2 ii h 69_keine textansicht](https://user-images.githubusercontent.com/26788529/40993710-96ad8f0c-68fa-11e8-99c8-047374c06192.JPG)

**Comment by thvitt** [comment]
Duplicate of https://github.com/faustedition/faust-gen-html/issues/390
