### ISSUE TITLE
Fehler in Gräf 1721

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#38]
Siehe https://faustedition.uni-wuerzburg.de/wiki/index.php/Diskussion:Dokumente_zur_Entstehungsgeschichte#Fehler_in_Gr.C3.A4f_1721

@sandrakrause , könnten Sie sich das mal ansehen?

**Comment by sandrakrause** [comment]
Ich habe das überflüssige Leerzeichen in der xml-Datei entfernt.
