### ISSUE TITLE
3x nach 2464

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#381]
@dietmarpravida, ich erinnere mich, dass du mehrmaliges "vor 2465" durch Änderung in "nach 2464" erreichen wolltest.
Aber jetzt finde ich "nach 2464" dreimal, und "vor 2465" gar nicht mehr. Ist das so gedacht?

**Comment by dietmarpravida** [comment]
"vor 2465" müsste hier stehen:

`before_2465_a[Die Hexe]{=} vor 2465] Die Hexe wird in A B C1 C3 nicht als Auftritt markiert (S unterscheidet typographisch nicht zwischen Auftritten und Sprecherangaben). [Typ 1c]
`
Aber das ist vermutlich wieder in dieser Sonderdatei?

**Comment by dietmarpravida** [comment]
"vor 2465" müsste hier stehen: 

before_2465_a[Die Hexe]{=} vor 2465 ] Die Hexe wird in A B C 1 C 3 nicht als Auftritt markiert (S unterscheidet typographisch nicht zwischen Auftritten und Sprecherangaben). [Typ 1c] 

Aber das ist vermutlich wieder in dieser Sonderdatei? 



Von: "Gerrit Brüning" <notifications@github.com> 
An: "faustedition/xml" <xml@noreply.github.com> 
CC: "dietmarpravida" <dpravida@goethehaus-frankfurt.de>, "Mention" <mention@noreply.github.com> 
Gesendet: Mittwoch, 6. Juni 2018 11:16:11 
Betreff: [faustedition/xml] 3x nach 2464 (#381) 



@dietmarpravida , ich erinnere mich, dass du mehrmaliges "vor 2465" durch Änderung in "nach 2464" erreichen wolltest. 
Aber jetzt finde ich "nach 2464" dreimal, und "vor 2465" gar nicht mehr. Ist das so gedacht?

**Comment by gerritbruening** [comment]
Ja, und just dieser Eintrag wird nicht ins IDML eingefügt, deswegen: https://github.com/faustedition/faust-gen-html/issues/511.
