### ISSUE TITLE
line-final dot before_3776

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#407]
Der Punkt nach dem ersten Teil der ersten Auftrittsangabe in Dom
![dom](https://user-images.githubusercontent.com/26788529/41612646-d1affda2-73f3-11e8-8152-b105333491c9.JPG)
entspricht wohl dem bei der ersten Auftrittsangabe in der Walpurgisnacht, 
![walpurgis_auftritt](https://user-images.githubusercontent.com/26788529/41612658-d9a24786-73f3-11e8-9bb6-933d6e946ece.JPG)
, oder? (@gerritbruening )
Sieht wegen des Zeilenwechsels aber beinahe falsch aus, ist aber wohl nicht zu ändern, da der Umbruch vor "Böser Geist" wohl so okay ist?

**Comment by gerritbruening** [comment]
> ist aber wohl nicht zu ändern

Ja, scheint mir auch so. Der `Volke.` ist in der Quelle nicht bloß typographisch, der `Tag.` Punkt schon.

**Comment by dietmarpravida** [comment]
> Der Volke. ist in der Quelle nicht bloß typographisch, der Tag. Punkt schon.
wirklich? Sehe ich eigentlich nicht so, für mich sind sie parallel.

**Comment by dietmarpravida** [comment]
![punkt](https://user-images.githubusercontent.com/26788529/41615950-f8344b14-73fc-11e8-9f9e-cc915a1993b9.JPG)
Das hier zeigt m.A.n. ganz gut, warum man hier keine Punkte machen sollte.
