### ISSUE TITLE
ID für Geiger 1882

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#43]
> markiert, noch nicht vollständig, wegen fehlender Identifikationsnummer

**Comment by dietmarpravida** [comment]
Gräf Nr. 859A_e ("A" für Anmerkung, "e" für Stelle)

**Comment by thvitt** [comment]
Bitte nicht, `_` wird zum Unterteilen der ids in "Haupt-`<milestone/>`" vs. Fortsetzungsmilestones benutzt

**Comment by dietmarpravida** [comment]
@thvitt: was sonst?

**Comment by gerritbruening** [comment]
Z.B. `-` Bindestrich.

**Comment by dietmarpravida** [comment]
859A (das e ist ohnehin unverständlich); ist aber hier nicht wirklich befriediegend lösbar, man findet die Stelle bei Gräf nur mit der Seitenangabe in der Bemerkung
