### ISSUE TITLE
correct texcrit-note 6211

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#430]
Könnte man Skrupel haben

Setzte sich das wirklich 
> im Druck fort

d.h. in C 41?

**Comment by dietmarpravida** [comment]
nein, C1 42 hat "Säumniß!"

**Comment by gerritbruening** [comment]
Aber kein Komma, ich hatte es so verstanden, das komische Komma habe sich im Druck fortgesetzt.

**Comment by dietmarpravida** [comment]
Ist im Wortlaut der jetzigen 1. Fahne auch nicht anders zu verstehen, Flüchtigkeitsfehler meinerseits

**Comment by dietmarpravida** [comment]
ist in meinen hsl Korrekturausdruck übernommen
