### ISSUE TITLE
textcrit note on vor 7249 (Überschrift) Peneus

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#431]
> und II H25; ###)

Hier könnte evtl. offenbar noch etwas ergänzt werden.
Woran wäre hier zu denken?

**Comment by dietmarpravida** [comment]
Ändere zu: "In zahlreichen Bleistiftentwürfen zu verschiedenen Versen gebraucht Goethe durchweg die lateinische Namensform “Peneus” (z. B. Vers 7466 II H33, II H34; Vers 7495 II H17; Versentwurf II H42; Bühnennweisung II H49). "

II H25 entfällt

**Comment by gerritbruening** [comment]
Dies wäre für heute vielleicht auch noch zu bedenken?

**Comment by gerritbruening** [comment]
Ist erledigt.
