### ISSUE TITLE
8850 C.1 4 zweimal?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#433]
> Warum kommt C1 4 hier zweimal vor?

> Ich hielt es für vernünftig C.1 noch einmal aufzunehmen.
Zuerst als Angabe, worauf sich das Lemma primär stützt, das zweitemal zu dem Zweck, diesen Abschnitt der Textentwicklung vollständig darzustellen.

**Comment by dietmarpravida** [comment]
wird in EB erläutert
