### ISSUE TITLE
keine/komische ID

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#44]
Siehe die letzte Spalte in Tabelle http://dev.faustedition.net/archive_testimonies.

Fortsetzung von #17.

* Mit strg-f suchen,
* eventuell in Tabelle https://docs.google.com/spreadsheets/d/1UxmS--XKaV-hSABJKP8gRlmenwoeaVIn7hV49sMsWwk/edit?usp=sharing sammeln,
* für problematische Fälle wie https://github.com/faustedition/xml/issues/43 als eigene Issues anlegen und @dietmarpravida assignen

**Comment by sandrakrause** [comment]
Ich habe nun alle Problemfälle in der Tabelle gesammelt.
Manche Fehler/Probleme konnte ich direkt beheben/lösen. Diese habe ich entsprechend markiert.
Andere nicht:
Bei einigen Fällen in der Tabelle handelt es sich um Zeugnisse, zu denen wir noch kein Digitalisat haben (#12 ).
Diese sind in der zugehörigen [Tabelle](https://docs.google.com/spreadsheets/d/11Z043ZghUsXGrOiWsEJsopcub-SdeYX92rPYkfcpfiE/edit#gid=0) aufgeführt.

Ich habe das in der keine/komische-ID-Tabelle entsprechend vermerkt.

Für die anders gearteten problematischen Fälle lege ich jeweils eigene Issues an, sie sind jedoch ebenfalls in der Tabelle oben vermerkt.

**Comment by gerritbruening** [comment]
OK, gut. Was ist in der Tabelle mit den Zeilen 3 bis 9? Gibt es für die alle Issues? Ich frage, weil die Spalte an den Stellen keinen Eintrag hat. Wenn für alle diese Fälle Issues angelegt wurden, könnten wir dieses Issue hier denke ich schließen.

**Comment by sandrakrause** [comment]
Ich hatte ein Issue vergessen (s.o.)
Die Links zu den Issues habe ich jetzt in der Tabelle ergänzt. 

Damit sollten dann diese Fälle abgedeckt sein.

**Comment by gerritbruening** [comment]
Vielen Dank und eine geruhsame Nacht!
