### ISSUE TITLE
vor 6377 Ia, IIb?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#446]
Verstehe IIb nicht: aus welcher Vorlage geerbt?

> IIa solte tatsächlich nicht gebraucht werden, wo es keine frühere Überlieferung gibt (aIso auch bei vor 6097 und vor 6377, anders als in der Kopie)

**Comment by gerritbruening** [comment]
Ich belasse es vorläufig bei 1a, wir können vor Freigabe nochmal draufschauen.

**Comment by dietmarpravida** [comment]
1a

**Comment by gerritbruening** [comment]
Druck und online sind konsistent.
