### ISSUE TITLE
7729 ungewissem

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#448]
nicht ändern?
Wenn das Korrigierte schon in der Vorlage steht, wäre parallel zu vor 8359 an IIb zu denken, obwohl keine Vorlage mit der richtigen Lesart vorhanden ist.

**Comment by dietmarpravida** [comment]
Ich würde nicht ändern, bei der starken oder schwachen Flexion des Attributs ohne vorangehenden Artikel bestehen im 18. Jahrhundert sehr große Unsicherheiten, gerade beim späten Goethe. Im vorliegenden Fall kann es sogar direkt semantisch motiviert sein, da bestimmter Artikel auf etwas fest Umrissenes verweist, was hier bei ungewissen Schimmer gerade nicht vorliegt. Ich sehe hier gar keinen Fehler, allenfalls IIb*.

**Comment by gerritbruening** [comment]
Bitte nicht closen.

**Comment by gerritbruening** [comment]
> im 18. Jahrhundert sehr große Unsicherheiten, 

das sei immer zugestanden

> gerade beim späten Goethe. 

Darauf käme es hier an. Aber das kommt mir bislang gar nicht so vor, ich kann mich an keinen eigenhändigen Beleg dieser Art erinnern.

**Comment by dietmarpravida** [comment]
naja, die Debatte mit Göttling ("reines Weines") geht doch gerade um den Fall, was man macht, wenn einem Adjektiv kein Artikel vorhergeht. Es ist zugegebenermaßen nicht ganz derselbe Fall wie hier, wo es um Präpositionalphrasen geht.

**Comment by gerritbruening** [comment]
> Präpositionalphrasen 

(im Dativ) und im speziellen das m/n-Problem

**Comment by dietmarpravida** [comment]
Man könnte den Eingriff wohl wegen der analogen Fälle 10636 und 10959 (warum nicht gesencktem] IV H.22 gesenckten H resp. heilgem] IV H.22 e heilgen H??) machen. Evtl. Anm.

**Comment by gerritbruening** [comment]
> _warum nicht_ gesencktem] _IV H.22_ gesenckten _H_

Weil H.22 die Endung nicht klar erkennbar ist.

>_warum nicht ..._ heilgem] _IV H.22e_ heilgen _H?_

Du meinst http://dev.faustedition.net/print/faust.39#app.10959.heiligem?
Aber da steht das doch so?

**Comment by dietmarpravida** [comment]
> Aber da steht das doch so?

stimmt, seltsam

**Comment by gerritbruening** [comment]
Ich belasse es beim jetzigen Stand.

**Comment by gerritbruening** [comment]
Für mich ist jetzt noch unklar, ob es neben 1a auch 2b heißen soll.

**Comment by dietmarpravida** [comment]
Ich habe Ia, IIb notiert und würde das auch machen, damit es nicht aussieht, als sei es ein ganz anderer Fall wie die unter 2b stehenden.

**Comment by gerritbruening** [comment]
Und 4680 dann zusätzlich 2aa?
7544 zusätzlich 2aa?
7776 usw?

**Comment by dietmarpravida** [comment]
ich würde es nicht übertreiben, 4860, 7544, 7776 sind doch ganz klare Fälle, während wir bei 7729 immerhin einen ganzen Thread volldiskutiert haben

**Comment by gerritbruening** [comment]
Na gut:
