### ISSUE TITLE
7776 und vor 7877 IIa?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#449]
Wohl versehentlich für IIaa, da gegen unmittelbare Vorlage?

**Comment by gerritbruening** [comment]
Dieses Issue basiert glaube ich auf einem Korrekturvorschlag von @dietmarpravida.

**Comment by dietmarpravida** [comment]
dürfte erledigt sein (> Ia), nicht?

**Comment by gerritbruening** [comment]
Ja, Druck und online sind konsistent.
