### ISSUE TITLE
GJb-Verweise in Metadaten durch Autor-Jahr ersetzen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#45]

**Comment by dietmarpravida** [comment]
@gerritbruening Ungeklärt ist immer noch, ob es auf der Ebene der Bibliographie Links auf die Bibliographie  geben soll (ob es aso heißt: ..., in: GJb 1 (1880)... oder: ... in: faust://bibliography/gjb_1,... Ich persönlich bin gegen solche selbstrefexiven Links.

**Comment by thvitt** [comment]
`in: faust://bibliography/gjb_1` wird bereits unterstützt (mit Durchklickbarkeit) und ist bereits vorhanden, siehe z.B. [Fischer-Lamberg 1954](http://dev.faustedition.net/bibliography#fischer-lamberg1954). Im Sinne der Konsistenz und der Benutzbarkeit bitte diese Verweisform benutzen.

**Comment by dietmarpravida** [comment]
ah okay, dann vereinheitliche ich das entsprechend
