### ISSUE TITLE
zu 10452

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#450]
mehr Hss angeben?
H.14 -- H.13 -- H

**Comment by dietmarpravida** [comment]
warum?

**Comment by gerritbruening** [comment]
Waren im Scan hingeschrieben. Nur à propos?

**Comment by dietmarpravida** [comment]
An der Stelle kann man gut sehen, was mit Umlauten so passiert. Da man dazu eine Anmerkung machen könnte, habe ich das notiert, insofern apropos

**Comment by gerritbruening** [comment]
OK
