### ISSUE TITLE
after_10570 nicht IIaa?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#451]

**Comment by dietmarpravida** [comment]
Die Verwendung von IIaa verstehe ich sowieso nicht so ganz, musst du entscheiden

**Comment by gerritbruening** [comment]
Das vergebe ich, wenn nichts für eine nicht erhaltene Zwischenstufe spricht, also anhand der unmittelbaren Vorlage korrigiert werden kann.
