### ISSUE TITLE
Leseregeln erklären

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#455]
Im Nachwort sollte auch die Leseregel für den Doppelpunkt erklärt werden

**Comment by gerritbruening** [comment]
Ist im Korrektur-Dokument schon eingetragen.

**Comment by dietmarpravida** [comment]
welches Korrektur-Dokument?

**Comment by dietmarpravida** [comment]
Auch die Syntax "G H II H74" u.ä. sollte erläutert werden

**Comment by gerritbruening** [comment]
OK, habe ich auf genommen. Ich denke, es reicht, wenn das im Korrekturdokument steht.
