### ISSUE TITLE
5107, 10790 ohne Punkt, welcher Typ?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#456]
Wenn 10790 IIaa, dann wohl auch bei 5107?

**Comment by dietmarpravida** [comment]
ich kenne mich grade nicht mehr aus. Scheint aber dasselbe wie 4877 (= IIaa), oder macht das "?" den Unterschied?

**Comment by gerritbruening** [comment]
"Ich" ohne Fragezeichen bietet an sich keinen Anstoß, ist nur anhand der Vorlage H als Fehler zu erkennen.
Die im Titel genannten Fälle sind anders: Hier fehlt jeweils der Punkt am Ende einer Figurenrede.

**Comment by dietmarpravida** [comment]
Ermessenssache, sollte aber entsprechend 4135 (derzeit: IIa) behandelt werden, daher habe ich bei 10790 IIaa vorgeschlagen (und konsequenterweise dann auch 5107) , ich bin aber grade sehr unsicher geworden

**Comment by gerritbruening** [comment]
> sollte aber entsprechend 4135 (derzeit: IIa) behandelt werden

Gut, ändere ich entsprechend.
