### ISSUE TITLE
Multiple occurence of witnesses in app entries

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#458]
Betrifft 
* 8550 C.14
* vor 10067 alsobald

> Ich hielt es für vernünftig C.1 noch einmal aufzunehmen.
Zuerst als Angabe, worauf sich das Lemma primär stützt, das zweitemal zu dem Zweck, diesen Abschnitt der Textentwicklung vollständig darzustellen.

**Comment by dietmarpravida** [comment]
sieht halt wie ein Fehler aus

**Comment by gerritbruening** [comment]
Nur, wenn der Zeuge an der jeweils zweiten Stelle wegfällt, ist nicht klar, in welcher genealogischen Position die Emendationsgrundlage steht.

**Comment by dietmarpravida** [comment]
dann lass es so

**Comment by gerritbruening** [comment]
OK, vgl. immerhin jetzt http://dev.faustedition.net/print/faust.42#app.11422.dich. Dort habe ich die Wiederholung eingespart.
