### ISSUE TITLE
Abk. mglw in app entries

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#459]
Haben wir die oder nicht? Ich finde, wir sollten sie nutzen können.

**Comment by dietmarpravida** [comment]
bisher haben wir sie nicht > unter editorischen Abkürzungen im Nachwort aufnehmen

**Comment by gerritbruening** [comment]
Aber ist das nicht so wie vgl. und d.h.?

**Comment by dietmarpravida** [comment]
nein, vgl und dh sind allgemein üblich, mglw nicht

**Comment by dietmarpravida** [comment]
wir erklärens also nicht, wird schon gehen
