### ISSUE TITLE
GJ 22, 74 - graef_895: Doppelte Aufführung in Zeno

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#46]
Der Brief 2806a von Goethe an Göschen ist in der WA im Ergänzungsband WA IV, 30 enthalten.
Zeno hat den Brief chronologisch in WA IV, 9 eingefügt.
Dadurch haben wir den Brief nun zweimal in unseren xml-Dateien, wodurch er auch zweimal markiert wurde und wodurch wiederum es nun zu einer Doppelung der vergebenen ID (graef_895) kommt.
Soll nun der Brief aus der xml-Datei aus WA IV, 9 entfernt werden (weil er dort eigentlich nicht enthalten ist) oder soll die Markierung in WA IV, 30 entfernt werden?

Teil von #44

**Comment by gerritbruening** [comment]
> Soll nun der Brief aus der xml-Datei aus WA IV, 9 entfernt werden (weil er dort eigentlich nicht enthalten ist) oder soll die Markierung in WA IV, 30 entfernt werden?

Ja, der Brief soll aus WA IV, 9 entfernt werden , weil er nicht in dem Band steht, und nur in WA IV, 30 stehen und markiert sein.

**Comment by sandrakrause** [comment]
Danke sehr, habe ich so erledigt.

**Comment by gerritbruening** [comment]
Danke!
