### ISSUE TITLE
8506 Eröffnet

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#460]
Was ist hier fraglich?
Ob das da steht? Ob von Riemer, oder ob das die einzige Änderung ist, die nicht fixiert wurde?

**Comment by dietmarpravida** [comment]
Der Bezug der Doppelpunkt-Änderung auf die Siglen scheint mir unklar, man könnte ja meinen, dass in allen Hss derselbe Vorgang vorkam

**Comment by gerritbruening** [comment]
Ja OK, das ist wieder so eine arkane AA-Konvention. Werde die Lesart wiederholen.

**Comment by gerritbruening** [comment]
#461
