### ISSUE TITLE
correct textcrit note ad 8506

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#464]
> Der Vorschlag ist in der ganzen Handschrift **III H3:2** der einzige, der von Goethe
nicht fixiert und mithin auch nicht ausdrücklich akzeptiert wurde.

@gerritbruening muss heißen II H3a:2, oder?

**Comment by gerritbruening** [comment]
Nein, III H3

**Comment by dietmarpravida** [comment]
wird derzeit im Siglenverzeichnis nicht erklärt

**Comment by gerritbruening** [comment]
III H3 ist ins Korrekturdokument übernommen.
Hast du die Korrektur der Anmerkung hsl eingetragen? Dann hier closen.

**Comment by dietmarpravida** [comment]
Im Korrekturdokument steht nichts (mehr) dergleichen. 

Soll es also heißen:
> Der Vorschlag ist in der ganzen
Handschrift III H3 der einzige, der von Goethe nicht fixiert
und mithin auch nicht ausdrücklich akzeptiert wurde.

?

**Comment by gerritbruening** [comment]
Korrektur ist eingetragen.
