### ISSUE TITLE
IV H.3 10172 die aus da

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#469]
@dietmarpravida, könntest du mal auf diese Stelle schauen:
http://dev.faustedition.net/document?sigil=2_IV_H.2&page=3&view=facsimile_text#l10172
Es scheint ursprunglich "da" ergänzt, evtl. dann geändert zu "die", was hier einfach als "die" transkribiert wurde. Wenn das so zu transkribieren ist, wäre "da" in H ein Fehler, der zu emdieren ist.
Also hast du eine spontane Meinung zu "die" und "da" in IV H.3?

**Comment by gerritbruening** [comment]
Habe das jetzt mal [so](https://github.com/faustedition/faust-gen-html/commit/6f32b20867c15b8ab619e61f951c4d539eeafaa2#diff-a48138172ec406b07f08b2d419608958R161) verzeichnet.

**Comment by dietmarpravida** [comment]
() (1) Und da verbrächt ich meine Zeit 

(2 (2) Und verbrächt da gränzenlose Zeit 

(3) Verbrächte die gränzenlose Zeit 


Von: "Gerrit Brüning" <notifications@github.com> 
An: "faustedition/xml" <xml@noreply.github.com> 
CC: "dietmarpravida" <dpravida@goethehaus-frankfurt.de>, "Mention" <mention@noreply.github.com> 
Gesendet: Donnerstag, 26. Juli 2018 14:53:48 
Betreff: [faustedition/xml] 10172 die oder da? (#469) 



@dietmarpravida , könntest du mal auf diese Stelle schauen: 
http://dev.faustedition.net/document?sigil=2_IV_H.2&page=3&view=facsimile_text#l10172 
Es scheint ursprunglich "da" ergänzt, evtl. dann geändert zu "die", was hier einfach als "die" transkribiert wurde. Wenn das so zu transkribieren ist, wäre "da" in H ein Fehler, der zu emdieren ist. 
Also hast du eine spontane Meinung zu "die" und "da" in IV H.3?

**Comment by gerritbruening** [comment]
Also "die" aus "da"?
"da die" scheint mir möglich, aber nicht notwendig anzunehmen.

**Comment by dietmarpravida** [comment]
die aus da hätte ich angenommen

**Comment by gerritbruening** [comment]
Gut, d.h.: 
http://dev.faustedition.net/print/faust.37#app.10172.die
(Neuerung)

**Comment by gerritbruening** [comment]
Das ist aber unabhängig von "die" oder "da", oder?

**Comment by dietmarpravida** [comment]
ja, natürlich

**Comment by gerritbruening** [comment]
Die Transkription muss noch korrigiert werden.

**Comment by gerritbruening** [comment]
done
