### ISSUE TITLE
Reichard 1778a und Reichard 1778b (1779a/b?)

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#47]
Reichard 1778 gehört zu den Zeugnissen zur Nachdigitalisierung #12 
Deswegen wird in der Tabelle keine ID angezeigt.
Zwei Dinge sind dabei jedoch unklar/aufgefallen:

1. In der [Tabelle](http://dev.faustedition.net/archive_testimonies) wird bei Reichard 1778b nun aber angezeigt "keine/komische ID: »quz_ «". Woher kommt diese ID, wenn wir gar kein xml-Dokument für Reichard 1778b haben?
2. Zusätzlich ist Reichard 1778a/b nicht in der Wiki-[Bibliographie](https://faustedition.uni-wuerzburg.de/wiki/index.php/Bibliographische_Verweise#R) aufgeführt. Hier findet man jedoch Reichard 1779a und Reichard 1779b, die jeweils 1778 erschienen sind. In der Excel-Tabelle wiederum gibt es Reichard 1779 nicht, sondern nur Reichard 1778. Liegt hier ein Fehler vor?

Teil von #44

**Comment by thvitt** [comment]
zu 1.: Die ID wird für jede Zeile der Excel-Tabelle aus der ersten nicht leeren Spalte aus Gräf-Nr., Pniower-Nr., QuZ und Biedermann-HerwigNr. gebildet. Gibt's in keiner dieser Spalten einen Eintrag → keine ID. (Die so vorberechnete ID wird dann in `<milestone unit="testimony"/>` gesucht.) Der Meldung nach steht im QuZ-Feld irgendeine Art von Leerzeichen.

**Comment by sandrakrause** [comment]
@thvitt Vielen Dank für die Erklärung!
Ich habe das Leerzeichen aufgespürt und entfernt.

**Comment by gerritbruening** [comment]
* [ ] URI festlegen: Reichard 1778a/b oder 1779a/b
* [ ] Abhängig davon Spalte Druckort (jetzt "Reichard 1778a / Reichard 1778b) ändern oder belassen

**Comment by dietmarpravida** [comment]
Verfügbarkeit der beiden Ausgaben prüfen!

**Comment by dietmarpravida** [comment]
Wird nach Tille digitalisiert
