### ISSUE TITLE
rend="indented" lost on 11424

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#473]
H hat 

                           <l n="11424" rend="indented">Würde mich kein Ohr vernehmen</l>

aber das `@rend` überlebt in faust.xml nicht.

**Comment by thvitt** [comment]
ist bereits vor dem einzelstellenapparat.

Zum Kontext:

```xml
<sp>
   <speaker n="before_11424">Sorge</speaker>
   <lg rend="indented">
      <l n="11424">Würde mich kein Ohr vernehmen</l>
      <l n="11425" rend="indented">Müßt es doch im Herzen dröhnen;</l>
      <l n="11426" rend="indented">In verwandelter Gestalt</l>
      <l n="11427" rend="indented">Üb’ ich grimmige Gewalt.</l>
      <l n="11428" rend="indented">Auf den Pfaden, auf der Welle</l>
      <l n="11429" rend="indented">Ewig ängstlicher Geselle,</l>
      <l n="11430" rend="indented">Stets gefunden nie gesucht,</l>
      <l n="11431" rend="indented">So geschmeichelt wie verflucht.</l>
      <l n="11432">Hast du die Sorge nie gekannt?</l>
   </lg>
</sp>
```

da war doch was mit 'indented in indented, aber nicht das erste' oder so?

**Comment by gerritbruening** [comment]
Ja, Daten sind geändert, lg ist weg.

**Comment by thvitt** [comment]
@gerritbruening , die hier zuschlagende Regel – rend=indented wegwerfen wenn’s das erste Element ist – ist von dir. https://github.com/faustedition/faust-gen-html/commit/cac36a3b6f6cf6af5c1d1b5077fd4e4f6cebfcd3

Was soll da nun geschehen? Sie hat ja wohl irgendeinen Sinn gehabt

**Comment by gerritbruening** [comment]
Ja, das war für eine typographische Konvention im Druck, die ignoriert werden soll: den Erstzeileneinzug bei eingerückter Versgruppe (Bsp. [C.1 4, S. 25](http://dev.faustedition.net/document?sigil=C.1_4&page=25&view=facsimile_text)).
Also müsste die Regel lauten: `rend="indented"` wegwerfen, wenn nur das erste `l`-Element eines trägt.

**Comment by gerritbruening** [comment]
Ah, natürlich. Danke!
