### ISSUE TITLE
10909 sich

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#477]
Muss "sichs" emendiert werden, auch gegen Goethes Reinschrift?

**Comment by dietmarpravida** [comment]
Ich würde es nicht machen. Das "es" ist hier syntaktisch ein reiner Dummy-Term einer unpersönlichen Konstruktion, um eine Satzposition zu besetzen, und das auch noch in einem Nebensatz. Man könnte auch denken, dass das Subjekt hier aus dem Kontext erschließbar ist. Evt. Fall für eine Anmerkung.

**Comment by gerritbruening** [comment]
Danke, ist im Korrekturdokument vermerkt.
