### ISSUE TITLE
11593 Versabteilung

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#478]
Nach V H.2 wäre richtig:

```
              Meph.
Die Uhr steht still
              Chor
                    Steht still
Sie schweigt wie Mitternacht
```

**Comment by dietmarpravida** [comment]
Wenn das strikt analog zu "Und ich, der Gottverhaßte, hatte nicht genug," ist (was mir der Fall zu sein scheint), wäre ich für analoges Vorgehen, d.h. Umbruch und a-b-Verszahlen

**Comment by gerritbruening** [comment]
Und nicht durch die darunter folgende Schlängellinie autorisationsbestrahlt?

**Comment by dietmarpravida** [comment]
übrigens wieder so ein Fall, wo man vom Apparat zu 11593 aus auf Seite 363 statt auf Seite 364 geleitet wird.

**Comment by dietmarpravida** [comment]
die Schlangenlinie (Schlängellinie? wtf?) scheint sich mir zu den Fragen der Versabeteilung nicht mit ausreichender Bestimmtheit zu äußern

**Comment by dietmarpravida** [comment]
Wenn die Versabteilung neu eingefügt wird, dann müsste das in der betreffenden Anmerkung im Nachwort mit aufgezählt werden.

**Comment by gerritbruening** [comment]
Mir ist nich wohl bei der Sache, weil die Vorlagensituation undurchsichtig ist. Eine direkte Abschrift von V H.2 liegt, wie schon beim Schlussmonolog, nicht vor, siehe http://dev.faustedition.net/genesis_bargraph?rangeStart=11539&rangeEnd=11603.
Auch die große Lücke nach 11593 ist seltsam, sie ist in V H.2 in keiner Weise angewiesen.
Dagegen scheint die Antilabe 11594 H S. 365 oben ergänzt, obwohl sie in V H.2 schon enthalten ist.
Schließlich passt die in H entstandene Versabteilung zu dieser wie auch zur gleich danach folgenden analogen Antilabe 11595.

**Comment by dietmarpravida** [comment]
Hm, aber gar nichts zu sagen fände ich auch nicht recht
