### ISSUE TITLE
zu 8670 Apparat ausführlicher?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#479]
@dietmarpravida, hättest du den Apparateintrag lieber in der ausführlicheren Form

![grafik](https://user-images.githubusercontent.com/10358005/43395580-e3cc3002-93fe-11e8-9ff7-f166bc6f614b.png)

?

**Comment by dietmarpravida** [comment]
ja, aber müsste nicht Ri dazu mit angegeben werden?

**Comment by gerritbruening** [comment]
Ja, und einmal John (Selbstkorrektur IIRC)

**Comment by gerritbruening** [comment]
Fixed in https://github.com/faustedition/faust-gen-html/commit/ae08113c015dea9a65e51f64df607832df9c0fcc.
