### ISSUE TITLE
7583 Ritzen WA JA

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#485]
Apparateintrag folgt in Kürze. Man könnte geneigt sein, hier doch "Ritzen" herzustellen, vgl. auch 7591.

**Comment by dietmarpravida** [comment]
Paul, Bd. 2, § 54, S. 92 sagt, dass Ritz/Ritze schwankendes Genus hat: mask. Ritz, pl Ritze; fem. Ritze, pl. Ritzen; die Wahl des Femininums kann durchaus durch Reimerfordernisse bestimmt sein. Ich würde nichts ändern.

**Comment by gerritbruening** [comment]
Anmerkung machen, dass "Ritze" mask. pl. sein könnte?

**Comment by dietmarpravida** [comment]
scheint mir auch ohne Anmerkung evident, dir nicht?

**Comment by gerritbruening** [comment]
Siehe jetzt http://dev.faustedition.net/print/faust.33#app.7583.ritze

**Comment by dietmarpravida** [comment]
ok

**Comment by gerritbruening** [comment]
Für lag das Feminum näher. Apparateintrag dann auch überflüssig, oder ist die Emendation buchenswert?

**Comment by dietmarpravida** [comment]
hängt davon ob, wie du das sonst handhabst. Habe aber im Prinzip nichts gegen die Buchung.

**Comment by gerritbruening** [comment]
Ich gehe gerade dazu über, ein paar diskutable Emendationen zu buchen, siehe #486.

**Comment by gerritbruening** [comment]
D.h. es liegt kein Fehler vor, ich muss es zu Typ 7 machen.
