### ISSUE TITLE
10060 quellen?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#486]
Siehe den baldigen Apparateintrag.

**Comment by dietmarpravida** [comment]
wäre interessant zu wissen, ob Goethe die starke (intransitive) Form "quellen, quill, quoll" überhaupt häufiger verwendet; m.W. gebraucht er oft die schwache (transitive) Form "quellen, quelle, quellte" in intransitiven Konstukrtionen, wo eigentlich die starke angebracht wäre (siehe auch Paul II, § 165 A.7, S. 221, wo aber nur auf DWb verwiesen wird)

**Comment by dietmarpravida** [comment]
die Schlangenlinie (Schlängellinie? wtf?) scheint sich mir zu den Fragen der Versabeteilung nicht mit ausreichender Bestimmtheit zu äußern

**Comment by dietmarpravida** [comment]
ich unassigne mich zwischendurch, um den Überblick zu bewahren

**Comment by gerritbruening** [comment]
Besprechen, ob 2b0 geht.

**Comment by gerritbruening** [comment]
> ja, die starke Form kommt oft vor 

WA hat 11 mal "quoll" und 3 mal "quollen"
