### ISSUE TITLE
7049 von / vor

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#487]
1a, 2b oder 3*?
Etwas verzagt.

**Comment by dietmarpravida** [comment]
wenn du eingreifst: 1a, wenn nicht 1a*, wenn du das nicht mal für einen Fehler halten willst 3, das wäre die schächste Version (danach kommt nur noch 7)

**Comment by dietmarpravida** [comment]
ich unassigne mich zwischendurch, um den Überblick zu bewahren

**Comment by gerritbruening** [comment]
Bin jetzt doch auf 1a* zurückgewichen.

**Comment by gerritbruening** [comment]
Es soll eine Anmerkung geben, ist vermerkt.
