### ISSUE TITLE
Tille-Nr. als ID für Anonym 1779, S. 237 verwenden

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#49]
Aufgrund fehlender Identifikationsnummer konnte dieses Zeugnis in der xml-Datei noch nicht markiert werden.

Teil von #44

**Comment by dietmarpravida** [comment]
Hat die Tille-Nr. 313;
@thvitt Tille-Nummern in der excel-Datei sollten als IDs akzeptoiert werden können

**Comment by thvitt** [comment]
aus irgendwelchen Gründen ist die Spalte Tille-Nr. in der Exceltabelle eine Kommazahl‽

**Comment by dietmarpravida** [comment]
müsste jetzt in der aktuellen Tabelle gelöst sein, ich habe alle Spalten von lfd. Nr. bis Biedermann-Herwig als "Text" formatiert, ich hoffe, dass das jetzt nicht neue Probleme schafft?

**Comment by thvitt** [comment]
ach sorry, hatte das im Skript bereits umschifft. Sollte aber keine neuen Probleme schaffen.
