### ISSUE TITLE
vor 8359 Psellen / Psyllen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#496]
Offen ist für mich noch, ob neben 1a noch 2b gelten soll. Ich belasse es erstmal bei 1a.

**Comment by dietmarpravida** [comment]
Ja, scheint mir auch so

**Comment by gerritbruening** [comment]
D.h., hier ist anders als im Fall von #448 nicht klar, ob 2b dazu soll, richtig?

**Comment by dietmarpravida** [comment]
Naja, so eindeutig wie 4860 etc. ist es nicht. Andererseits ändern wir trotzdem auch ohne Vorlage. Daher vielleicht nur 1a?

**Comment by dietmarpravida** [comment]
1a
