### ISSUE TITLE
Nur die erste ID aus Spalte für das matching herausziehen, beide in Tabellenspalte ausgeben

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#50]
In der Excel-Tabelle stehen für dieses Zeugnis zwei Identifikationsnummern (in einem Feld): quz_II-638, IV-1797.
Seltsamerweise ist jedoch weder in der xml-Datei quz_2 noch in der xml-Datei quz_4 dieses Zeugnis enthalten. Ich habe es der Tabelle "[zeugnisse-nachdigitalisierung](https://docs.google.com/spreadsheets/d/11Z043ZghUsXGrOiWsEJsopcub-SdeYX92rPYkfcpfiE/edit#gid=0)" hinzugefügt.
Damit die ID, sobald vorhanden, in der Tabelle http://dev.faustedition.net/archive_testimonies richtig erkannt werden kann, darf in der Excel-Spalte nur eine ID stehen, die andere muss evtl. in eine andere Spalte ausgelagert werden. (Das Zeugnis in QuZ II ist hierbei das ausführlichere, während in QuZ IV nur ein kleiner Ausschnitt daraus steht.)

Teil von #44

**Comment by gerritbruening** [comment]
> Seltsamerweise ist jedoch weder in der xml-Datei quz_2 noch in der xml-Datei quz_4 dieses Zeugnis enthalten.

Ist es denn in WA IV, 40 enthalten? Wenn ja, wurde nicht nochmalige die Wiedergabe in QuZ digitalisiert, sondern nur die ID von dort bezogen.

**Comment by gerritbruening** [comment]
@dietmarpravida : neu Spalte für QuZ-Zweitnummer?

**Comment by sandrakrause** [comment]
@gerritbruening
Auf das Naheliegendste bin ich da wohl nicht gekommen: Sie haben recht, in WA IV, 40 ist das Zeugnis natürlich enthalten und auch markiert.
Bleibt also nur das Problem mit der QuZ-Zweitnummer.

**Comment by thvitt** [comment]
kommt das denn regelmäßig vor, dass es mehrere IDs des primären Referenzsystems gibt? Dann könnte man ggf. auch für die ID einfach immer nur die erste heranziehen und die andere nur mit abdrucken. Dh die ID des og Eintrags wäre `quz_II-638`, im Feld stünde `I-638, IV-1797`.

**Comment by gerritbruening** [comment]
Ja, finden wir gut, dann müsste man nicht bei nur einem Fall eine ganze Tabellenspalte hinzufügungen, denn häufig kommt es nicht vor. Die Regel muss dann nur sein, die (aus welchen Gründen auch immer) maßgebliche ID nach vornze zu stellen, auch wenn sie nach Zählung hinter der anderen gekommen wäre.

**Comment by gerritbruening** [comment]
@sandrakrause sortiert Werte in Spalte ggf. um, @thvitt: so wie vorgeschlagen.
