### ISSUE TITLE
5993 wilde

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#500]
schwanke ich, ob "wilder" in den Text gesetzt werden muss. Würde es eigentlich gern vermeiden, aber H scheint Abschrift von H.43a

**Comment by dietmarpravida** [comment]
scheint mir grammatisch mit "wilder" eher tragbar

übrigens sollte erschlossene Zwischenhandschriften mal irgendwo dokumentiert werden

**Comment by gerritbruening** [comment]
> erschlossene Zwischenhandschriften

Wo wir gerade dabei sind: Gibt es zwischen V H.2 und H eine solche? Ode war das damals nicht Teil der Untrsuchung?

**Comment by dietmarpravida** [comment]
Ich hatte dazu mal eine Meinung (ja, glaube ich), müsste ich aber erst rekonstruieren

**Comment by dietmarpravida** [comment]
wird jetzt anscheinend nicht geändert, oder? Dann schließen.

**Comment by gerritbruening** [comment]
Oh, glatt vergessen.

**Comment by gerritbruening** [comment]
Ist geändert http://dev.faustedition.net/print/faust.30#l5993, im Satz auch.
