### ISSUE TITLE
6016 keines

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#501]
ist auch verdächtig, da die Vorlage "keiner" hat. Scheint aber nicht schlecht zu passen.

**Comment by dietmarpravida** [comment]
Ist I H44 "keiner" absolut eindeutig?

**Comment by dietmarpravida** [comment]
genau das scheint mir nicht gemeint zu sein

**Comment by dietmarpravida** [comment]
dann würde ich (so obenhin) dazu tendieren, auf "keiner" zurückzugehen

**Comment by dietmarpravida** [comment]
in Datei eintargen, dann schließen

**Comment by gerritbruening** [comment]
Ist beiderseits eingetragen.
