### ISSUE TITLE
5904 Tageslüften

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#503]
wohl besser "Tages Lüften" I H.41a 
Kann man hier nicht wenigstens sagen: das lassen wir, weil getrennt zusammen immer so eine Sache ist?

**Comment by dietmarpravida** [comment]
mm, das ist eine prinzipielle Frage, die du eigentlich schon entschieden haben solltest. Ich hätte nie von A auf S zurückgeändert, nur weil es in S anders ist; bei der Überlieferung von F-II kann und muss man anders verfahren, aber es ist keine Frage einzelner Stellen

**Comment by gerritbruening** [comment]
Vergleichbar ist eigentlich nur http://dev.faustedition.net/print/faust.30#app.5146.wunderseltsam, wo mir der Sinn klar berührt zu sein scheint.
In diesem Fall ist mir nicht auf Anhieb klar, ob die "Lüfte des reinen Tages" (Goethe) etwas anderes sind als die "reinen Tageslüfte" (John). Das "rein" bezieht sich wohl auf Unterschiedliches; einmal sind die Lüfte rein, einmal der Tag.

**Comment by dietmarpravida** [comment]
das ist so ein Fall von zwar nicht morphologischem, aber doch semantischem Attributbezug auf das Vordererglied eines Kompositums, kommt oft vor ("deutscher Heimatminister" = Minister für deutsche Heimat oder deutscher Minister für Heimat?), aber klar, hier muss man eingreifen, wie unser Innenminister es auch täglich macht

**Comment by dietmarpravida** [comment]
nicht mal, heißt, du lässt es so sans phrase?

**Comment by dietmarpravida** [comment]
dürfte durch EB-Nachtrag geklärt sein

**Comment by gerritbruening** [comment]
Ja.
