### ISSUE TITLE
6267 Bist du beschränkt

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#504]
scheint mir jetzt ein dicker Fehler zu sein, lies:
Bist so beschränckt

**Comment by dietmarpravida** [comment]
Ja, Trivialisierung durch den Schreiber, der ein Anredepronomen haben wollte, wo eins zu fehlen schien.

**Comment by dietmarpravida** [comment]
erscher Manier könnte

**Comment by dietmarpravida** [comment]
in deiner Datei eintragen, dann schließen

**Comment by gerritbruening** [comment]
Ist gemacht.
