### ISSUE TITLE
3899 Stecken : Strecken

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#507]
Sieht in der Fahne derzeit ungenau so aus:
![3899 teko](https://user-images.githubusercontent.com/26788529/43966171-78eee8d0-9cc1-11e8-92a2-19de0218d319.JPG)

In der digitalen Edition so: 

![3899 h1](https://user-images.githubusercontent.com/26788529/43966123-58895c92-9cc1-11e8-96f2-960f75e88680.JPG)

Wie würdest du den Apparateintrag formulieren (es geht um den Doppepunkt)?

**Comment by dietmarpravida** [comment]
Siehe auch #511

**Comment by gerritbruening** [comment]
Ich habe mir in analogen Fällen erlaubt, den Doppelpunkt nicht zu machen, wenn die ersetzte Variante (hier = B) schon vorkommt.
http://dev.faustedition.net/print/faust.30#app.5265.lust (letzte Variante)
Dann wäre das hier in Ordnung, abgesehen vielleicht von
> Strecken _propon Gö H.6_ Strecken _G H.1 C.1 C.3_

**Comment by dietmarpravida** [comment]
ich finde ja, dass hier (und generell) "G" unglücklich und für den nicht ganz eingeweihten Leser irreführend aussieht, daher würde ich lieber schreiben:

`Strecken] H14  Stecken A B Ba 	Strecken propon Gö H6 	Stecken : Strecken G H1 	Strecken C1 C3 `

**Comment by gerritbruening** [comment]
Das ist die luxuriöse Variante, das geht immer. Nichts dagegen.
Aber ist "G" grundsätzlich schlecht? Brauchen wir da etwas anderes? Oder sind nur unmittelbar folgende Siglen das Problem?

**Comment by dietmarpravida** [comment]
Man könnte an der Optimierung der zugehörigen Erläuterung arbeiten (am besten mit Beispiel in Fußnote @gerritbruening ); das sollte idiotensicher erklärt werden

**Comment by dietmarpravida** [comment]
ggf in EB ergänzen

**Comment by gerritbruening** [comment]
Beispiel in Fußnote.
Handsigle gefolgt von Zeugensigle (evtl. gefolgt von noch einer Zeugensigle).

**Comment by dietmarpravida** [comment]
lassen wir jetzt wohl bleiben?
