### ISSUE TITLE
1957 & 9594 drinne] Hs drinnen Pr

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#509]
Darf man eigentlich im Apparat zu einem Vers einen Verweis auf einen anderen Eintrag geben? Würde sich hier anbieten.

**Comment by gerritbruening** [comment]
Fände ich eigentlich sehr gut, habe so etwas aber letztlich in die Erläuterungen verlagert. Problem dort: Man müsste eigentlich an zwei Stellen verweisen, bei drei Fällen sogar an drei mit Verweis auf jeweils unterschiedliche Partner-Einträge. Da verheddert man sich leicht.

**Comment by gerritbruening** [comment]
Weist du die Korrektur / Ergänzung an?

**Comment by dietmarpravida** [comment]
ja
