### ISSUE TITLE
Biedermann-Herwig Nr. als ID für Pollmer 1923, S. 61

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#51]
Pollmer 1923 konnte noch nicht markiert werden, da es nicht in der xml-Datei pollmer_1923 enthalten ist.
Zusätzlich ist in der Tabelle keine Identifikationsnummer angegeben. Bei alternativer Druckort steht jedoch eine Biedermann-Angabe, die, wenn ich das richtig sehe, bei Biedermann-Herweg-Nr. eingetragen werden könnte.

Teil von #44

**Comment by dietmarpravida** [comment]
@thvitt Biedermann-Herwig-Nrn. solten als IDs verwendet werden können

**Comment by sandrakrause** [comment]
@dietmarpravida Die Biedermann-Herweg-Nummern können bereits als ID verwendet werden.
Nur ist in diesem Fall die entsprechende Spalte in der Excel-Datei nicht ausgefüllt.
Hier wäre jetzt die Frage, ob die Angabe aus "alternativer Druckort" korrekt ist und dementsprechend als Biedermann-Herwig-Nummer eingetragen werden kann.

**Comment by dietmarpravida** [comment]
Bie 3 3903
