### ISSUE TITLE
7919 Du

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#515]
@dietmarpravida,
_7919_ Dich _II H.74_ Du _H_

"Dich", kann das sein, oder muss das Fehler sein, den John bei der Abschrift stillschweigend korrigiert? Vielleicht ein IIa*-Eintrag am Platz?
"Du" ist trivialer, aber das wäre nur dann ein Argument, wenn die Angerufene sich selbst zugrunderichten könnte.

**Comment by dietmarpravida** [comment]
"Dich" scheint mir ein Antizipationsfeher in II H.74, "Du" ist nicht trivialer, sondern richtig

**Comment by gerritbruening** [comment]
Alles klar
