### ISSUE TITLE
4885 Ders

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#517]
http://dev.faustedition.net/print/faust.30#app.4885.ders

Doch lieber bleiben lassen? Bin ich fast dafür.

**Comment by dietmarpravida** [comment]
im Satz dann:
`ders] I H0a Ders H (II aa*)`
?

**Comment by gerritbruening** [comment]
Ich würde es ohne Apparateintrag lassen, denn sonst müsste man schauen, ob es nicht ähnliche Fälle gibt, die dann auch einen bekommen müssten.

**Comment by dietmarpravida** [comment]
für den Satz ist das aber ein Problem, wenn du dir die Seiten mal anschaust

**Comment by dietmarpravida** [comment]
wenn dus in deiner Datei geändert hast, bitte schließen

**Comment by gerritbruening** [comment]
ist beiderseits geändert
