### ISSUE TITLE
Doppelter Eintrag in Excel-Tabelle

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#52]
Die beiden Einträge lfd. Nr. allerneuestens 1021 & 1022 beziehen sich auf dasselbe Zeugnis, das führt zu einer Dopplung der XML-Quellen. Vermutlich können beide Zeilen zu einer zusammengefasst werden. 

Teil von #44

**Comment by dietmarpravida** [comment]
gelöscht
