### ISSUE TITLE
Thurn

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#525]
- [ ] 9199 Thurn _H.3a_ Thurm _H ff._
- [ ] vor 9218 Thurnwarter _III H.45_ Thurmwärter. _H.2:1_ , Lynceus _erg G (anstelle von Punkt), so bis C.1&nbsp;4&nbsp;&nbsp;&nbsp;Komma tilgt Göttling III H.45a_ 
- [ ] 9235 Thurn _H.3a_ Thurm _H ff._
- [ ] vor 11143 Der Thürmer _schon G V H.1 H&nbsp;&nbsp;&nbsp;davor_ Lynceus _erg G H_
- [ ] vor 11163 Thürner _G V H.1_ Thürmer _H_
- [ ] vor 11288 Lynceus der Thürner _G V H.1_ Lynceus, der Thürmer _H_
- [ ] 11290 Thurne _G V H.1_ Thurme _H_
- [ ] 11340 Thürner _G V H.1_ Thürmer _H_

Vgl. Paul, Bd. 1, S. 361f., § 234, hier: S. 362 Anm. 1 ("Turn" die originäre Form) 

Gesichtspunkte:
* "Thürmer" auch bei Goethe
* "Thürmer" zweimal bei Änderung unbeanstandet

**Comment by gerritbruening** [comment]
Gedrucktes GWb geht bis Portrait.

**Comment by dietmarpravida** [comment]
ist ein interessaanter Fall, aber wohl eher für eine Erläuterung ls für eine Textänderung. Auf 11143 G mit -m muss man wohl nicht viel geben, wenn die anderen beiden Stellen in 11163 und 11288 ungefähr gleichzeitig sind

**Comment by gerritbruening** [comment]
> wenn die anderen beiden Stellen in 11163 und 11288 ungefähr gleichzeitig sind

klar, die sind ja in der gleichen Hs

**Comment by gerritbruening** [comment]
Also werden die Türme nicht abgetauscht.

**Comment by dietmarpravida** [comment]
ich habe deine Ergänzung im EB jedenfalls so verstanden

**Comment by gerritbruening** [comment]
Wenn man mich damit passieren lässt?

**Comment by dietmarpravida** [comment]
Hm, ist deine Entscheidung, ichs chwanke selbst, wie du oben nachlesen kannst. Sympathischer wäre mir -n, das ist doch der echte Goethe.
