### ISSUE TITLE
9843ff. erläutern?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#526]
Da gibt es ja allerhand Konjekturen. Sollen wir das erläutern?

**Comment by dietmarpravida** [comment]
Denk übrigens daran, die textkritischen Probleme im Wiki nicht zu vergessen, bei F-II könnten einige Stichwörter später mal von Nutzen sein

**Comment by dietmarpravida** [comment]
sehe eigentlich keinen Grund hier etwas anzumerken, da MA ad loc. das Nötige sagt (allerdings dort Doppelpunkt nach "Bluts")

**Comment by gerritbruening** [comment]
Umso besser. Dass die Editionen alle etwas tun und was, wird ja in EB vermerkt.

**Comment by dietmarpravida** [comment]
> Dass die Editionen alle etwas tun und was, wird ja in EB vermerkt.

wie meinen?
