### ISSUE TITLE
5441-5456

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#527]
warum nicht auch

`eingerückt H C1`

im Apparat?

**Comment by dietmarpravida** [comment]
entsprechend dann wohl auch 5484-5493, 5640 – 5645, 5715 – 5726, 5748 – 5756

**Comment by gerritbruening** [comment]
Die Reihe 
> H C.1

geht wohl nicht. Ich hatte gedacht, H sei immer so wie H.0a, und C sei in diesem Fall egal.

**Comment by dietmarpravida** [comment]
Das war aber nicht die Frage.

**Comment by dietmarpravida** [comment]
sondern: ob es nicht überhaupt genannt werden sollte, was derzeit nicht der Fall ist.

**Comment by dietmarpravida** [comment]
egal
