### ISSUE TITLE
before_5521 / before_5541

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#528]
SA vor 5521 und vor 5541
DP (09-08 & 14-08): einmal “Wagenlenker”, dann “LENKER” (ebenso ff.), so okay?

**Comment by gerritbruening** [comment]
Scheint mir uneingreifbar. Dir nicht?

**Comment by dietmarpravida** [comment]
ich frage ja nur

**Comment by gerritbruening** [comment]
Habs in die ewige Liste der (potenziellen) textkritischen Probleme aufgenommen.
