### ISSUE TITLE
Spalte "Sigle" prüfen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#53]
Ob nicht fälschlich aus "Bemerkungen" übernommen.

**Comment by gerritbruening** [comment]
Außerdem zu klären, was in @thvitt s Kommentar https://github.com/faustedition/faust-web/issues/259#issuecomment-297133570 steht:

> @dietmarpravida, @sandrakrause, es gibt noch ein paar defekte Links (d.h. nicht existierende oder falschgeschriebene Siglen in der Exceltabelle, [z.B. bei Pniower 945](http://dev.digital-humanities.de/archive_testimonies#pniower_945). Außerdem muss noch entschieden werden:
> * was in Fällen geschehen soll, in denen ein `<milestone unit="testimony"/>` unter testimonies/ _und_ eine H-Sigle vorhanden ist, z.B. [Gräf 1270](http://dev.digital-humanities.de/archive_testimonies#graef_1270)
> * ob/wie/wo für Einträge, die _nur_ Siglen haben, die Metadaten aus der Excel-Tabelle (#269) gerendert und verlinkt werden sollen

**Comment by dietmarpravida** [comment]
verstehe ich nicht

**Comment by gerritbruening** [comment]
Auf der Seite http://dev.faustedition.net/archive_testimonies gibt es drei Einträge, zu denen es heißt:
> H-Sigle nicht gefunden:

Bei zweien davon rührt das Problem daher, dass mehrere Handschriften einschlägig sind (auch III H.7 ist archivalisch aufgeteilt).

@thvitt ist jetzt im Urlaub, ich würde vorschlagen, du korrigierst den fehlenden Punkt in `2 III H19` und das Problem der mehrfachen Handschriften klären wir dann mit Thorsten.

**Comment by thvitt** [comment]
Ich würde vorschlagen, für die aufgeteilten Hs. alle einschlägigen aufzuführen; mehrfache Siglen in der Spalte sind ja möglich.

D.h. Du, @dietmarpravida, korrigierst bitte die Sigleneinträge »2 III H.6« (Pniower 932), »2 III H.7« (Pniower 945) und »2 III H19« (Pniower 934) so, dass sie exakt so lauten wie in der 1. Spalte der [Handschriftentabelle](http://dev.faustedition.net/archive_manuscripts), sonst gibt's den angegebenen Fehler.

**Comment by dietmarpravida** [comment]
2 III H.6 durch 2 III H.6:1 ersetzt; 2 III H19 mit Punkt versehen

**Comment by dietmarpravida** [comment]
Problem: Pniower-596 und -957 scheinen sich auf dieselbe Hs I H.43 zu beziehen!?

**Comment by dietmarpravida** [comment]
Siglen durchgesehen und einzelnes korrigiert
