### ISSUE TITLE
app 10771

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#530]
![10771](https://user-images.githubusercontent.com/26788529/44106600-657361b4-9ff5-11e8-945b-b89d42705d76.JPG)

hier ist das "Schienen" nach dem ] seltsam, bei Fehlkorrekturen funktioniert das bei 1a anzuwendende Prinzip nicht so gut

**Comment by gerritbruening** [comment]
Hatte sowieso überlegt, "(Fehlkorrektur)" zu streichen. Einverstanden? Und erledigt sich dann das restliche Problem?

**Comment by gerritbruening** [comment]
> kein richtiges 1a, denn letzlich gehst du auf IV H8 zurück

Wir können auch 2aa sagen. Aber bitte jetzt nicht alle 1a-Fälle wieder umändern, wo eine frühere Handschrift das richtige hat.

**Comment by dietmarpravida** [comment]
keine Angst, dieser Fall dürfte ein besonderer sein

**Comment by dietmarpravida** [comment]
okay ändere es bitte in deiner Datei zu 2aa

**Comment by gerritbruening** [comment]
Ist im Satz IIaa, online auch.
