### ISSUE TITLE
asymmetric spacing before 11656, 11670 systematic error?

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#531]
![11655](https://user-images.githubusercontent.com/26788529/44107390-7e949d32-9ff7-11e8-9070-d8a9629a6ad2.JPG)

--

![11670](https://user-images.githubusercontent.com/26788529/44107407-8d828cdc-9ff7-11e8-8a53-7e3bbdb5e737.JPG)

**Comment by dietmarpravida** [comment]
siehe auch #537

**Comment by gerritbruening** [comment]
Ja, systematisch, Korrekturen sind notiert.
Ich doublechecke morgen und close dann.

**Comment by dietmarpravida** [comment]
bitte alle Fälle notieren!

**Comment by dietmarpravida** [comment]
gehört before_8217 auch hierher?

**Comment by dietmarpravida** [comment]
ist das hier erledigt?
