### ISSUE TITLE
encoding error 5281 & encoding error app 5281

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#532]
muss nicht "kneipt" im Text stehen?

muss es im App nicht 5281 statt 5282 heißen?

Ich bin rein durch Zufall daraufgestoßen, wie überprüfen wir das am besten?

**Comment by gerritbruening** [comment]
Wie jetzt?
![grafik](https://user-images.githubusercontent.com/10358005/44115391-13db7260-a00e-11e8-8608-fa809b8f3a9c.png)

**Comment by dietmarpravida** [comment]
äh, sorry

**Comment by gerritbruening** [comment]
Hatte schon einen ordentlichen Schreck gekriegt.
