### ISSUE TITLE
Zeilenabstand der BA vor 6772 so korrekt? (Satz, Seite 288)

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#534]
@markusciupke sieht seltsam aus, oder nicht?

![before 6772](https://user-images.githubusercontent.com/26788529/44110385-d1879ef6-9fff-11e8-8a14-95c676d40913.JPG)

**Comment by markusciupke** [comment]
Das ist nicht aus dem aktuellen Umbruch. In der zuletzt gesandten Fahne von Faust II ist nach »näher« die Zeile umbrochen.

**Comment by dietmarpravida** [comment]
stimmt, Entschuldigung!

Aber, interressehalben: der Abstand zwischen kleingesetzten Textzeilen gleichgroß wie der zwischen normalgroßen Zeien, oder wie?

**Comment by markusciupke** [comment]
Nein, wir hatten beim Satz von Faust I besprochen, dass wir bei zweizeiligen BAs die zweite leicht anheben, weil sie sonst wegen der geringeren Schriftgröße zu weit von der darüberstehenden weg steht. Das habe ich bei Faust II auch so gemacht.

**Comment by dietmarpravida** [comment]
ok, das wollte ich wissen
