### ISSUE TITLE
pointy brackets in app 6319 etc.??

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#535]
![6319](https://user-images.githubusercontent.com/26788529/44112821-761fb178-a006-11e8-8de6-3af4531b0a0d.JPG)

??

**Comment by gerritbruening** [comment]
Zum ersten Fall habe ich schon eine Korrektur notiert, den zweiten Fall finde ich so OK.

**Comment by dietmarpravida** [comment]
You kidding? How is that okay?

**Comment by gerritbruening** [comment]
Zugegeben, streng nach Vorschrift müsste es

> Nun auf! ⟨ Nun auf! _tilgt G_⟩ den  

heißen.
Einverstanden?

**Comment by dietmarpravida** [comment]
ja, lieber so

warum werde ich hier assigniert?

**Comment by gerritbruening** [comment]
> warum werde ich hier assigniert?

um das 

> ja, lieber so

zu erwirken.
Danke!

**Comment by gerritbruening** [comment]
Ich muss die Korrektur noch anweisen.

**Comment by gerritbruening** [comment]
- [ ] 6319 Satz
- [ ] 6319 online
- [ ] 6983 Satz
- [ ] 6983 online
