### ISSUE TITLE
capital letters in app before 7249??

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#536]
![before 7249](https://user-images.githubusercontent.com/26788529/44113376-291f5804-a008-11e8-84ad-e01b1b80a77d.JPG)

e/E, ei/EI, Peneus/PENEUS ??

**Comment by gerritbruening** [comment]
Ups, da war es wohl etwas spät geworden.

**Comment by dietmarpravida** [comment]
im Seitenumbruch (den ich heute eine Weile lang für den Satz hielt) stehen aber noch keine Kapitale

**Comment by gerritbruening** [comment]
Ist die Korrektur angewiesen?
Würde morgen gerne double checken.

**Comment by gerritbruening** [comment]
Das
![grafik](https://user-images.githubusercontent.com/10358005/44490889-eb9f7500-a65f-11e8-8b08-3524c018e5de.png)
scheint mir so noch nicht ganz richtig zu sein, oder geht das nicht anders?
Das Komma ist wohl kursiv, aber es steht komisch in der Landschaft.

**Comment by dietmarpravida** [comment]
scheint mir okay so

**Comment by gerritbruening** [comment]
OK, dann lassen wir es so. Online ist konform.
