### ISSUE TITLE
do you like the over-m-dash in app 4680?

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#538]
![4680](https://user-images.githubusercontent.com/26788529/44114920-d06189da-a00c-11e8-9aa2-7615c905e162.JPG)

looks weird to me

**Comment by gerritbruening** [comment]
Had worse come can, would I say.
Is the stroke two far right?

**Comment by dietmarpravida** [comment]
Yes indeed, that's the impression that is getting across to me.

**Comment by markusciupke** [comment]
Das ist zugegebenermaßen Handarbeit, weil der Font kein m mit Strich hat. Ich habe es jetzt nachgearbeitet. War wirklich zu weit rechts.
[213.pdf](https://github.com/faustedition/xml/files/2288565/213.pdf)

**Comment by dietmarpravida** [comment]
@gerritbruening Es gibt noch wenigstens einen weiteren Fall, suchst du mir bitte die Stelle?

**Comment by gerritbruening** [comment]
http://dev.faustedition.net/print/faust.32#app.6832.willkommen

**Comment by dietmarpravida** [comment]
scheint mir jetzt okay
