### ISSUE TITLE
spacing before 5305 and in other places correct?

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#540]
![5305](https://user-images.githubusercontent.com/26788529/44116205-2f22acf8-a010-11e8-8825-840b8b3c2dc9.JPG)

**Comment by gerritbruening** [comment]
Du meinst, der Abstand sei asymmetrisch?
Scheint mir auch so.

**Comment by dietmarpravida** [comment]
@markusciupke Kuckst du dir das bitte mal an?

**Comment by dietmarpravida** [comment]
zu überprüfende Fälle:

- [ ] nach 7151 (sieht für mich okay aus)
- [ ] nach 7213 (dito)
- [ ] nach 7248 (dito)
- [ ] nach 7502 (?)
- [ ] nach 8326
- [ ] nach 8696
- [ ] nach 10322
- [ ] (nach 10931, am Seitenbeginn)
- [ ] nach 11078
- [ ] vor 11171 Auftritt
- [ ] (nach 11281 Auftritt, am Seitenende)
- [ ] (nach 12031 am Seitenbeginn)

**Comment by markusciupke** [comment]
Ich habe mir die Stellen angesehen. Tatsächlich müssen die ersten sieben Stellen um einen halben mm nach unten gerückt werden, dann sind sie mittig. Das habe ich jetzt bei 7151, 7213, 7248, 7502, 8326, 8696 und 10322 gemacht.
Die Stellen an Seitenbeginn (10931 und 12031 sind in Ordnung so wie sie sind.
Die anderen drei Stellen (11078, 11171 und 11281) haben nach oben einen viertelzeiligen Abstand (BA F 1,15). Das ist korrekt so, weil in der Zeile kein Auftritt bzw. keine Figur stehen. Die nächste Zeile folgt dann jeweils mit halbzeiligem Abstand. Hier muss also auch nichts geändert werden.
Insofern habe ich die letzten fünf Stellen abgehakt. Die anderen sieben Stellen prüft bitte zusammen mit den anderen Korrekturen in der nächsten Fahne.

**Comment by markusciupke** [comment]
nach 8423 ist auch noch eine BA C 2,3, die ich um einen 1/2 mm nach unten gerückt habe. Habe ich oben in die Liste eingefügt.

**Comment by dietmarpravida** [comment]
scheinen mir jetzt okay zu sein

**Comment by gerritbruening** [comment]
Sehr gut, danke!
