### ISSUE TITLE
Formulierung von 2d*

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#541]
I don't get it.

**Comment by gerritbruening** [comment]
Apostroph von Riemer (Fremdvariante)
von Goethe durchgewinkt ("autorisiert")
deswegen nicht emendiert, obwohl Fehler

Was ist unklar?

**Comment by dietmarpravida** [comment]
Mein Problem liegt wohl eher bei der Formulierung im EB, die mir nicht besonders durchsichgit zu sein scheint:

> Störungen durch vom Autor übernommene Fremdvarianten
(Eingriff unterbleibt, es kommen nur Angaben
der Form »(IId*)« vor; die Autorvariante wird
im Apparat verzeichnet)

**Comment by dietmarpravida** [comment]
lassen wir so
