### ISSUE TITLE
Ungleiche | in EB

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#543]
In der VIII-Liste sehen sie | (korrekt) aus, im Vergleich mit anderen Ausgaben nicht.

Das Problem ist von früher her bekannt, vgl. https://github.com/faustedition/faust-gen-html/issues/374#issuecomment-388966540 ff.

**Comment by markusciupke** [comment]
Was ist mit 
> im Vergleich mit anderen Ausgaben nicht

gemeint? Wo sieht der senkrechte Strich nicht korrekt aus? Bitte in der Fahne anzeichnen.

**Comment by dietmarpravida** [comment]
bin mir nicht sicher, @gerritbruening nennst du bitte ein konkretes Beispiel?

**Comment by gerritbruening** [comment]
Stellen sind jetzt angesrichen und an MC gesandt.
Link zum erwarteten Aussehen des Zeichens: https://github.com/faustedition/faust-gen-html/issues/374#issuecomment-388966540.

**Comment by markusciupke** [comment]
Habe ich bislang nicht bekommen. Bitte senden!

**Comment by gerritbruening** [comment]
Müsste bei @dietmarpravida liegen.

**Comment by dietmarpravida** [comment]
stehen auf Seite 488f. im EB

**Comment by markusciupke** [comment]
Verstehe. Das sind die Korrekturen im EB. Danke.

**Comment by dietmarpravida** [comment]
dürfte jetzt erledigt sein?

**Comment by markusciupke** [comment]
Ja. Siehe heute gesandte Fahne des EB. Die Striche sind jetzt jeder im EB vorkommenden Schriftgröße angepasst. Das waren sie vorher nicht. Da passten sie nur zur Schriftgröße des Apparats. Es gibt aber im EB auch noch die normale Größe 10 pt und Petit 9 pt.

**Comment by dietmarpravida** [comment]
@markusciupke gilt das für alle Vorkommnisse im Textband, auch im KT?

**Comment by markusciupke** [comment]
Im Textteil S. 1-480 können die nur im Apparat vorkommen, der eine 8 Pt-Schrift hat. Habe ich aber noch mal geprüft. Alle 7 sind in Ordnung.

**Comment by dietmarpravida** [comment]
danke!
