### ISSUE TITLE
before 8424

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#544]
> GALATEE auf dem Muschelwagen nähert sich

sollte man nicht setzen

> GALATEE auf dem Muschelwagen / nähert sich

?

So in II H.70, scheint mir eine Art Abschreibefehler Johns

**Comment by markusciupke** [comment]
Das finde ich gut. – Kann man das dann ohne Apparat-Eintrag machen?

**Comment by gerritbruening** [comment]
Ja, Zeilenwechsel einfügen.

**Comment by markusciupke** [comment]
Erledigt!

**Comment by gerritbruening** [comment]
Danke!
