### ISSUE TITLE
Punkte nach 11387 und in 11388 ergänzen

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#545]
Warum nicht mit V H.2 Punkt nach "Da werd ich zum Schatten" ergänzen?

**Comment by gerritbruening** [comment]
Sind doch schon da?
![grafik](https://user-images.githubusercontent.com/10358005/44492033-63bb6a00-a663-11e8-94ac-77b02951bce3.png)
Online auch angewiesen:
https://github.com/faustedition/faust-gen-html/commit/6b0eaf6006bff4352292aec18ee5e7629cb13bb0#diff-a48138172ec406b07f08b2d419608958R225.
Allein, https://github.com/faustedition/faust-gen-html/issues/582.
Ergänzung habe ich an @markusciupke geschickt.

**Comment by dietmarpravida** [comment]
das war ein rückwirkender Vermerk, quod non est in actis non est in mundo
