### ISSUE TITLE
WA III, 11, 23 - Einzelne Einträge für Gräf 1463a-c in Excel-Tabelle

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#55]
In der Excel-Tabelle gibt es nur einen Eintrag für Gräf 1463a-c.
Da in der xml-Datei aber graef1463a, graef1463b und graef1463c jeweils einzeln markiert werden,
müsste der Eintrag in der Excel-Tabelle auch aufgesplittet werden, um eine Zuordnung zu den jeweiligen IDs zu ermöglichen.

**Comment by gerritbruening** [comment]
@dietmarpravida, könnte das Frau Krause übernehmen?

**Comment by dietmarpravida** [comment]
Zeilen 1463a, 1463b, 1463 c eingeführt
