### ISSUE TITLE
Doppelter Eintrag zu Pniower 243 - WA IV, 19, 66 und WA IV, 19, 65

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#56]
In der Excel-Tabelle gibt es den Eintrag Pniower 243 zweimal.
Der erste Eintrag (Lfd. Nr. allerneuestens 332) bezieht sich auf einen Brief Goethes an Cotta und entspricht Gräf 1046.
Der zweite Eintrag (Lfd. Nr. allerneuestens 333) bezieht sich auf die Beilage zu diesem Brief. Diese wird meines Erachtens bei Pniower 243 nicht erwähnt. 
Hier sollte besser die QuZ-Nr. I-870a als Identifikator genommen werden. Hier ist das Zeugnis vollständig enthalten. Ich habe das Zeugnis in WA_IV-19.xml schon mal mit der QuZ-ID markiert.
Wahrscheinlich wäre es am besten, die Pniower-Nr. aus dieser Zeile zu entfernen?

**Comment by gerritbruening** [comment]
> Wahrscheinlich wäre es am besten, die Pniower-Nr. aus dieser Zeile zu entfernen?

Das ist technisch nicht nötig, @thvitt , oder? Denn die xml:id sollte das Matching zulassen.

@dietmarpravida , wahrscheinlich ist der Datensatz und mit ihr die Pniower-Nummer kopiert worden, obwohl sie sich nur auf den Brief und nicht auf die Beilage bezieht? Könnten wir hier nicht großzügig Verfahren und sowohl die Gräf- als auch die Pniower-Nr. auf die Einheit von Brief und Beilage beziehen => aus zwei mach ein Datensatz?

**Comment by thvitt** [comment]
Es wird immer die erste Nummer pro Tabellenzeile genommen, um die ID für das entsprechende Zeugnis zu bilden. D.h. die beiden Zeugnisse haben die IDs  [`graef_1046`](http://dev.faustedition.net/archive_testimonies#graef_1046) und [`pniower_243`](http://dev.faustedition.net/archive_testimonies#pniower_243).

**Comment by sandrakrause** [comment]
Die Pniower-Nr. habe ich nun aus 333 entfernt.
So haben wir auf jeden Fall erstmal eine Markierung, die beim Matching erkannt wird.
Falls die Datensätze zusammengeführt werden, kann die Markierung dann dementsprechend geändert werden.

**Comment by gerritbruening** [comment]
Können wir das Thema dann schließen?

**Comment by sandrakrause** [comment]
Ja, das ist dann geklärt, denke ich. Vielen Dank.
