### ISSUE TITLE
Schlussvermerke

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#563]
wie tel. mit DP besprochen
betrifft
- [x] Transkription
- [x] Text

**Comment by dietmarpravida** [comment]
NB Vorschlag von mc

**Comment by gerritbruening** [comment]
@dietmarpravida, schaust du den Entwurf im alten Google-Doc Erläuterungen zu H an?

**Comment by dietmarpravida** [comment]
sollte man die Arbeit an den Transkriptionsprinzipien im ersten Satz noch unterbringen? Herr Ritschel wird wohl in der Danksagung (ähnlich wie im Textband) genannt?

**Comment by gerritbruening** [comment]
Könnte man versuchen.
Die Danksagungen sind ja wohl identisch. Dann wird Herr Ritschel beidemale genannt.
