### ISSUE TITLE
Belege für Hör- und Abschreibefehler sammeln

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#564]
für abr-Nachwort, pronto!

**Comment by gerritbruening** [comment]
> Z.B. Typische Abschreibefehler z.B. ################## [soviel Platz wie bei der folgenden Fußnote freiassen!!]

So schreibt John "rasselts, klapperts" ab (H, S. 327, Vers 10766), obwohl die beiden Wörter in der Vorlage IV H.8 umgestellt sind, oder er schreibt "Offenbrauch" statt "Offenbarung"  (H, S. 378, Vers 11924), wo die Vorlage V H.33 etwas undeutlich ist.

**Comment by gerritbruening** [comment]
Wenn so recht, bitte als Ergänzung senden, oder @markusciupke sagen, er möge den Text von hier kopieren.

**Comment by gerritbruening** [comment]
(Hörfehler sind schon in Fn 11 genannt.)
