### ISSUE TITLE
Geminationsstrich über m in 6832

### ISSUE THREAD

**Issue by markusciupke** [faustedition/xml#567]
Der Strich steht in H über dem ersten m, nicht über dem zweiten, wie in der digitalen Edition und der gelieferten IDML-Datei.

**Comment by dietmarpravida** [comment]
stimmt

@gerritbruening an Herrn Renken schreiben?

**Comment by gerritbruening** [comment]
Danke für den Hinweis.
Bei DR ist, wie im dokumentarischen Transkript, alles richtig:
![grafik](https://user-images.githubusercontent.com/10358005/44290101-77d42580-a277-11e8-8289-ed2854c79f73.png)

Der Fehler stammt aus dem textuellen Transkript.

**Comment by dietmarpravida** [comment]
in Korrekturfahne für F-II eingefügt

**Comment by gerritbruening** [comment]
danke, online ist jetzt auch alles konsistent
