### ISSUE TITLE
lem range shorter than replace / ins string

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#568]
- [x] 8467 "und" would suffice as lemma, but `bald` is not sufficient as replacement string.
Instead, `8467[bald süße]{und süße}` is necessary.
I would like to keep the lemma short, but online and printed edition should be consistent.
- [x] Same applies to 3620
- [x] Same applies to 9971, were a word is added to the text.
- [x] We have a solution for Faust I's 359, but I do not see why this works.

**Comment by thvitt** [comment]
- 359: `<f:replace n="359">Und</f:replace><f:ins n="359">Und bin</f:ins>`. There is only one `Und` in 359, so the replacement is unambiguous
- 8467: two `bald`s that need to be distinguished
- 9971: We need something to replace …

If you think it is too confusing that the `<seg type="lem">` in the reading text is longer than the 'semantic' change, I could implement a postprocessing step that adjusts nested segs. In this case, you would still leave the extent of the f:ins/f:replace elements as is (to ensure they are not ambiguous), but you would mark the relevant part of the f:ins with a seg:

```xml
  <!--       9971[Hades]{Hades <seg>selbst</seg>} <i>9971</i> selbst <i>2_III_H.2:2</i>] <i>fehlt 2_III_H.3a:2 2_H C.1_4  [type=2b]</i>-->
  <app>
    <f:replace n="9971">Hades</f:replace>
    <f:ins n="9971">Hades <seg>selbst</seg></f:ins>
    <ref>9971</ref>
    <lem wit="2_III_H.2_2">selbst <note><wit>2_III_H.2_2</wit></note></lem>
    <rdg wit="2_III_H.3a_2 2_H C.1_4" type="type_2b"> <note>fehlt <wit>2_III_H.3a_2</wit> <wit>2_H</wit> <wit>C.1_4</wit></note></rdg>
  </app>
```
regular text-insert-app would encode this as 
```xml
<l n="9971">Auch im <seg type="lem" xml:id="seg.9971.hadesselbst">Hades <seg>selbst</seg></seg> stehen sie oben an[…]</l>
```
and cleanup could move the attributes to the inner seg and remove the outer one
```xml
<l n="9971">Auch im Hades <seg type="lem" xml:id="seg.9971.hadesselbst">selbst</seg> stehen sie oben an[…]</l>
```

**Comment by thvitt** [comment]
@gerritbruening if you want this, encode the `f:ins` with `<seg>` as indicated above and reassign me, otherwise close.

**Comment by gerritbruening** [comment]
Thanks, I have added all the `seg` elements!

**Comment by thvitt** [comment]
faustedition/faust-gen-html@5b9aad806f2e9b0b02f42017050c3ff7834c80a6
wrong issue comment :(
