### ISSUE TITLE
Worttrennungen 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#573]
> müssen alle nochmal geprüft werden

**Comment by dietmarpravida** [comment]
- TTF 14
- TTF 34
- App 6199 Gespenst-Gespinnsten, schwierig, aber unvermeidlich

Das sind anscheinend die einzigen Fälle im konstituierten Text & Apparat (soweit nicht im Verstext)

**Comment by dietmarpravida** [comment]
nein, man kann die pdf leider nicht auf Trennungen durchsuchen

**Comment by dietmarpravida** [comment]
vielleicht problematisch im EB des Textbandes:
- S. 492 Fehler **au-tornah** (@markusciupke Änderung möglich?)
- S. 500 zweiter Absatz: etwas viele Trennungen kurz aufeinander, aaber nicht schlimm, da vereinzelter Fall
- S. 511 etwas viele Trennungen, aber wohl unvermeidlich so
- S. 512 3. Z.v.u. Fehler **das-**
- 5. 524 erster Absatz: vier Trennungen nacheinander
- S. 532 Fehler **Furi-en** (ändern zu "Fu-rien")
- S. 539 **pos-tum**, wenn möglich Trennung dieses Wortes vermeiden

sonst scheint mir alles okay

**Comment by dietmarpravida** [comment]
off topic, aber da du, @markusciupke , das hier hoffentlich liest, erwähne ich noch die fälschlich kursive schließende Klammer auf Seite 527 nach "**Felsenspalte?**" sowie den fälschlich kursiven **Faust** auf Seite 498, Z. 1

**Comment by markusciupke** [comment]
Jetzt habe ich gerade die neu abgespeicherten PDFs losgeschickt. Das schaue ich mir morgen an. Es kommt sicher noch mehr dazu.

**Comment by markusciupke** [comment]
492 war 493 --> ist korrigiert
498 ist korrigiert
500 halte ich für die beste Lösung --> so lassen
511 II c Au-torvarianten ließe sich nur auch Umformulierung vermeiden.
512 ist korrigert
NEU: 517, 1. Zeile zu weit. Kann nur durch Umformulierung behoben werden.
524 halte ich für die beste Lösung --> so lassen
527 ist korrigiert
532 ist korrigiert
539 ist korrigiert

**Comment by dietmarpravida** [comment]
> 500 halte ich für die beste Lösung --> so lassen

okay

> 511 II c Au-torvarianten ließe sich nur auch Umformulierung vermeiden.

da vereinzelt, vielleicht ertragbar

> 524 halte ich für die beste Lösung --> so lassen

okay

**Comment by dietmarpravida** [comment]
Ich lasse den Issue für allfällige weitere Vorkommnisse noch offen

**Comment by markusciupke** [comment]
S. 31: zusätzlich gemachte Korrekturen: S --> kursiv; 2 LZ vor »lang’«; 2 LZ vor »lang«
S. 293/294: so besser? – Ich finde ja?
S. 348: zusätzlich gemachte Korrektur: 2 LZ vor »und _G_«
S. 364: so besser? – Ich bin unsicher.
S. 466: ja!

**Comment by dietmarpravida** [comment]
293/94 ja, besser
364 ja!

**Comment by dietmarpravida** [comment]
> 517, 1. Zeile zu weit. Kann nur durch Umformulierung behoben werden.

ganz einfach: `(z.B. "Meph.")`, steht bereits in der kommenden Fahnenkorrektur

**Comment by gerritbruening** [comment]
> S. 293/294: so besser? – Ich finde ja?

Gibt es hier Worttrennungen? Oder ging es um die Antilabe?

> S. 348: zusätzlich gemachte Korrektur: 2 LZ vor »und G«

danke

> S. 364: so besser? – Ich bin unsicher.

Worttrennungen?
HELENA und CHOR / stehen finde ich noch zu tannenbaumig.

> S. 466: ja!
@dietmarpravida

Was ist / war hier los?

**Comment by markusciupke** [comment]
S. 293/294 ging es um die Antilabe. Vers 6922 ist auf S. 294 gerutscht.

S. 364 Worttrennungen in zentrierten BAs möchte ich bitte nicht. Eine besser Aufteilung habe ich nicht.

S. 466 Ich bin nicht sicher. Vielleicht: @dietmarpravida fragte ob der Abstand von Glorie nach oben kleiner ist als nach unten. Und ich sagte: ja!
