### ISSUE TITLE
7534 Kreißenden

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#574]
Kreisenden C.1 C.3 Q, oder etwa nicht? Weil im App jetzt gegenteiliges behauptet.
Google-Doc:

> App 7534 
DP (09-08): emend Erich Schmidt] emend C3 Q Erich Schmidt
DP (09-08): “Kreisenden C1” ergänzen

**Comment by dietmarpravida** [comment]
stimmt

**Comment by gerritbruening** [comment]
closen?

**Comment by gerritbruening** [comment]
Ach so, ist ja schon.
