### ISSUE TITLE
check runnning titles in F-I & F-II

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#576]
@gerritbruening generate list

**Comment by dietmarpravida** [comment]
Faust I durchgesehen, Faust II anscheinend auch (siehe #577)

**Comment by gerritbruening** [comment]
Ja, Faust II ist durchgesehen.

**Comment by dietmarpravida** [comment]
Blieben jetzt noch die Kolumnentitel im EB: Ich würde sagen links "Editorischer Bericht", rechts "Zusätzliche Lesarten", "Zur Textkonstitution" etc. Oder wollen wir die Untertitel von "Zur Textkonstitution" haben? Wenn doch, dann vielleicht nicht, wie jetzt, mitsamt der römschen Ziffern, oder?

**Comment by dietmarpravida** [comment]
TK und EB_Transkr geprüft, Transkr lag mir nicht vor
