### ISSUE TITLE
check verse groupings in F-I & F-II

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#578]
@gerritbruening provide list

**Comment by gerritbruening** [comment]
[versgruppen.docx](https://github.com/faustedition/xml/files/2317668/versgruppen.docx)

**Comment by dietmarpravida** [comment]
- [ ] - 5096 Seitenwechsel, kein Einzug: kein Einzug nötig
- [ ] - 5415 Seitenwechsel, kein Einzug: kein Einzug nötig
- [ ] - 5279  Seitenwechsel, kein Einzug, danach Vierzeiler: hier wäre ein Einzug sicherheitshalber denkbar
- [ ] - 5848 Seitenwechsel, kein Einzug: Einzug wäre angebracht
- [ ] - 5944 Seitenwechsel, mit Einzug: korrekt
- [ ] - (6717 Seitenwechsel, keine Versgruppe, obwohl eine zu erwarten wäre; Erich Schmidt greift hier ein, wir nicht)
- [ ] - 7034 Seitenwechsel, kein Einzug:  Einzug wäre angebracht
- [ ] - 8707 Seitenwechsel mit Einzug: nicht unbedingt nötig, aber auch nicht überfüssig
- [ ] - 8903 Seitenwechsel mit Einzug: korrekt
- [ ] - 9800 Schusterjunge, wohl unvermeidlich
- [ ] - 9831 Seitenwechsel, kein Einzug: hier ist nach unserem Verfahren nicht erkennbar, ob eine acht- oder zwei vierzeilige Versgruppen vorliegen (es ist achtzeilig, beginnend mit 9827); lässt sich mit unseren Mitteln wohl nicht lösen

**Comment by gerritbruening** [comment]
Danke!
Rückfrage: Was bedeutet es, dass die Häkchen fehlen? Soll ich schauen, ob noch Korrekturen nötig sind?

**Comment by dietmarpravida** [comment]
ich habe gesagt, was ich dazu denke. Wenn du zustimmst, bitte abhaken oder, wenn es kein ja/nein-Fall ist, Alternative angeben, ich trage es dann in die Korrektur ein

**Comment by dietmarpravida** [comment]
gb wrote https://github.com/faustedition/xml/issues/579#issuecomment-415907542:

> Am Seitenbeginn 461 scheint mir ein Erstzeileneinzug nötig, weil sonst nicht trivial ist, dass es sich um zwei Strophen handelt. Oder hast du das schon angewiesen?
Sonst sehe ich (beim nächsten Seitenumbruch) keine Probleme. Warum der Plural?

**Comment by dietmarpravida** [comment]
versuchs, andernfalls eben Einzug

**Comment by gerritbruening** [comment]
Meine Meinung:

* 5279 scheint mir kein Einzug nötig (vorhergehende Strophen eindeutig)
* 8707 dito
* 8903 dito
* 9831 wirkt nur auf den ersten Blick zweistrophig, vgl. 9827 mit 9831

Korrekturen habe ich angewiesen.

**Comment by gerritbruening** [comment]
> > 5848: warum nicht einfach Einzug?

> weil’s unschön ist (nach meinem Geschmack). Ich habe beim Satz versucht, es zu vermeiden. Ging nicht immer. Hier könnte es gehen, denke ich. Hab’s noch nicht versucht. Was meinst du @gerritbruening ?

Da die Versgruppe auf neuer Seite beginnt, halte ich einen Einzug für unumgänglich.
