### ISSUE TITLE
check page breaks in act 5, p. 460 "Großer Vorhof" etc.

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#579]

**Comment by gerritbruening** [comment]
Am Seitenbeginn 461 scheint mir ein Erstzeileneinzug nötig, weil sonst nicht trivial ist, dass es sich um zwei Strophen handelt. Oder hast du das schon angewiesen?
Sonst sehe ich (beim nächsten Seitenumbruch) keine Probleme. Warum der Plural?

**Comment by dietmarpravida** [comment]
> Warum der Plural?

ich dachte, man müsse bei allen vergleichbaren Unterszenen im fünten Akt prüfen, ob die mit ener neuen Seite beginnen sollen oder nicht. War nur eine Idee.

**Comment by gerritbruening** [comment]
Scheinen mir "Stand jetzt" alle in Ordnung.
