### ISSUE TITLE
Zensurstriche im Satz

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#580]
1821:

![1820](https://user-images.githubusercontent.com/26788529/44604741-31d31080-a7e7-11e8-8f57-1fb07046e5be.JPG)

Wie findest du denn die Abstände bei "H - -"?

**Comment by dietmarpravida** [comment]
Unproblematischer wohl 4138ff:

![4138ff](https://user-images.githubusercontent.com/26788529/44604967-f553e480-a7e7-11e8-9f0b-c342d7de0698.JPG)

**Comment by markusciupke** [comment]
Was schlagt ihr vor? Es sind ganz normale Leerzeichen zwischen den Halbgeviertstrichen. Das Semikolon folgt ebenfalls ganz normal.

**Comment by dietmarpravida** [comment]
ich frage nur, ob das für euch okay so aussieht, ich bin derzeit unsicher

**Comment by dietmarpravida** [comment]
10397

![10397](https://user-images.githubusercontent.com/26788529/44605375-592add00-a7e9-11e8-9855-40aa1c944319.JPG)

**Comment by markusciupke** [comment]
Für mich ist es so in Ordnung. Allenfalls würde ich vielleicht  das Semikolon eine Winzigkeit vom Halbgeviertstrich wegrücken. Muss aber nicht sein.

**Comment by dietmarpravida** [comment]
ja, doch, fände ich gut

Bei H-- hätte ich gern, dass die Worteinheit erkennbar ist, dass also die Striche und ds H näher beieinder sind als der Abstand des letzten Strichs zum d von "dein". Aber vielleicht ist das Quatsch.

**Comment by dietmarpravida** [comment]
A propos, es bleibt doch schade, dass wir hier nicht Karl Marx' Beitrag zur konjekturalen Faustphilologie  zitieren

**Comment by gerritbruening** [comment]
Ich fühle mich hier unzuständig, würde aber keine Notwendigkeit sehen, eine Differenzierung einzuführen, die in A nicht vorhanden ist. Wäre das nicht horribile dictu "Interpretation"?

**Comment by gerritbruening** [comment]
Nur schade, dass der Vers 11397 nicht umgebrochen wird, so bin ich es gewohnt, und ohne Umbruch finde ich den Vers fast komisch.

**Comment by markusciupke** [comment]
> Ich fühle mich hier unzuständig, würde aber keine Notwendigkeit sehen, eine Differenzierung einzuführen, die in A nicht vorhanden ist. Wäre das nicht horribile dictu "Interpretation"?

Da hat GB auch recht. 
@dietmarpravida: Soll ich die Abstände in 1821 wieder normalisieren?

**Comment by dietmarpravida** [comment]
Ich für mein Teil ediere nicht A, und Interpretation ist ein Papiertiger. Im letzten Durchlauf 2018-08-24 hat sich bei 1821 noch nichts getan, oder sehe ich nur nicht recht?

4138 hat jetzt sehr gewonnen

**Comment by markusciupke** [comment]
Doch du siehst recht. Die Korrektur habe ich erst heute morgen vorgenommen und noch nicht gesendet. Hier ist sie:
[75 enger.pdf](https://github.com/faustedition/xml/files/2320837/75.enger.pdf)

4138 kannst du auch noch nicht gesehen haben. Das Semikolon habe ich erst heute morgen abgerückt. Hier ist es:
[138 neu.pdf](https://github.com/faustedition/xml/files/2320838/138.neu.pdf)

Bitte entscheiden!

**Comment by dietmarpravida** [comment]
138 neu ist nicht die richtige Seite, sondern nochmal 75, schickst du es mir bitte nochmal? 


Von: "markusciupke" <notifications@github.com> 
An: "faustedition/xml" <xml@noreply.github.com> 
CC: "dietmarpravida" <dpravida@goethehaus-frankfurt.de>, "Mention" <mention@noreply.github.com> 
Gesendet: Samstag, 25. August 2018 17:48:32 
Betreff: Re: [faustedition/xml] Zensurstriche im Satz (#580) 



Doch du siehst recht. Die Korrektur habe ich erst heute morgen vorgenommen und noch nicht gesendet. Hier ist sie: 
75 enger.pdf 


4138 kannst du auch noch nicht gesehen haben. Das Semikolon habe ich erst heute morgen abgerückt. Hier ist es: 
138 neu.pdf 


Bitte entscheiden!

**Comment by markusciupke** [comment]
Entschuldigung. Seite 182 (!) also:
[182.pdf](https://github.com/faustedition/xml/files/2320872/182.pdf)

**Comment by dietmarpravida** [comment]
ich kann da keinen Unterschied erkennen, liegt es an mir, an der Tageszeit?

**Comment by markusciupke** [comment]
Ich weiß auch nicht. War es doch schon gestern abgerückt? Ich habe noch mal ohne Abstand abgespeichert. Aber in ID sieht mans tatsächlich besser als im PDF. Hier ist es noch mal ohne:
[182 alt.pdf](https://github.com/faustedition/xml/files/2320879/182.alt.pdf)

Aber lass uns nicht zu viel Zeit darauf verwenden.

**Comment by dietmarpravida** [comment]
> Aber lass uns nicht zu viel Zeit darauf verwenden.

*zustimm*

**Comment by markusciupke** [comment]
Auch auf S. 75?

**Comment by dietmarpravida** [comment]
ja, bitte

**Comment by markusciupke** [comment]
Das schließe ich hiermit.
