### ISSUE TITLE
Unterszenen in der Klassischen Walpurgisnacht

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#581]
Scheint mir jetzt sehr mickrig, obwohl ursprünglich BA und nicht ausdrücklich zur Überschrift erhoben.

![grafik](https://user-images.githubusercontent.com/10358005/44612176-7f12aa80-a806-11e8-8383-a4eb318f0080.png)

Hast du dazu eine Meinung?

**Comment by dietmarpravida** [comment]
Naja, Innerer Burghof z.B. ist ja auch nicht gerade spektakulär (wenngleich an einem Seitenbeginn). Problematisch ist es aber wegen der BA direkt davor und dem ERDBEBEN danach. Abstand einfügen und 7514 auf die Folgeseite ziehen, wenn das geht?

**Comment by gerritbruening** [comment]
Abstand davor scheint mir gut, den würde ich dann analog auch vor
> TELCHINEN von RHODUS

haben wollen, wie in H angewiesen.

**Comment by dietmarpravida** [comment]
Wenn man Vers 8292 von Seite 341 nach 342 zieht, dürfte sich bis Seite 346 alles ausgleichen, nur auf Seite 344 wäre ein Schusterjunge in Kauf zu nehmen (womit ich keine Probleme habe).

Bei Seite 314 muss man nur mit dem letzten Vers 7514 bis an den unteren Seitenrand gehen, denn anscheinend ist dort noch eine Zeile Luft (muss dann auf der nächsten Seite ein Einzug hin?). Vers 7514 dürfte wohl gar nicht geschoben werden, oder?

**Comment by gerritbruening** [comment]
Gut, dann wäre wohl @markusciupke zurate zu ziehen.

**Comment by markusciupke** [comment]
Beide Male ist die Einfügung einer halben Leerzeile problemlos möglich. Eine Verschiebung von Versen ist bei beiden Stellen nicht nötig.
[314:341.pdf](https://github.com/faustedition/xml/files/2321437/314.341.pdf)

Wieso sollte bei 7415 ein Einzug hin. In H sehe ich keinen.

**Comment by gerritbruening** [comment]
Ausgangspunkt wäre aus meiner Sicht eigentlich der Abstand vor einer Unterszenenüberschrift.

**Comment by markusciupke** [comment]
Was meinst du damit?

**Comment by gerritbruening** [comment]
(Im dritten Akt bleibt alles wie es ist.)

**Comment by gerritbruening** [comment]
Ich meinte, es hätte eine gewisse Logik, vor den beiden betreffenden BA denselben Abstand wie vor Unterscenenüberschriften einzufügen.

**Comment by markusciupke** [comment]
Der Abstand wird durch das darüberstehende Textelement definiert. Ist es ein Vers, sind es 2,5 LZ (Unterszene). Ist es ein Szenentitel, sind es 1,5 LZ (Unterszene nach Szene. Was ich euch oben geschickt habe, war 1 LZ.
Ich schicke euch nun beides. Mit 1,5 LZ bekommen wir im folgenden keine Umbruchsprobleme, mit 2,5 wird es schwieriger. Bitte entscheidet.
[314:341 1,5 LZ.pdf](https://github.com/faustedition/xml/files/2321695/314.341.1.5.LZ.pdf)
[314:341 2,5 LZ.pdf](https://github.com/faustedition/xml/files/2321696/314.341.2.5.LZ.pdf)

**Comment by dietmarpravida** [comment]
1,5 bitte, sieht für mich okay aus und erfüllt seinen Zweck

**Comment by dietmarpravida** [comment]
äh verstehe, vielleicht sollte ich mich jetzt gerade hier gar nicht äußern

**Comment by gerritbruening** [comment]
Why not?

**Comment by gerritbruening** [comment]
(ebenfalls Teil von https://github.com/faustedition/faust-gen-html/issues/331)

**Comment by gerritbruening** [comment]
ABR und SH sich haben ebenfalls für 1,5 Leerzeilen Abstand ausgesprochen. Dann würde ich sagen, wir machen das so.

**Comment by markusciupke** [comment]
Bei Peneus und Telchinen: 1, 5 LZ nach oben. Hab ich so gemacht.

**Comment by gerritbruening** [comment]
Danke! Ich lasse es noch open, bis die neue Version da ist.

**Comment by gerritbruening** [comment]
Der dritte im Bunde wäre noch analog zu behandeln:
> PENEUS umgeben von Gewässern und NYMPHEN

(S. 305)
Ich fürchte, das ist nicht zu unangenehm wegen der Verschiebung auf die nächste Seite.

**Comment by markusciupke** [comment]
Das würde tatsächlich eine Umbruchsverschiebung für die folgenden Seiten bedeuten. Vermutlich bis S. 248, und dann dürfte die auf keinen Fall »überlaufen«. Soll ich es ausprobieren?

**Comment by gerritbruening** [comment]
Ja, bitte!
Danke im Voraus. Ich konnte die Dinge nur nacheinander abarbeiten und bin dieses Issue etwas zu spät angegangen.

**Comment by markusciupke** [comment]
Hier kommen zwei Versuche: Ein einfacher, bei dem sich die Änderung nur auf S. 305 selbst findet (KT 299-331 neu 1) und ein aufwendiger, bei dem sich die Umbruchsverschiebung von S. 299-331 zieht. Ich habe beidemale die Seiten 299-331 komplett abgespeichert, so dass ihr besser vergleichen könnt.
Neu 2 hat durchaus auch was für sich. Aber ihr müsst entscheiden. Auf jeden Fall müsst ihr bitte bald entscheiden, weil ich sonst nicht weiterarbeiten kann (ich muss ja wissen in welcher Version ich weiter korrigiere).

**Comment by gerritbruening** [comment]
An der ersten Version gefällt mir der Vorsprung von fast einer halben Seite (S. 318). Könnte dieser Vorsprung nicht dazu genutzt werden, die Abstände zwischen den Unterszenen etwas größer zu machen? Jetzt sind sie doch extrem klein.

**Comment by markusciupke** [comment]
Das ist mir jetzt in dieser Phase etwas viel hin und her. 
Zumal:
> ABR und SH sich haben ebenfalls für 1,5 Leerzeilen Abstand ausgesprochen. Dann würde ich sagen, wir machen das so.

So habe ich es gemacht. – Aber ich kann auch 2, 2,5 oder 3 LZ ausprobieren. Aber nur eins davon. Welche Variante soll es sein?

**Comment by gerritbruening** [comment]
Wie ich oben schon schrieb:
> Wenn die Folgewirkungen bis zum nächsten Vorkommnis dieser Art reicht, wäre zu überlegen, dann auch einen größeren Abstand zu nehmen. Der jetzige (1,5) ist sehr klein, das absolute Minimum gemessen am sonstigen Abstand vor Unterszenenüberschriften.

Könntest du 2 LZ probieren?

**Comment by gerritbruening** [comment]
- [x] 306 Pene
- [x] 314 Am ob
- [x] (332) Überschrift Felsbuchten
- [x] 341 Telch
