### ISSUE TITLE
vor 6377 Dämmernde Beleuchtung: Abstand nach unten

### ISSUE THREAD

**Issue by markusciupke** [faustedition/xml#583]
Ich habe mir alle »Unterszenenunter« angesehen, weil da die Formatierungen in IDML nicht korrekt mitgekommen waren. Dabei ist mir aufgefallen, dass ich »Dämmernde Beleuchtung« als einziger eine ganze LZ Abstand nach untern gegeben habe (S. 272). Den parallelen Fällen auf S. 211, 215, 256, 269, 332 und 460 aber eine halbe LZ. Ich schlage vor, das auch bei »Dämmernde Beleuchtung« so zu machen. Einverstanden?
[Unterszenenunter.pdf](https://github.com/faustedition/xml/files/2321450/Unterszenenunter.pdf)

**Comment by gerritbruening** [comment]
Teil von https://github.com/faustedition/faust-gen-html/issues/331.

**Comment by dietmarpravida** [comment]
Markus' Vorschlag scheint mir richtig

**Comment by gerritbruening** [comment]
Ich fürchte, ich tendiere zum Gegenteil, d.h. so wie hier sollte jede Unterszenen-Unterüberschrift einen überschrifts-mäßigen Abstand nach unten haben. Muss morgen mal meine diesbezüglichen Korrekturen durchgehen.

**Comment by dietmarpravida** [comment]
Sind dieser Issue und #581 eigentlich verschieden oder zusammengehörig? (sorry, kann mich diesem Them hier gerade nicht uneingeschränkt widmen; im Zweifelsfall meine Meinungen ignorieren)

**Comment by markusciupke** [comment]
> Ich fürchte, ich tendiere zum Gegenteil

Dann warte ich das weitere erstmal ab. Der größere Abstand müsste nach meiner Einschätzung überall einigermaßen gut einzurichten sein.

**Comment by gerritbruening** [comment]
Habe Korrekturen zu dieser und zu den anderen Überschriften geschickt, lasst uns das im Rahmen von https://github.com/faustedition/faust-gen-html/issues/331 weiterdiskutieren.
