### ISSUE TITLE
Absenkungen auf den Seiten 226 und 269

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#586]
könnten evtl. entfallen.
Ich finde das eigentlich doch nicht zwingend nötig, denn nicht die Absenkung, sondern die Schriftgröße der Überschrift selbst sagt aus, auf welcher Hierarchie-Ebene die Überschrift steht.

**Comment by gerritbruening** [comment]
Ich habe keine klare Meinung. Du, @dietmarpravida?

**Comment by gerritbruening** [comment]
ganz oben
> könnten evtl. entfallen.
Ich finde das eigentlich doch nicht zwingend nötig

(Das Entfallenlassen finde ich nicht zwingend nötig, aus dem im folgenden genannten Grund.)

**Comment by markusciupke** [comment]
> ganz oben
könnten evtl. entfallen.
Ich finde das eigentlich doch nicht zwingend nötig
(Das Entfallenlassen finde ich nicht zwingend nötig, aus dem im folgenden genannten Grund.)

Das ist mir jetzt zu kryptisch. Ist das Entfallen der Absenkungen nicht zwingend nötig? Sollen also die Absenkungen wieder gemacht werden?

**Comment by gerritbruening** [comment]
Ja, das Entfallen der Absenkungen ist nicht zwingend nötig.
(Sie selbst allerdings auch nicht.) 
Meine Tendenz: Lassen wir es so es ist (war), d.h. mit Absenkung.

**Comment by markusciupke** [comment]
Schön, dass du deinen Humor behältst.
