### ISSUE TITLE
Merkwürdige Einrückungsunterschiede 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#590]
![grafik](https://user-images.githubusercontent.com/10358005/44753164-70393a00-ab1d-11e8-8c76-3eea744a94bc.png)

Liebe @sandrakrause, auf dieser Doppelseite sehen zwei seltsame Einrückungsunterschiede:
* "Zeigt sich eine Felsenritze"
* "An jenem Weiher" 

(Der Punkt ist, der Einrückungsunterschied tritt **innerhalb einer Versgruppe auf**. Verschiedene Versgruppen können unterschiedlich eingerückt sein. Das wäre kein Fehler.
Könnten Sie anhand der neuesten Satzdatei nach weiteren solcher Fälle Ausschau halten? Dann würde ich die Ihnen schicken.
(@markusciupke, wie erklärst du dir das? gibt es eine Möglichkeit, das systematisch zu suchen?)

**Comment by markusciupke** [comment]
Das ist in dem Bereich, in dem ich den Umbruch geändert habe (Klassische Walpurgisnacht). Ich habe die Einrückungen seitenweise auf optische Mitte gestellt, so dass bei Seitenwechsel einer eingerückten Passage (hier wohl zwischen 7611/7612 sowie 7645/7646) ein solcher Sprung zustande kommt, der aber wegen des Seitenwechsels nicht sichtbar, sondern nur messbar ist. Wichtig ist mir die optische Zentrierung, auch im Zusammenhang mit den vorangehenden oder folgenden Versgruppen. Tatsächlich muss das jetzt noch mal genau kontrolliert und behoben werden. Das mache ich morgen.

**Comment by dietmarpravida** [comment]
soweit erledigt; einige verbleibende Einrückungen im Druck scheinen mir trotzdem recht zweifelhaft, da müssen wir allfällige Kritik dann wohl einfach auf uns nehmen, wie sie zustandekamen, kann man ja niemand erzählen.
