### ISSUE TITLE
Schema or conversion adjustments

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#596]
The TEI 3.4 based schema still seems to need some adjustments for errors present in the validation. See also #595 for stuff that probably needs decisions first.

* [x] `<date>` as part of the content model for `<line>` seems to be used quite often
* [x] `<num>` as part of the content model for `<line>` is used 58×
* [x] nested `<change>`, this probably needs some encoding using nested `<listChange>`
* [x] `listTranspose` is currently mostly found in `creation`, it needs to be moved to `profileDesc`
* [x] `unit` and `quantity` attributes for `<f:grLine>`
* [x] `<supplied>` needs `source` attribute for `<supplied evidence="external" source="391098">`
* [x] `<alt targets="#foo #bar #baz"/>` is not allowed?

**Comment by thvitt** [comment]
The original sources sometimes contain nested `<ge:stage>`, e.g. this example from 391404.xml:

```xml
                <ge:stageNotes>
                    <ge:stageNote type="bondedVar" xml:id="verb_l_5914ff">metrisch <ge:stageNote
                            type="bondedVar" xml:id="verb_l_5915">syntaktisch</ge:stageNote>
                    </ge:stageNote>
                    <ge:stageNote type="bondedVar" xml:id="verb_l_5918f">metrisch</ge:stageNote>
                    <ge:stageNote type="bondedVar" xml:id="verb_l_5909"/>
                    <ge:stageNote type="bondedVar" xml:id="verb_l_5809"/>
                    <ge:stageNote type="bondedVar" xml:id="verb_l_5422f"/>
                    <ge:stageNote type="vorgang" xml:id="vorg_l_5922f"/>
                </ge:stageNotes>
```

In TEI P5 3.4.0, the equivalent to `ge:stage`, `<change>` may contain neither `<change>` nor `<listChange>`, so this cannot be directly converted. I do not really understand the semantics here. Additionally, mixing text content (“metrisch”) with nested elements seems problematic here to me.

Is the nesting semantically relevant here? If so, do you have an idea on how to express that in TEI P5 3.4.0?

**Comment by gerritbruening** [comment]
Provisional solution could be:
```xml
            <listChange>
               <change type="bondedVar" xml:id="verb_l_5914ff">metrisch <listEvent>
                     <event type="bondedVar" xml:id="verb_l_5915">
                        <p>syntaktisch</p>
                     </event>
                  </listEvent>
               </change>
            </listChange>
```

I would try to preserve the containment relation because one change is part of the other. Mixed content seems to be built in in `change`.

**Comment by gerritbruening** [comment]
Still open?

**Comment by thvitt** [comment]
please check what I’ve done (in 2 H, e.g.) and close if it’s acceptable. I’ve not implemented the `event` solution since it makes processing harder

**Comment by gerritbruening** [comment]
OK, looks good.
Only this one is invalid:
```xml
               <change xml:id="verband_l_5807-10">metrisch 
               <listChange><change xml:id="verband_l_5808">syntaktisch</change></listChange></change>
```
(`change/listChange`)

**Comment by gerritbruening** [comment]
Which is https://github.com/faustedition/faust-schema/issues/7.
