### ISSUE TITLE
Some new a, b, c idnos imply chronological order

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#600]
@dietmarpravida, die Siglierung neuer Handschriften war öfters chrononologisch.
Kann man das so formulieren (als `temp-pre` Relation kraft `self`, dass @thvitt das weiterverarbeiten kann? Würde vorschlagen, ihr klärt das bilateral.

**Comment by dietmarpravida** [comment]
meines Wissens ist die immer chronologisch, wo identische Verszahlintervallanfänge vorliegen

**Comment by dietmarpravida** [comment]
@thvitt ich habe eine ganze Datei mit chronologischen Relationen, wie wird die am besten in xml überführt?

**Comment by thvitt** [comment]
zeig mal

**Comment by dietmarpravida** [comment]
Sobald #609 und #613 gelöst sind, könnten wir das umsetzen. (In beiliegender Datei sind die Siglen aber noch die alten!)

[Reihenfolge.xlsx](https://github.com/faustedition/xml/files/2383376/Reihenfolge.xlsx)

**Comment by dietmarpravida** [comment]
[Reihenfolge_Siglen geändert.xlsx](https://github.com/faustedition/xml/files/2398685/Reihenfolge_Siglen.geandert.xlsx)

let's go

**Comment by thvitt** [comment]
Hier:

Faustedition-Sigle / --- | Quelle (leer = faust://self) / Relation (leer = temp-pre) | Kommentar für Relation zu voriger Sigle / Kommentar für Gruppe (ggf. leer) | weitere Anmerkungen ()
-- | -- | -- | --
--- |   |   |  
2 I H.8 |   | Bleistiftentwurf |  
2 I H.9 |   | eigh. Reinschrift | 08-12-1827

was soll denn mit dem Kommentar 'Bleistiftentwurf' passieren? Die Kommentare beziehen sich ja immer auf eine Relation, d.h.

```xml
<relation type="temp-pre">
   <item uri="faust://document/faustedition/2_I_H.8"/>
   <item uri="faust://document/faustedition/2_I_H.9"/>
   <source uri="faust://self"/>
   <comment>eigh. Reinschrift</comment>
</relation>
```

**Comment by thvitt** [comment]
>25-12-1827
>28.12.1827
och menno, ich hab extra datumsfelder mit isoformat draus gemacht damit ich nicht selber durcheinandere Stringrepräsentationen parsen muss

**Comment by thvitt** [comment]
die konvertierten Daten liegen jetzt in der Datei `macrogenesis/issue600.xml` im Makrogeneseordner. Alle weiteren Änderungen bitte direkt dort vornehmen! Die Datei darf auch gern umbenannt werden …

**Comment by dietmarpravida** [comment]
> was soll denn mit dem Kommentar 'Bleistiftentwurf' passieren

muss ich nachbearbeiten

**Comment by gerritbruening** [comment]
Dateien liegen jetzt in `xml/macrogenesis/self/`

Ich bin noch auf das hier gestoßen:
`<!--Could not convert Pandas(Index=7, sigil='2 I H.9f', source='', comment='', notBefore='', notAfter='', _6='', to='', when='', notes='')-->`

**Comment by gerritbruening** [comment]
OK

**Comment by gerritbruening** [comment]
@dietmarpravida, die Daten sind jetzt in XML verteilt und nachbearbeitet, evtle Ergänzungen oder Korrekturen also besser direkt an mich.
