### ISSUE TITLE
Mapping-Probleme bei Landeck

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#603]
Folgende URIs verweisen auf Landeck-Siglen, bei denen ein Mapping-Problem besteht:
(Die Siglen tauchen auf der Liste aller verwendeten Siglen bei Landeck nicht auf, müssen vermutlich ergänzt werden)

- [x] faust://document/landeck/2_H |  Landeck S. 88-89
- [x] faust://document/landeck/2_V_H.1I |  Landeck: S. 95
- [x] faust://document/landeck/2_V_H.1II | S.102
- [x] faust://document/landeck/2_V_H.1III | S. 111
- [x] faust://document/landeck/2_V_H.2 | S. 60f.
- [x] faust://document/landeck/2_V_H.33I | S. 210
- [x] faust://document/landeck/2_V_H.g33 | S. 210
- [x] faust://document/landeck/2_V_H.gI | S. 205
- [x] faust://document/landeck/2_V_H.gII | S. 205
- [x] faust://document/landeck/2_V_H.h | S. 210

**Comment by dietmarpravida** [comment]
landeck/2_V_H.1I = V H.1, Bl. 1-3  (Palast), datiert -4. Mai 1831
landeck/2_V_H.1II = V H.1, Bl. 4-6r (Tiefe Nacht), datiert April-Anfang Mai 1831
landeck/2_V_H.1III = V H.1, Bl. 6v (Mitternacht), datiert April-Anfang Mai 1831

Da Landeck keine verschiedenen Datierungen vorschlägt, besteht hier letztlich kein großes Problem

**Comment by dietmarpravida** [comment]
landeck/2_V_H.g33 muss ein Fehler sein, bei Landeck ist auf Seite 210 nur von H.gI und H.gII die Rede; @sandrakrause was für ein Datum gibt er denn an?

**Comment by dietmarpravida** [comment]
landeck/2_V_H.gI = 2 V H.37e
landeck/2_V_H.gII = 2 V H.37f

**Comment by dietmarpravida** [comment]
landeck/2_V_H.h = 2 V H.37g (Landeck spricht S. 207 aber von einer "alten Phortographie"? unsere Metaadaten sind hier etwas kryptisch)

**Comment by dietmarpravida** [comment]
Landeck , S. 88f. ist von landeck/2_V_H.**i** (= 2 V H. .0a) die Rede, nicht von landeck/2_V_**H**; Tippfehler in der Datei?

**Comment by dietmarpravida** [comment]
landeck/2_V_H.2 = 2 V H.2

**Comment by sandrakrause** [comment]
Zu Landeck 2_V_H.g33:
In der Datei steht leider gar kein Datum.
   ```
<relation name="temp-pre">
      <source uri="faust://bibliography/landeck1981">S.210</source>
      <item uri="faust://document/landeck/2_V_H.g33"/>
      <item uri="faust://document/landeck/2_V_H.n"/>
   </relation>
```

Zu Landeck S. 88f:
In der Datei steht sowohl 2_V_H.i als auch 2_V_H, ein Tippfehler ist da wohl eher unwahrscheinlich.
 ```
<relation name="temp-pre">
      <source uri="faust://bibliography/landeck1981">S.88-89</source>
      <comment>Bezug auf Tgb; Datierung auf Hs. Apr. 30.. .</comment>
      <item uri="faust://document/landeck/2_V_H.i"/>
      <item uri="faust://document/landeck/2_H"/>
   </relation>
```

**Comment by dietmarpravida** [comment]
ja, es ist wieder der fünfte Akt von H gemeint

**Comment by dietmarpravida** [comment]
statt "2_V_H.g33" sollte es wohl "2_V_H.33" heißen. Ob genau das gemeint war, steht dahin; falsch ist es aber (im Sinne Landecks) nicht

**Comment by dietmarpravida** [comment]
Ein generelles Probem ist es, wenn Landecks "2_V_H" (= fünfter Akt in der Reinschrift) zu "2_H" aufgelöst wird und analog bei Fischer-Lamberg "2_II_H" und "2_III_H"  (= zweiter/dritter Akt in der Reinschrift) auch jeweils zu "2_H". Wir erzeugen so ganz unnötig Datierungswidersprüche, die hinterher wieder aufgeöst werden müssen.

**Comment by thvitt** [comment]
vielleicht zu (Pseudo-)inskriptionen auflösen?

**Comment by dietmarpravida** [comment]
geht das?

**Comment by thvitt** [comment]
naja, wenn man’s als generische Regel formulieren kann …

Ich habe grade mal eine Änderung gepusht, die alle `faust://document/(wa|wa_faust)/2_<Akt>_H` zu `faust://inscription/faustedition/2_H/<Akt>` macht, kannst ja in ein paar Minuten mal schauen was dabei herausgekommen ist.

**Comment by gerritbruening** [comment]
Das lese ich mit großem Interesse. @thvitt, heißt das, wir können aus `faust://document/wa_faust/2_H` jeweils eine `inscription` machen, die dann auch im Balkendiagramm so dargestellt wird?
Es ist nämlich so, dass immer dieselbe Datierung für H (1831) dort zu Problemen führt, weil dem die relative Chronologie in den einzelnenn Szenen oft widerspricht, also z.B. 2_H --> I_H.0a --> C.1_12 und nicht 2_H ganz am Ende.
Und kann ich auch unterhalb der Akt-Grenze arbeiten?

**Comment by thvitt** [comment]
Im Balkendiagramm gibt es keine Inskriptionen. Nur als Knoten in der Makrogenese.

**Comment by dietmarpravida** [comment]
die Anschlussdiskussion zu den kten von H steht jetzt unter #630

**Comment by dietmarpravida** [comment]
@sandrakrause Haben Sie die Siglen nach den folgenden Posts geändert bzw. ergänzt? Oder ist das noch zu machen?

- [ ] https://github.com/faustedition/xml/issues/603#issuecomment-419497538
- [ ] https://github.com/faustedition/xml/issues/603#issuecomment-419498812
- [ ] https://github.com/faustedition/xml/issues/603#issuecomment-419499838
- [ ] https://github.com/faustedition/xml/issues/603#issuecomment-421015434

**Comment by sandrakrause** [comment]
Ja, die sind erledigt.

**Comment by dietmarpravida** [comment]
Inskription steht jetzt unter #643; hier schließe ich
