### ISSUE TITLE
Provide absolute dating for prints

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#605]
>(I wonder why the prints lack absolute dating information)

https://github.com/faustedition/faust-gen-html/issues/567#issuecomment-412012351

**Comment by dietmarpravida** [comment]
- J.1 : Erscheinungsdatum 00-00-1782
- S 7 : Erscheinungsdatum zur Ostermesse 1790, zwischen 00-04-1790 und 00-06-1790, QuZ I, Nr. 419, 421, 423
- J.2 : Erscheinungsdatum 07-04-1808 (Nr. 84), 13-04-1808 (Nr. 89), 03-05-1808 (Nr. 108)
- A 8 : Erscheinungsdatum zur Ostermesse 1808, zwischen 00-04-1808 und 00-05-1808, QuZ I, Nr. 1022, 1027 
- D.1 : Erscheinungsdatum vor Michaelismesse 1808, zwischen 00-06-1808 und 00-10-1808, QuZ I, Nr. 1030, 1036; QuZ IV, Nr. 1240
- D.2 : Erscheinungsdatum 00-00-1816, QuZ I, Nr. 1313
- B 8 : Erscheinungsdatum zur Ostermesse 1817, zwischen 00-04-1808 und 00-05-1808, QuZ I, Nr. 1312, 1340, 1360
- Ba 8 : Erscheinungsdatum zweite Hälfte 1817, zwischen 00-06-1817 und 00-12-1817
- D.3 : Erscheinungsdatum 00-00-1821, QuZ IV, Nr. 1240, 1249
- D.4 : Erscheinungsdatum 00-09-1825, QuZ IV, Nr. 1789 
- D.4alpha : Erscheinungsdatum 00-09-1825 (vermutlich)
- C.1 4 : Erscheinungsdatum zur Ostermesse 1827, zwischen 15-04-1827 und   00-05-1827, QuZ II, Nr. 1063
- C.1 4alpha
- C.1 12 : Erscheinungsdatum zur Ostermesse 1828, zwischen 00-04-1818 und 00-05-1828, QuZ II, Nr. 1255, 1282
- C.1 41 : Erscheinungsdatum zur Ostermesse 1833, 00-03-1833, QuZ III, Nr. 182, 311
- C.3 4 : Erscheinungsdatum nach Ostern 1828, zwischen 00-04-1828 und 00-05-1828, QuZ II, Nr. 1255 (nach Ostern)
- C.3 12 : Erscheinungsdatum zwischen 00-03-1829 und 00-10-1829, QuZ II, Nr. 1287, 1636
- C.3 41 : Erscheinungsdatum zur Ostermesse 1833, 00-04-1833, QuZ III, Nr. 182, 311
- Q : Erscheinungsdatum erstte Hälfte 1836, zwischn  16-03-1836 und 11-06-1836, QuZ IV, Nr. 487

**Comment by dietmarpravida** [comment]
@gerritbruening Ist C.1 4alpha geichzeitig mit C.1 41?

**Comment by dietmarpravida** [comment]
@thvitt Wo sollen die absoluten Daten für die Drucke eingetragen werden?

**Comment by thvitt** [comment]
`xml/macrogenesis/print.xml`? oder ein eigenes XML-File im Macrogenesis-Baum, ist mir egal

**Comment by gerritbruening** [comment]
> @gerritbruening Ist C.1 4alpha geichzeitig mit C.1 41?

Nein, ich würde Gleichzeitigkeit mit C.3 4 annehmen.
Ich habe nur gerade nicht den Überblick über die sonstigen Bände von C.2alpha. Sagt Hagen nichts dazu?

**Comment by dietmarpravida** [comment]
müsste in den "Beiträgen zur Goetheforschung" stehen, die aber schon seit längerem vermisst werden; dauert also, bis ich eines Exemplars habhaft werde

**Comment by gerritbruening** [comment]
Danke @dietmarpravida.

Zwischen
```xml
    <!--  D.2 : Erscheinungsdatum 00-00-1816, QuZ I, Nr. 1313 -->
    <date notBefore="1816-01-01" notAfter="1816-12-31">
        <source uri="faust://bibliography/quz_1">Nr. 1313</source>
        <item uri="faust://print/hagen/D.2"/>
    </date>
    <!--  B 9 : Erscheinungsdatum zur Ostermesse 1817, zwischen 00-04-1817 und 00-05-1817, 
        QuZ I, Nr. 1312, 1340, 1360 -->
    <date notBefore="1817-04-01" notAfter="1817-05-31">
        <source uri="faust://bibliography/quz_1">Nr. 1312, 1340, 1360</source>
        <item uri="faust://print/hagen/B"/>
    </date>
```
und
```xml
    <relation name="temp-pre">
        ...
        <item uri="faust://print/hagen/B"/>
        <item uri="faust://print/hagen/D.2"/>
```
haben wir jetzt einen Widerspruch (Herstellungs- vs. Auslieferungszeitpunkt).

**Comment by gerritbruening** [comment]
> - C.1 12 : Erscheinungsdatum zur Ostermesse 1828, zwischen 00-04-1818 und 00-05-1828, QuZ II, Nr. 1255, 1282
...
> - C.3 4 : Erscheinungsdatum nach Ostern 1828, zwischen 00-04-1828 und 00-05-1828, QuZ II, Nr. 1255 

@dietmarpravida: "zu Ostern", "nach Ostern" -- Zeitintervalle aber gleich?

**Comment by gerritbruening** [comment]
Alles in `xml/macrogenesis/self/self_print.xml` eingetragen.

**Comment by dietmarpravida** [comment]
@gerritbruening shouldn't we flag those datings als "self"?

**Comment by gerritbruening** [comment]
> @gerritbruening shouldn't we flag those datings als "self"?

Tun wir das nicht? 
z.B.
```xml
  <relation name="temp-pre">
    <source uri="faust://self"/>
    <comment>eigh. Reinschrift</comment>
    <item uri="faust://document/faustedition/2_I_H.8"/>
    <item uri="faust://document/faustedition/2_I_H.9"/>
    <!--08-12-1827-->
  </relation>
```
