### ISSUE TITLE
Findbuch-Siglen droppen

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#608]
Siglen, die alphanumerisch fortgesetzt werden und nur im GSA-Verzeichnis vorkommen:
Sollen die noch aufgenommen werden?

**Comment by dietmarpravida** [comment]
Müssten wir uns da eine Kopie der Seite aus dem GSA geben lassen? Wäre sowieso sinnvoll.

**Comment by dietmarpravida** [comment]
@gerritbruening gehört das zu  #314?

**Comment by gerritbruening** [comment]
Nein, da geht es um die Pseudeo-Signaturen für Reproduktionen, die nur zu internen Zwecken eingeführt wurden.

**Comment by dietmarpravida** [comment]
Wir brauchen eine Liste aller Findbuch-Verweise in den Dateien; in Weimar muss man dann auf Vollständigkeit prüfen und ggf. vervollständigen: Um die Verständlichkeit der Datierungseinträge zu wahren, sollen die Siglen nicht auf unsere Siglierung umgestellt werden.

**Comment by dietmarpravida** [comment]
https://faustedition.uni-wuerzburg.de/new/xml-query/?folder=document&xpath=%2F%2Ff%3Aidno%5B%40type%3D%22gsa_findbuch%22%5D&mode=xml

**Comment by gerritbruening** [comment]
> Müssten es nicht mehr sein?

Ja, müssten es. Soll ich SH fragen?

Bei der Verzeichnung ist mir nicht klar, ob die im Findbuch stehenden Klammern wie `<H.1a>` einfach weggelassen werden können.

**Comment by thvitt** [comment]
gibt nochn paar auskommentierte

<pre><font color="#8AE234"><b>faust/2.2/gsa_390006.xml</b></font>
<font color="#FCE94F"><b>24</b></font>:      &lt;!--&lt;idno type=&quot;gsa_<span style="background-color:#C4A000"><font color="#2E3436">findbuch</font></span>&quot;&gt;2 II H.24&lt;/idno&gt;--&gt;
<font color="#FCE94F"><b>67</b></font>:      &lt;f:bemerkung&gt;im <span style="background-color:#C4A000"><font color="#2E3436">Findbuch</font></span>, bei Fischer-Lamberg und Bohnenkamp als H.24 beschrieben; zur Entstehung vgl. Bohnenkamp, S.506, = späteres Konzept im Vgl. mit II H.22 (25/XVII,7,23*a), Vorlage für II H.24 (25/XVII,7,24*a), = Vorlage für II H.24 (25/XVII,7,24), &lt;/f:bemerkung&gt;   

<font color="#8AE234"><b>faust/2.2/gsa_391427.xml</b></font>
<font color="#FCE94F"><b>24</b></font>:      &lt;!--&lt;idno type=&quot;gsa_<span style="background-color:#C4A000"><font color="#2E3436">findbuch</font></span>&quot;&gt;H.23&lt;/idno&gt;--&gt;

<font color="#8AE234"><b>faust/0/gsa_390028.xml</b></font>
<font color="#FCE94F"><b>42</b></font>:         &lt;!-- siehe auch <span style="background-color:#C4A000"><font color="#2E3436">Findbuch</font></span>einleitung;  

</pre>

**Comment by dietmarpravida** [comment]
> ob die im Findbuch stehenden Klammern wie <H.1a> einfach weggelassen werden können

Können sie meiner Ansicht nach wohl, das wird bei uns durch die Angabe "Findbuch" klargemcht

**Comment by dietmarpravida** [comment]
> Soll ich SH fragen

ja

**Comment by dietmarpravida** [comment]
> auskommentierte

Dioe könnten wir dann entkommentieren und in gewöhnliche Siglenangaben überführen

**Comment by dietmarpravida** [comment]
machen wir nicht mehr zur 1.0, nur die Fälle, wo es Referenzprobeme gibt, müssen durch Umstellen auf unsere Siglen geklärt werden

**Comment by gerritbruening** [comment]
Habe SH um Auskunft gefragt.

**Comment by gerritbruening** [comment]
Die Findbuch-Siglen wurden von Weimar wieder verworfen, auch nicht ins Inventar aufgenommen. Sie sollen bei uns einfach wegfallen. Oder gibt es Forschung, die darauf verweist? Bei Bohnenkamp finde ich nichts.

**Comment by dietmarpravida** [comment]
Man versteht manchmal die Siglierung bei Landeck (wohl auch bei F-L und abr) nicht, wenn man nicht weiß, dass da eine Findbuch-Sigle zugrundeliegt. Aber das ist ein Luxusproblem. Wegen mir können wir die Findbuch-Siglen beseitigen.

**Comment by thvitt** [comment]
könnt ihr die vier treffer nicht einfach auskommentieren?

**Comment by dietmarpravida** [comment]
ja

**Comment by dietmarpravida** [comment]
391502  und 390595  Siglen korrigiert und auskommentiert
