### ISSUE TITLE
	2 III H.54b earlier than H.54a and H.54a-c later than H.56

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#609]
Können wir diese Siglen umbenennen: 

- [x] 2 III H.54b (jetzt)  = `uri="KK123_23.xml"` ->2 III H.56a (neu)
- [x] 2 H III 54a (jetzt)  = `uri="KK123_22.xml"` -> 2 III H.56b (neu)
- [x] 2 III H.54c (jetzt)  = `uri="KK123_07.xml"` -> 2 III H.56c (neu)

In der Buchausgabe werden sie nicht verwendet

**Comment by dietmarpravida** [comment]
Siehe auch #613

**Comment by dietmarpravida** [comment]
Die Verszahen sind hier kein Problem, da alle mit 9482 beginnen.

**Comment by dietmarpravida** [comment]
@thvitt Wie soll die Umbennennung (hier und in #613) am besten vorgenommen werden? Kann man das gleich über den gesamten Datenbestand (also inklusive Genese etc.) hinweg machen? (Obwoh sie vermutlich sonst nirgends vorkommen dürften.)

**Comment by dietmarpravida** [comment]
@thvitt Wird auf 2 III H.54b 2 H III 54a 2 III H.54c in unseren Daten verwiesen?

**Comment by thvitt** [comment]
In unseren Makrogenesedaten?
* http://dev.faustedition.net/macrogenesis/2_III_H.54b nein¹
* http://dev.faustedition.net/macrogenesis/2_III_H.54a nein¹
* http://dev.faustedition.net/macrogenesis/2_III_H.54c nein¹

¹ zumindest konnte kein Verweis darauf aufgelöst werden

In den XML-Daten gibt es drei Treffer

1. document/archival/gm_duesseldorf/KK123_07.xml:      `<note>Gleiche Papierart wie faust://document/faustedition/2_III_H.54a, aber nicht gleiches Folio-Blatt.</note>`
2. document/archival/gm_duesseldorf/KK123_21.xml:      `<note>Ursprünglich Folioblatt-Einheit mit faust://document/faustedition/2_III_H.54b.</note>`
3. document/archival/gm_duesseldorf/KK123_22.xml:      `<note>Gleiche Papierart wie faust://document/faustedition/2_III_H.54c, aber nicht gleiches Folio-Blatt.</note>`

**Comment by dietmarpravida** [comment]
danke!

**Comment by dietmarpravida** [comment]
- [ ] document/archival/gm_duesseldorf/KK123_07.xml: <note>Gleiche Papierart wie faust://document/faustedition/2_III_H.54a, aber nicht gleiches Folio-Blatt.</note>
- [ ]     document/archival/gm_duesseldorf/KK123_21.xml: <note>Ursprünglich Folioblatt-Einheit mit faust://document/faustedition/2_III_H.54b.</note>
- [ ]     document/archival/gm_duesseldorf/KK123_22.xml: <note>Gleiche Papierart wie faust://document/faustedition/2_III_H.54c, aber nicht gleiches Folio-Blatt.</note>

**Comment by dietmarpravida** [comment]
2 III H.54b (alt) = KK123:x
2 III H.54a (alt) = KK123:y
2 III H.54c (alt) = KK123:z
