### ISSUE TITLE
strange display of Archivsignatur for 2 III H.58b 

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#611]
![2 iii h58b](https://user-images.githubusercontent.com/26788529/45505097-f6938400-b78b-11e8-88ed-abf29b9a9070.JPG)

Sind die `.;` vor der Signatur ein Kodierungsproblem?

**Comment by dietmarpravida** [comment]
@gerritbruening gehört das auch zu #314?? (ist dort mit abgebildet)

**Comment by gerritbruening** [comment]
= #314
