### ISSUE TITLE
Unknown Uri faust://document/wa/2_(oS) - kann entfernt werden

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#612]
Es handelt sich um ein Entstehungszeugnis (Tagebucheintrag Eckermann), das nicht als Handschrift geführt werden muss. Kann entfernt werden.

**Comment by dietmarpravida** [comment]
Unter den Entstehungsdokumenten anscheinend bereits enthalten (Eckermann Januar 1830). Die Textidentität mit Houbens Druck sollte sicherheitshalber nochmal überprüft werden (falls nicht schon geschehen).

**Comment by dietmarpravida** [comment]
geht es hier um 390376? Dann gehört das zu #627

**Comment by sandrakrause** [comment]
Verweis aus Datierungsdatei entfernt.
