### ISSUE TITLE
2 III H58.b later than 2 III H.59

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#613]
umbenennen:

- [x] 2 IIIH.58b (jetzt) -> 2 IIIH.59a (neu)
- [x] 2 IIIH.59a (jetzt) -> 2 IIIH.59b (neu)
- [x] 2 IIIH.59b (jetzt) -> 2 IIIH.59c (neu)

**Comment by dietmarpravida** [comment]
Die Verszahen sind hier kein Problem, da alle mit 9482 beginnen.

**Comment by dietmarpravida** [comment]
Verszahl ist hier kein Problem

**Comment by dietmarpravida** [comment]
@thvitt wird in unseren Daten auf 2 IIIH.58b 2 IIIH.59a 2 IIIH.59b verwiesen? Wenn nein, benenne ich sie einfach um. Wenn doch, brauchte ich deine Hilfe.

**Comment by thvitt** [comment]
nö
