### ISSUE TITLE
corr in diplomatic transcript 

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#615]
The following test case on [p. 22 (23.xml) of the Testhandschrift](http://dev.faustedition.net/document?sigil=Testhandschrift&page=22&view=facsimile_document) will be read as `Händedruck` after performing the TEI updates & XML cleanup, since the bare `corr` will be removed:

current documentary XML
```xml
                <ge:line>Händed<corr>r</corr>uck, för<choice>
                        <sic>t</sic>
                        <corr>d</corr>
                    </choice>ert, <choice>
                        <sic>winkende</sic>
                        <corr>würckende</corr>
                    </choice>, Heidenv<sic>ckol</sic></ge:line>
```
future XML
```xml
                <line>Händedruck, för<choice>
                        <sic>t</sic>
                        <corr>d</corr>
                    </choice>ert, <choice>
                        <sic>winkende</sic>
                        <corr>würckende</corr>
                    </choice>, Heidenvckol</line>
```
if this is ok, simply close this issue, otherwise reassign with instructions on when to keep the bare corr

**Comment by gerritbruening** [comment]
Thanks for helping me to clarify this.
"Dropp" is intended to be `<xsl:template match="corr"/>`-like, so that we have `Händeduck` (yes, "Hände-Ente") after the processing.
If we do this, wouldn't it be consistent to `select` the `choice/sic/text()` and drop `choice/corr` too?

**Comment by thvitt** [comment]
> If we do this, wouldn't it be consistent to select the choice/sic/text() and drop choice/corr too?
you decide.

**Comment by thvitt** [comment]
OTOH, no, I do not like this kind of markup adjustments in the current phase – I fear it’s a kind of Pandora’s box, and I would prefer to stay with the issues we decided on earlier and those that are neccessary for validation.

corr fix: https://github.com/faustedition/faust-schema/commit/b01d386a49190d9d7a8c95e5c20fcdad5f9012de
