### ISSUE TITLE
III H.6:1

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#621]
In den Metadaten wird angegeben, die entsprechende WA-Sigle sei III H.6. Das ist im Grunde nicht ganz richtig, denn WA_III H.6 bezieht sich sowohl auf H.6:1 wie auf _:2. @gerritbruening Was ist hier zu machen?

Siehe auch https://github.com/faustedition/xml/issues/602#issue-357715884

**Comment by gerritbruening** [comment]
Aus meiner Sicht kann weder eine andere WA-Sigle noch gar keine angegeben werden.
