### ISSUE TITLE
B9 / D.2

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#623]
Zwischen
```xml
    <!--  D.2 : Erscheinungsdatum 00-00-1816, QuZ I, Nr. 1313 -->
    <date notBefore="1816-01-01" notAfter="1816-12-31">
        <source uri="faust://bibliography/quz_1">Nr. 1313</source>
        <item uri="faust://print/hagen/D.2"/>
    </date>
    <!--  B 9 : Erscheinungsdatum zur Ostermesse 1817, zwischen 00-04-1817 und 00-05-1817, 
        QuZ I, Nr. 1312, 1340, 1360 -->
    <date notBefore="1817-04-01" notAfter="1817-05-31">
        <source uri="faust://bibliography/quz_1">Nr. 1312, 1340, 1360</source>
        <item uri="faust://print/hagen/B"/>
    </date>
```
und
```xml
    <relation name="temp-pre">
        ...
        <item uri="faust://print/hagen/B"/>
        <item uri="faust://print/hagen/D.2"/>
```
haben wir jetzt einen Widerspruch (Herstellungs- vs. Auslieferungszeitpunkt).

**Comment by dietmarpravida** [comment]
```xml
    <relation name="temp-pre">
        ...
        <item uri="faust://print/hagen/B"/>
        <item uri="faust://print/hagen/D.2"/>
```
dürfte (wenn man mit Erscheinungsterminen rechnet) einfach falsch sein

**Comment by gerritbruening** [comment]
Dann sollten wir, wenn sich das unterscheidet, eher den Satzzeitpunkt nehmen.

**Comment by dietmarpravida** [comment]
B 9: Satz 00-10-1816 (QuZ I, Nr. 1297), Herstellung not after 31-03-1817 (Fischer 2003, Bd. 2, S. 87)

Laut QuZ I, Nr. 1444 müsste D.2 "in der ersten Hälfte von 1816" gedruckt worden sein (00-01-1816 bis 00-06-1816). Dann könnte D.2 aber nicht aus dem umbrochenen Satz von B stammen, da B 9 im Oktober "ausgesetzt" (QuZ I, Nr. 1297) wurde. Reichels Angabe "in der ersten Hälfte von 1816" kann aber nicht stimmen, D.2 ist wegen Übereinstimungen zwischen A und B gegen D.2 ziemlich sicher ein abgeleiteter Druck. Ich würde daher annehmen, dass D.2 Oktober-Dezember 1816 gesetzt wurde, ohne dass ein Zeugnis dies bestätigen könnte.

**Comment by gerritbruening** [comment]
Soll ich dann B9 absolut datieren, und D.2 nicht, sondern nur die relative Chronologie B9 --> D.2 angeben?

**Comment by dietmarpravida** [comment]
beides: B früher als D.2 und D.2 00-00-1816, wenn das keinen Widerspruch ergibt

**Comment by gerritbruening** [comment]
Habe jetzt in den Daten B9 auf Oktober und D.2 auf nach B9 datiert.
