### ISSUE TITLE
C.1 12 / C.3 4

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#624]
Aus #605:

> - C.1 12 : Erscheinungsdatum zur Ostermesse 1828, zwischen 00-04-1818 und 00-05-1828, QuZ II, Nr. 1255, 1282
...
> - C.3 4 : Erscheinungsdatum nach Ostern 1828, zwischen 00-04-1828 und 00-05-1828, QuZ II, Nr. 1255 

@dietmarpravida: "zu Ostern", "nach Ostern" -- Zeitintervalle aber gleich?

**Comment by dietmarpravida** [comment]
die Daten folgen den Angaben in den Quellen und sind im Zweifelsfall den Umschreibungen vorzuziehen; insofern gibt es hier kein Problem
