### ISSUE TITLE
check dating of 2_I_H.10

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#625]
https://github.com/faustedition/xml/issues/438#issue-343389147

**Comment by dietmarpravida** [comment]
it ist quite safe to date all the verses between 24-09-1827 to 29-09-1827 (Bohnenkamp, S. 322), `<comment>Über Rest der Handschrift keine Aussage über Datierung möglich</comment>` is a misunderstanding of what abr actually wrote

**Comment by gerritbruening** [comment]
Mir ist nicht klar, was hier stehen soll:
```xml
   <!--  / 25/XVII,4,12 /  / I H10 /  -->
   <date notBefore="1827-09-24">
      <comment>direkter Anschluss von 5650-5653 an I H9a</comment>
      <source uri="faust://bibliography/bohnenkamp1994">S.322</source>
      <item uri="faust://inscription/wa/2_I_H.10/i_var_u"/>
   </date>
   <!-- geprüft -->
   <date>
      <comment>Über Rest der Handschrift keine Aussage über Datierung möglich</comment>
      <source uri="faust://bibliography/bohnenkamp1994">S.322</source>
      <item uri="faust://inscription/wa/2_I_H.10/i_uebrige"/>
   </date>
   <!-- geprüft -->
   <date>
      <comment>Über Rest der Handschrift keine Aussage über Datierung möglich</comment>
      <source uri="faust://bibliography/bohnenkamp1994">S.322</source>
      <item uri="faust://inscription/wa/2_I_H.10/i_v"/>
   </date>
   <!-- geprüft -->
```
bitte um genauere Instruktionen.
Soll einfach die gesamte Handschrift datiert werden statt der Inskriptionen? Und die Inskriptionen dann nur relativ zueinander? Würde die Sache vereinfachen.

**Comment by dietmarpravida** [comment]
> Soll einfach die gesamte Handschrift datiert werden statt der Inskriptionen?

ja

**Comment by gerritbruening** [comment]
done
