### ISSUE TITLE
introduce faust-sigils C1 41 and C3 41

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/xml#628]
Die werden in der Genese andauernd benötigt, wir sollten sie als honette Faust-Siglen einführen

**Comment by dietmarpravida** [comment]
@sandrakrause

**Comment by gerritbruening** [comment]
Erstmal das web Issue klären.

**Comment by gerritbruening** [comment]
https://github.com/faustedition/faust-web/issues/429
