### ISSUE TITLE
Define August/September 1798

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#635]
Betrifft H P3, H P5 und H P5a.
Zu den ersteren beiden wird bei derselben Bohnenkamp-These (S. 216), `notBefore="1798-08-15" notAfter="1798-09-15"` angegeben, bei H&nbsp;P5a dagegen `notBefore="1798-08-01" notAfter="1798-09-30"`. Was ist richtig / soll gelten?

**Comment by dietmarpravida** [comment]
> notBefore="1798-08-15" notAfter="1798-09-15"

nach Schillemeit, Vorspiel; würde ich für alle drei übernehmen

**Comment by gerritbruening** [comment]
Gut, siehe jetzt https://faustedition.uni-wuerzburg.de/wiki/index.php/Handschriftendatierung#August.2FSeptember_1798.

**Comment by gerritbruening** [comment]
In den Daten korrigiert.
