### ISSUE TITLE
Datierung von H P30

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#636]
> H P 30: die wahrscheinliche Zugehörigkeit zu den Walpurgisnachtvorarbeiten
> lässt eine Datierung analog zu H P 27ff. plausibel erscheinen. Angeben?

Was hieße das, "analog zu H P 27ff."?

**Comment by gerritbruening** [comment]
Habe in `xml/self_1.xml` das Intervall `notBefore="1800-11-02" notAfter="1800-11-08"` angegeben.

**Comment by dietmarpravida** [comment]
> die wahrscheinliche Zugehörigkeit zu den Walpurgisnachtvorarbeiten
lässt eine Datierung analog zu H P 27ff. plausibel erscheinen

woher kommt das?

`notBefore="1800-11-02" notAfter="1800-11-08"`

woher kommt das?

abr hat für H P27 "letzte Monate des Jahres 1800"

**Comment by gerritbruening** [comment]
> die ... erscheinen

ABR per Mail

> `notBefore="1800-11-02" notAfter="1800-11-08"`

kommt aus `xml/macrogenesis/handschriftendatierung_pre1800.xml`:

```xml
   <!-- 389816 / 25/XVII,2,17 /  / H P27 /  -->
   <date notBefore="1800-11-02" notAfter="1800-11-08">
      <source uri="faust://bibliography/bohnenkamp1994">S.162</source>
      <item uri="faust://document/bohnenkamp/H_P27"/>
   </date>
```

**Comment by dietmarpravida** [comment]
abr, S. 162 hat für H P27 "letzte Monate des Jahres 1800"; 2. Nov. bis 8. Nov. ergibt sich erst aus den Tagebucherwähnungen

**Comment by gerritbruening** [comment]
D.h., das Intervall der Bohnenkamp-Datierung sollte weiter gefasst werden als jetzt, und die Datierung aufgrund der Tagebucherwähnungen sollte als `self` angegeben werden?

**Comment by dietmarpravida** [comment]
ja

**Comment by gerritbruening** [comment]
Nein, doch nicht, ist OK gem. https://faustedition.uni-wuerzburg.de/wiki/index.php/Handschriftendatierung#1800.2F01.
