### ISSUE TITLE
testimony-Dateien ohne testimony-div

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#69]
> In den folgenden Dateien sind keine `<div>`s mit `<milestone unit="testimony"/>` gefunden worden:
 0 testimony divs in 390376
 0 testimony divs in 390376_0002
 0 testimony divs in anonym1779
 0 testimony divs in burkhardt1870
 0 testimony divs in geiger1882
 0 testimony divs in geiger1890
 0 testimony divs in gm_duesseldorf_KK1838
 0 testimony divs in gm_duesseldorf_KK1838
 0 testimony divs in harding1920_2
 0 testimony divs in klischnig1794
 0 testimony divs in schmidt1892
 0 testimony divs in wa_I_5_1
 0 testimony divs in wa_IV_1

**Comment by gerritbruening** [comment]
@sandrakrause, könnten Sie sich mal die Ihnen bekannten Fälle ansehen (also nicht die mit den sechsstelligen Nummern).

**Comment by sandrakrause** [comment]
anonym1779: fehlende Identifikationsnummer (s. #49 )
burkhardt1870: xml enthält nicht das richtige Zeugnis (s. #12 )
geiger1882: fehlende Identifikationsnummer (s. #25 )
geiger1890: xml-Datei entspricht nicht dem Entstehungszeugnis (s. #24 )
harding1920_2: Ist das ein Entstehungszeugnis? Kann es weder in Excel, noch in der Tabelle finden, ...
klischnig1794: xml enthält nicht das richtige Zeugnis (s. #27 )
schmidt1892: Laut Excel-Tabelle alternativer Druckort für Gräf 858. Das Zeugnis ist bereits in biedermann1889-1896_10.xml markiert.
wa_1_5_1: enthält nur ein Zeugnis, das auch markiert war, <div>-Tag fehlte, habe ich ergänzt.
wa_IV_1: Datei enthält keinen Text. Soweit ich das sehe, gibt es auch kein Zeugnis mit diesem Druckort.

**Comment by dietmarpravida** [comment]
harding1920 und klischnig1794 sind erledigt

**Comment by dietmarpravida** [comment]
@sandrakrause was ist hier noch aktuell?

**Comment by sandrakrause** [comment]
Die von mir oben genannten Fälle sind alle soweit erledigt. Gibt zumindest keine Problemfälle mehr.
Lediglich burkhardt1870 hat noch keinen Milestone-Eintrag.
Das war bei der Nachdigitalisierung dabei. Für die Auszeichnung hatte sich eine Studentin aus GBs Seminar gemeldet.

**Comment by gerritbruening** [comment]
Machen Sie zu `burkhardt1870` ruhig einen `milestone`, wir wissen ja nicht, was da noch kommt.

**Comment by sandrakrause** [comment]
ist erledigt
