### ISSUE TITLE
Pniower-Zeugnisse markieren

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#7]
Liebe @sandrakrause, könnten Sie sich am Schluss darum kümmern, dass die Mangels Buch nicht markierten Pniower-Zeugnisse markiert werden?
Diese findet man mit folgender XPath-Abfrage:
https://faustedition.uni-wuerzburg.de/new/xml-query/?folder=testimony&xpath=%2F%2Ftei%3Amilestone[%40unit%3D%22testimony%22+and+not(xml%3Aid[contains(.%2C%27graef_%27)])+and+not(%40spanTo)]&mode=xml

(Treffer aus `zeno-converted` sind zu ignorieren)

**Comment by gerritbruening** [comment]
Der "Pniower" hat sich angefunden, er liegt auf dem Tisch. Sie können die betreffenden Zeugnisse also auch gleich nachholen.

**Comment by sandrakrause** [comment]
Lieber @gerritbruening, die Pniower-Zeugnisse sind nun korrekt markiert.
