### ISSUE TITLE
Texte der ersten drei Entstehungszeugnisse

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#78]
Betrifft v.a. Goethe an Gotter

**Comment by dietmarpravida** [comment]
wie meinen?

**Comment by gerritbruening** [comment]
Es wäre schön, wenn zu den ersten drei Zeugnissen der Tabelle ein Text da wäre.

**Comment by dietmarpravida** [comment]
@sandrakrause ist das für Sie geklärt oder muss ich da nochwas tun?

**Comment by sandrakrause** [comment]
Ist soweit geklärt.
Nr. 2 liegt bisher nur als PDF vor, 1 und 3 sind aber vorhanden.

**Comment by dietmarpravida** [comment]
ist das noch aktuell?

**Comment by gerritbruening** [comment]
Pniower 7 fehlt noch.

**Comment by sandrakrause** [comment]
Pniower 7 hinzugefügt.
