### ISSUE TITLE
Zeno-Fehler korrigieren (Tgb, Briefe)

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#8]
Liebe @sandrakrause, könnten Sie nach Abschluss der Extraktion diese durchsehen und die genannten Fehler korrigieren?
https://faustedition.uni-wuerzburg.de/wiki/index.php/Zeno.org-WA_Fehlerliste

Die Excel-Tabelle hat auch eine entsprechende Spalte, "Fehler in Zeno". Prüfen Sie bitte, ob da nur dieselben Fehler nochmal stehen oder weitere angemerkt werden.

**Comment by sandrakrause** [comment]
Lieber @gerritbruening, die für die Tagebücher aufgeführten Fehler sind nun korrigiert.
