### ISSUE TITLE
Leere Spalte "Druckort"

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#94]
Bei Biedermann-Herwig-Nr. 5147 ist in der Excel-Tabelle kein Druckort angegeben.
@dietmarpravida könnten Sie das vielleicht überprüfen und mir sagen, wie hier weiter vorgegangen werden soll?

Bei QuZ II-509 ist die Spalte "Druckort" ebenfalls leer. Hier sind jedoch ein WA-Druckort sowie ein alternativer Druckort angegeben. Soll einer davon in "Druckort" übernommen werden? Nach welchem soll hier zititert werden?

**Comment by dietmarpravida** [comment]
Bie3 5147: Druckort ist Biedermann (2), Bd. 2, S. 628

QuZ II-509: diesen Eintrag gibt es in der Tabelle anscheinend nicht, was ist gemeint?

**Comment by sandrakrause** [comment]
Entschuldigung, da habe ich mich vertippt.
Es sollte QuZ II-905 heißen.

**Comment by dietmarpravida** [comment]
QuZ II-905 wird nach WA zitiert
