### ISSUE TITLE
Überschneidung: Bie3_5528 und Gräf_1271

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#95]
Biedermann-Herwig-Nr. 5528 befindet sich auf der Liste der noch zu digitalisierenden Zeugnisse.
Mir ist aufgefallen, dass dieses Zeugnis sich in großen Teilen mit Gräf-Nr. 1271 überschneidet. Das Gräf-Zeugnis haben wir bereits digitalisiert vorliegen. Das Biedermann-Zeugnis ist am Anfang ein wenig länger, jedoch scheint diese Passage keinen direkten Faust-Bezug zu haben.
Ist es dennoch nötig/erwünscht, das Biedermann-Zeugnis ebenfalls aufzunehmen?

**Comment by dietmarpravida** [comment]
wird nicht aufgenommen; lfd.Nr. (neuneu) 624 entfält, die Bie3-Nr. 5528 ist nach 623 übernommen, vorliegendes Digitallisat genügt
