### ISSUE TITLE
Gräf1215a - WA-Fundstelle erfasst nicht das komplette Gräf-Zeugnis

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/xml#96]
Das Gräfzeugnis enthält zusätzlich noch eine Fußnote mit einem Brief an Goethe, die in der WA-Fundstelle WA IV, 33, 247 nicht enthalten ist.
Wurde dieses Fremdzeugnis bereits aufgenommen? Soll es noch aufgenommen werden?

**Comment by dietmarpravida** [comment]
nein
